[core]
isPickableStartingUnit:true
name:buildDrone-ms
displayText:<DESTRUCTION HOVER DRONE IV>
displayDescription:建造?\n-毁灭?
class: CustomUnitMetadata
price:红宝石=140000,data=114514,crystal=1024,heac=1280,iron=12000
maxHp:25000
mass:1000
autoRepair:true
techLevel:1
buildSpeed:166s
availableInDemo: false
selfRegenRate:1
radius:40
isBio: false
isBuilder: true
canRepairBuildings:true
canReclaimResources:true
nanoRange:320
nanoBuildSpeed:10
nanoReclaimSpeed:5
builtFrom_1_name:stafc_huge
maxShield:20000
shieldRegen:0.1
energyMax:300
energyRegen:0.2
maxTransportingUnits:10
transportUnitsRequireMovementType: AIR,HOVER,LAND
[canBuild_69]
name:mine
[canBuild_999]
name: reclaim
pos:  -1
[canBuild_61]
name:mis
[canBuild_62]
name:bigmine
[canBuild_68]
name:wall3
[canBuild_72]
name:ASPU
[canBuild_73]
name:ASPC
[canBuild_1]
name:stafc1
[canBuild_2]
name:solPan1
[canBuild_3]
name:staTur1
[canBuild_4]
name:staTur5

[canBuild_6]
name:stacore1
[canBuild_7]
name:redTur
[canBuild_8]
name:gen1
[canBuild_9]
name:drill1
[canBuild_10]
name:drill2
[canBuild_13]
name:stafc_huge
[canBuild_14]
name:tractionBeam
[canBuild_15]
name:repairTur
[canBuild_16]
name:wall
[canBuild_17]
name:enewall
[canBuild_18]
name:Ltur1
[canBuild_19]
name:mine
[canBuild_20]
name:gen2
[canBuild_21]
name:fuelCell
[canBuild_22]
name:fighterDrone
[canBuild_23]
name:buildDrone
[canBuild_24]
name:minerDrone

[canBuild_26]
name:stafc2
[canBuild_27]
name:dronefc1
[canBuild_28]
name:hyperTractionBeam
[canBuild_29]
name:Ltur2
[canBuild_31]
name:block
[canBuild_32]
name:gball
[canBuild_33]
name:gball2
[canBuild_34]
name:fixwall
[canBuild_35]
name:3tur-repair
[canBuild_36]
name:3tur1
[canBuild_37]
name:emptur1
[canBuild_38]
name:expRea
[canBuild_39]
name:dust_coll
[canBuild_40]
name:engineer2
[canBuild_41]
name:table
[canBuild_42]
name:nukePad
[canBuild_43]
name:presser
[canBuild_44]
name:drill_iron
[canBuild_45]
name:drill_cyst
[canBuild_46]
name:drill_uran
[canBuild_47]
name:reactor
[canBuild_48]
name:RTG
[canBuild_49]
name:Scell
[canBuild_50]
name:wall2
[canBuild_51]
name:turwall
[canBuild_52]
name:buildDrone3
[graphics]
icon_zoomed_out:ROOT:/icon/btsp4.png
showHealthBar:false
showEnergyBar:false
showShieldBar:false
total_frames:1
image:builder3.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:80
shadowOffsetX:1
shadowOffsetY:1
lock_body_rotation_with_main_turret:true
[attack]
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:true
canAttack:true
maxAttackRange:380
shootDelay:50
setMainTurretAs:2
[turret_1]
x:0
y:0
invisible:true
barrelY:20
canShoot:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
turnSpeed:1
turnSpeedAcceleration:1
[turret_2]
x:0
barrelX:16
barrelY:30
barrelOffsetX_onOddShots:-32
y:0
projectile:las
invisible:true
turnSpeed:1
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:1
shoot_light: #00ffd0
delay:10
[turret_4]
x:0
barrelY:30
y:0
projectile:1
invisible:true
turnSpeed:1
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:1
shoot_light: #00ffd0
[turret_3]
x:0
barrelX:40
barrelY:0
barrelOffsetX_onOddShots:-80
y:0
projectile:2
invisible:true
turnSpeed:1
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:1
shoot_light: #eaff00
delay:5
[turret_sd]
canAttackMaxAngle:181
energyUsage:1
barrelY:0
x:0
y:0
projectile:0
turnSpeed:6
turnSpeedAcceleration:10
shoot_sound:ROOT:/SFX/blast.ogg
shoot_sound_vol:0.5
shoot_light: #00FFFF
[projectile_0]
targetGround:true
pushVelocity:10
areaDamage:10
areaRadius:200
directDamage:1
life:0
speed:50
frame:1
drawSize:0.01
teamColorRatio:1
image:ROOT:/unit/ball.png
explodeOnEndOfLife:true
areaHitAirAndLandAtSameTime:true
[turret_xxx]
x:0
y:0
barrelY:-10
laserDefenceEnergyUse:1
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life:60
fadeOut: true
attachedToUnit: false
color: #dbdbdb
fadeInTime:5
scaleFrom: 0.5
scaleTo:2.5
alpha: 0.45
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:90
shadow:true
xSpeedAbsoluteRandom:0.1
ySpeedAbsoluteRandom:0.5
[projectile_1]
targetGroundSpread:25
targetGround:true
areaDamage:100
areaRadius:150
targetSpeed:80
targetSpeedAcceleration:0.1
directDamage:50
teamColorRatio:1
image:ROOT:/unit/ball.png
life:100
speed:1
frame:5
drawSize:0.5
lightColor: #00ff51
lightSize:1.8
tags:pluse
spawnUnit:Mboom,mine*3,bigmine
trailEffect:CUSTOM:projectileTrail
trailEffectRate:8
[projectile_2]
targetSpeed:80
targetSpeedAcceleration:0.2
directDamage:150
teamColorRatio:1
image:ROOT:/unit/mic.png
life:100
speed:0.1
frame:1
drawSize:0.4
lightColor: #00ff51
lightSize:1.2
tags:pluse
spawnUnit:Sboom
trailEffect:CUSTOM:projectileTrail
trailEffectRate:5
[projectile_las]
pushForce:120
life:15
instant:true
instantReuseLast:true
instantReuseLast_alsoChangeTurretAim:true
moveWithParent:true
beamImage:ROOT:/unit/boat/battle ships/module/laser2.png
beamImageEnd:SHARED:beam1_end.png
beamImageStart:SHARED:beam1_start.png
beamImageOffsetRate:2
explodeEffect:NONE
explodeEffectOnShield:NONE
sweepOffsetFromTargetRadius:0.4
sweepSpeed:1
directDamage:140
color: #ddFFFF88
teamColorRatio:1
laserEffect:true
#spawnUnit:Sboom
[movement]
movementType:AIR
moveSpeed:1.5
moveAccelerationSpeed:0.5
moveDecelerationSpeed:0.01
maxTurnSpeed:0.8
turnAcceleration:0.2
landOnGround:true
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.06
noneGlobalExtraPriority:0.01
[decal_sd]
image:ROOT:/effect/4.png
onlyWhileActive:true
alwaysStartDirAtZero:true
imageScale:4.5
color: #00b3ff
order:1
alpha:self.energy/600+0.2
[effect_dust]
color: #ffffff
delayedStartTimerRandom:10
stripIndex: effects
frameIndex: 0
life:140
scaleFrom:0.6
scaleTo:3.5
priority:critical
alpha:0.4
xSpeedAbsoluteRandom:1
ySpeedRelativeRandom:1
ySpeedRelative:-3
hSpeedRandom:0.5
hSpeed:0.3
dirSpeedRandom:1
dirSpeed:2
yOffsetRelative:-35
teamColorRatio:0.1
atmospheric:true
[effect_dust2]
color: #ffffff
delayedStartTimerRandom:10
stripIndex: effects
frameIndex: 0
life:100
scaleFrom:0.6
scaleTo:5
priority:critical
alpha:0.4
xSpeedAbsoluteRandom:0.5
ySpeedRelativeRandom:0.8
ySpeedRelative:-3
hSpeedRandom:0.5
hSpeed:0.3
dirSpeedRandom:1
dirSpeed:2
yOffsetRelative:-35
teamColorRatio:1
atmospheric:true
[animation_dust]
onActions:move
effect_0.1s:{x:0,y:0,name:dust*4}
effect2_0.1s:{x:0,y:0,name:dust2*1}

[hiddenAction_ac]
autoTriggerOnEvent:created
showQuickWarLogToAllPlayers:[A <Build Drone Mk4> HAD BEEN CREAED! 有一架建造无人机IV型刚刚完成制造!]
[action_Mag]
text:发射磁爆
iconImage:ROOT:ele.png
buildSpeed:25s
price:data=4096,crystal=128
spawnUnits:Eboom2

[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*60
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*60)-60
yOffsetAbsolute:-45
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:60
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-45
onlyWhileActive:true

[decal_bar_sd]
color: #22ffda
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.shield / self.maxShield)*60
alwaysStartDirAtZero:true
isVisible:if not (self.shield == self.maxShield)
onlyOnNonPreview:true
xOffsetAbsolute:((self.shield / self.maxShield)*60)-60
yOffsetAbsolute:-40
alpha:0.8
onlyWhileActive:true
[decal_sd_back]
color: #004869
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.shield == self.maxShield)
imageScale:2
imageScaleX:60
alpha:0.5
yOffsetAbsolute:-40
alwaysStartDirAtZero:true
onlyOnNonPreview:true
onlyWhileActive:true

[decal_bar_en]
color: #ffd622
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.energy / self.maxEnergy)*15
alwaysStartDirAtZero:true
isVisible:if not (self.energy == self.maxEnergy)
onlyOnNonPreview:true
xOffsetAbsolute:((self.energy / self.maxEnergy)*15)-15
yOffsetAbsolute:30
alpha:0.7
onlyWhileActive:true
[decal_en_back]
color: #555522
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.energy == self.maxEnergy)
imageScale:2
imageScaleX:15
alpha:0.5
yOffsetAbsolute:30
alwaysStartDirAtZero:true
onlyOnNonPreview:true
onlyWhileActive:true

[decal_sctC]
image:ROOT:sct.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.04*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2

[attachment_1]
x:0
y:20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_2]
x:20
y:-20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_3]
x:-20
y:-20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_2e]
x:10
y:-30
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_3e]
x:-10
y:-30
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_l1]
x:0
y:-30
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_r1]
x:-20
y:-10
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur2
[attachment_4]
x:20
y:-10
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur2
[attachment_5]
x:0
y:-20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_4r]
x:20
y:20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:-45
onCreateSpawnUnitOf:emptur1
[attachment_5r]
x:-20
y:20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:45
onCreateSpawnUnitOf:emptur1
[attachment_6]
x:0
y:0
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur2
[attachment_5ff]
x:-10
y:-20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1
[attachment_5f]
x:10
y:-20
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:emptur1