[core]
name:buildDrone
displayText:建造无人机
displayDescription:携带纳米光束器,可以辅助建造和回收\n-由于携带超载的建造设备,移动速度远不及其他小型单位
class: CustomUnitMetadata
price:红宝石=150
maxHp:100
mass:1
autoRepair:true
techLevel:1
buildSpeed:7s
availableInDemo: false
selfRegenRate:0.1
radius:4
displayRadius:3
isBio: false
isBuilder: true
canRepairBuildings:true
canReclaimResources:true
nanoRange:90
nanoBuildSpeed:0.3
nanoReclaimSpeed:0.3
showActionsWithMixedSelectionIfOtherUnitsHaveTag:drone
tags:drone
[canBuild_2]
name: reclaim
pos:  -1
[graphics]
total_frames:1
image:builder.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:15
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttack:false
isFixedFiring:true
turretSize:3
turretTurnSpeed:3
[turret_1]
x:0
y:0
invisible:true
warmup:10
canShoot:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
turnSpeedAcceleration:0.2
[movement]
movementType: HOVER
moveSpeed:0.9
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.2
maxTurnSpeed:1
turnAcceleration:0.5
[ai]
buildPriority:0.1
noneInBaseExtraPriority:0.06
noneGlobalExtraPriority:0.1
maxEachBase:15
maxGlobal:120

#[action_1]
#text:666
#rw lua test
#inputAlertDialogSetTitle:Input someting pleaseinputSometing 
#buildSpeed:0s 
#alwaysSinglePress:true 
#canPlayerCancel:false 
#allowMultiplelnQueue:false 
#displayType: action 
#isVisible:true