[core]
showInEditor:false
name:emptur3
displayText:通用模块(大)
displayDescription:-宇宙无敌螺旋升天超级模块
maxHp:1023
# 这段话主要是对歪果仁说的 别嘲笑我的Plastic英语555
# A little bit about this unit
# I made this when I'm a green hand , the unit's original config was copy from another Chinese RWMOD named Abyss Star(really ).
#That's why this cfg have hp and shield (for a child unit,it's uncommon)
price:500
shieldDisplayOnlyDeflection:true
mass:1000
radius:12
[graphics]
icon_zoomed_out:ROOT:/icon/wall.png
scaleImagesTo:35
image:emp3.png
image_wreak:NONE
image_turret:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:true

[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:NONE
targetHeight:5
maxTurnSpeed:20
targetHeightDrift:1
[ai]
ai_upgradePriority:0.8

[action_1]
convertTo:laser2
displayType:upgrade
price:红宝石=300
text:炮塔-激光炮
buildSpeed:2s
whenBuilding_cannotMove:true
highPriorityQueue:true
