[core]
copyFrom:ROOT:RW_Engine/View/View.md,ROOT:RW_Engine/Module/LayoutInterpreter/ImportLayoutInterpreter.md,ROOT:RW_Engine/View/CommonCallBack.md

name:LineTextViewSystem
tags:LineTextViewSystem
isUnselectable:true
#存储所有TextViewUnit
@memory unitEpoll:unit[]
#该行所显示的文本
@memory text:string
#用于生成新的TextViewUnit
@memory needInitTVUnitSoltId:boolean
#需要新TextViewUnit的数量
@memory needNewTVUnitNum:number
#下标，决定自身坐标
#@memory slotId:number
#更新下标时，用于刷新自身坐标，纵向排列
#@memory setSoltIdY:float
#一行所能显示的最大量
@memory textMax:number
#自动换行
@memory autoWrap:boolean
showInEditor:false
@memory textScale:number

#因alsoTriggerActionRepeat无法使用逻辑，该memory用于表达要设置颜色的下标
@memory textColorStart:number
@memory textColor:number
@memory defaultTextColor:number


#
@memory settingCharSucceedTotals:number

@memory skinCommonHead:number

#
#@memory soltSize:number
@memory textMarginTop:number
@memory textMarginLeft:number


@memory temporaryFontId:number
@memory temporaryFontColumn:number





[hiddenAction_created]
buildSpeed:0.0s
autoTriggerOnEvent:created
resetCustomTimer:true
sendMessageTo:self.customTarget1
sendMessageWithTags:addLTVSystemToEpoll
#该Page默认所能显示的最大量
setUnitMemory:textMax=20,textColor=${_defaultTextColor},defaultTextColor=${_defaultTextColor},autoWrap=false,textScale=${defaultFontScale},textMarginTop=0,textMarginLeft=0

switchToTeam:memory.defaultTextColor

#刷新下标，由其它View触发，如PageTextViewSystem
#[hiddenAction_setSoltId]
#autoTriggerOnEvent:newMessage(withTag="setSoltId")
#纵向排列
#setUnitMemory:slotId=eventData("slotId",type="number"),setSoltIdY=self.customTarget1.y+memory.soltSize*memory.slotId,commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource
#teleportTo:createMarker(x=eventSource.x,y=memory.setSoltIdY)
#alsoTriggerAction:StartCommonCallBack,initTextViewUnitSoltId


#在创建新TextViewUnit时，TextViewUnit会通过该action添加到epoll
[hiddenAction_addTextViewUnitToEpoll]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="addTextViewUnitToEpoll")
setUnitMemory:unitEpoll[memory.unitEpoll.size] = eventSource


#[hiddenAction_refreshLocation]
#alsoTriggerAction:initTextViewUnitSoltId


#重新刷新每一个TextViewUnit的下标
[hiddenAction_initTextViewUnitSoltId]
buildSpeed:0.0s
highPriorityQueue:true
alsoTriggerAction:initingTextViewUnitSoltId
alsoTriggerActionRepeat:memory.unitEpoll.size

[hiddenAction_initingTextViewUnitSoltId]
buildSpeed:0.0s
highPriorityQueue:true

setUnitMemory:temporaryFontId=index-(index-(index%memory.textMax)),temporaryFontColumn=(index-(index%memory.textMax))/memory.textMax
sendMessageTo:memory.unitEpoll[index]
sendMessageWithTags:setSoltId
sendMessageWithData:slotId=memory.temporaryFontId,position=createMarker(x=self.x+(memory.temporaryFontId)*memory.textMarginLeft+${defaultfontSize}*memory.textScale*memory.temporaryFontId,y=self.y+memory.textMarginTop+${defaultfontSize}*memory.textScale*memory.temporaryFontColumn)
#.getOffsetRelative(y=-5)

#column=(index-(index%memory.textMax))/memory.textMax
#showMessageToAllPlayers:%{(index-index%memory.textMax)/memory.textMax}
#setUnitMemory:slotId=eventData("slotId",type="number"),setSoltIdX=self.customTarget1.x+memory.soltSize*memory.slotId,setSoltIdY=self.customTarget1.y+memory.soltSize*eventData("column",type="number")


#(length(memory.text)-1)*(memory.LTVSystem.readUnitMemory("setSoltIdY",type="number")/2))*(-1)



#${defaultfontSize}*memory.textScale*length(memory.text)

#length(memory.text)*(${defaultfontSize}*memory.LTVSystem.readUnitMemory("textScale",type="number")





#设置显示文本，过长将会截断
[hiddenAction_setText]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setText")
setUnitMemory:text=eventData("text",type="string"),needInitTVUnitSoltId=true,commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource
alsoQueueAction:needNewTextViewUnit,initSettingText
alsoTriggerOrQueueActionWithTarget:eventSource
#showMessageToAllPlayers:setText

[hiddenAction_viewText]
buildSpeed:0.0s
setUnitMemory:needInitTVUnitSoltId=true
alsoQueueAction:needNewTextViewUnit,initSettingText
alsoTriggerOrQueueActionWithTarget:eventSource
#设置显示文本的最大量
[hiddenAction_setTextMax]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setTextMax")
setUnitMemory:textMax=eventData("textMax",type="number"),commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource

alsoTriggerAction:StartCommonCallBack



#判断是否需要添加新的TextViewUnit
[hiddenAction_needNewTextViewUnit]
buildSpeed:0.0s
requireConditional:if length(memory.text) > memory.unitEpoll.size

setUnitMemory:needNewTVUnitNum=length(memory.text) - memory.unitEpoll.size

#调用spawnNewTextViewUnit生成
alsoTriggerAction:spawnNewTextViewUnit
alsoTriggerActionRepeat:memory.needNewTVUnitNum
alsoTriggerOrQueueActionWithTarget:thisActionTarget


[hiddenAction_spawnNewTextViewUnit]
buildSpeed:0.0s
spawnUnits:TextViewUnit
#在添加完后显示text
alsoQueueAction:initSettingText
alsoTriggerOrQueueActionConditional:if index+1 == memory.needNewTVUnitNum
alsoTriggerOrQueueActionWithTarget:thisActionTarget




#显示text
#<!----------这里使用三个alsoTriggerOrQueueActionWithTarget:thisActionTarget用于传递由setText传来的eventSource，用于跳过对commonHead设置颜色---------->
[hiddenAction_initSettingText]
buildSpeed:0.00s
requireConditional:if memory.needInitTVUnitSoltId == true and length(memory.text) <= memory.unitEpoll.size
alsoTriggerAction:initTextViewUnitSoltId
setUnitMemory:needInitTVUnitSoltId=false
#显示text
alsoQueueAction:doSettingText
alsoTriggerOrQueueActionWithTarget:thisActionTarget

[hiddenAction_doSettingText]
buildSpeed:0.0s
alsoTriggerAction:settingText
alsoTriggerActionRepeat:memory.unitEpoll.size
alsoTriggerOrQueueActionWithTarget:thisActionTarget

[hiddenAction_settingText]
buildSpeed:0.0s
sendMessageTo:memory.unitEpoll[index]
sendMessageWithTags:setChar
sendMessageWithData:char=substring(memory.text,index,index+1),color=select(substring(memory.text,index,index+1)==substring(thisActionTarget.readUnitMemory("commonHead",type="string"),index,index+1),thisActionTarget.readUnitMemory("commonHeadColor",type="number"),memory.textColor)


#设置字体颜色，默认全部设置
[hiddenAction_setTextColor]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setTextColor")
#
setUnitMemory:skinCommonHead=eventData("commonHeadLength",type="number"),commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource
alsoTriggerAction:StartCommonCallBack,settingTextColor
alsoTriggerActionRepeat:int(select(eventData("indexEnd",type="number") == 0,memory.unitEpoll.size,eventData("indexEnd",type="number")-eventData("indexStart",type="number")))

[hiddenAction_settingTextColor]
buildSpeed:0.0s
setUnitMemory:textColorStart=index+eventData("indexStart",type="number") + memory.skinCommonHead
sendMessageTo:memory.unitEpoll[memory.textColorStart]
sendMessageWithTags:setCharColor
sendMessageWithData:color=eventData("color",type="number")


#当一个字显示出来后加一，待全部显示完成后，向父物体发送ALLsettingCharSucceed
[hiddenAction_settingCharSucceedTotals]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="settingCharSucceed")

setUnitMemory:settingCharSucceedTotals=memory.settingCharSucceedTotals+1
alsoQueueAction:ALLsettingCharSucceed
alsoTriggerOrQueueActionConditional:if memory.settingCharSucceedTotals == memory.unitEpoll.size

[hiddenAction_ALLsettingCharSucceed]
buildSpeed:0.0s
sendMessageTo:self.customTarget1
sendMessageWithTags:ALLsettingCharSucceed
alsoTriggerAction:StartCommonCallBack

#sendMessageWithData:





[hiddenAction_setTextScale]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setTextScale")
setUnitMemory:textScale=eventData("textScale",type="number"),commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource

alsoTriggerAction:StartCommonCallBack,initTextViewUnitSoltId

[hiddenAction_setTextMarginLeft]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setTextMarginLeft")
setUnitMemory:textMarginLeft=eventData("marginLeft",type="number"),commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource

alsoTriggerAction:StartCommonCallBack,initTextViewUnitSoltId


[hiddenAction_setTextMarginTop]
buildSpeed:0.0s
autoTriggerOnEvent:newMessage(withTag="setTextMarginTop")
setUnitMemory:textMarginTop=eventData("marginTop",type="number"),commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource

alsoTriggerAction:StartCommonCallBack,initTextViewUnitSoltId

[action_setTextSize1]
text:setTextSize-小
setUnitMemory:textScale=memory.textScale-0.5
alsoTriggerAction:initTextViewUnitSoltId
[action_setTextSize2]
text:setTextSize-大
setUnitMemory:textScale=memory.textScale+0.5
alsoTriggerAction:initTextViewUnitSoltId
[action_setTextSize3]
text:setTextSize-间隔
setUnitMemory:textMarginLeft=memory.textMarginLeft+10
alsoTriggerAction:initTextViewUnitSoltId

