[core]
copyFrom:"""ROOT:RW_Engine/fonts/allFontsBase.ini"""
name:font-base
dont_load:true
showInEditor:false
isUnselectable:false
tags:font
@memory char:string
autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true



[decal_0]
layer:beforeUI
frame_width:45
frame_height:45
xOffsetAbsolute: 0
yOffsetAbsolute: 0
imageScale:memory.fontsScale
teamColors:true


#[decal_1]
#layer:beforeUI
#frame_width:45
#frame_height:45
#xOffsetAbsolute: 0
#yOffsetAbsolute: 0
#imageScale:memory.fontsScale
#teamColors:true
