[core]
name:cystDrop
displayText:晶体补给仓
displayDescription:-包含250晶体
class:CustomUnitMetadata
price:crystal=250
maxHp:8000
mass:12000
techLevel:1
availableInDemo:true
radius:20
isBio:false
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Sboom
explodeOnDeathGroundCollision:false
isBuilding:false
energyMax:45
energyRegen:0.1
startEnergyAtZero: true
@memory landed:boolean
#buildingToFootprintOffsetY:-20
tags:droper
showActionsWithMixedSelectionIfOtherUnitsHaveTag:droper
[graphics]
showEnergyBar:false
showQueueBar:false
drawLayer: ground2
icon_zoomed_out:ROOT:icon/site.png
total_frames:1
scaleImagesTo:35
image:pack64_cyst.png
image_wreak:NONE
image_shadow:pack64sdw.png
shadowOffsetX:1
shadowOffsetY:0.5
[attack]
canAttack:false
[movement]
moveSpeed:0
landOnGround: true
movementType:AIR
targetHeight:800
startingHeightOffset:800
maxTurnSpeed:0
ignoreMoveOrders:true
heightChangeRate: 3
fallingAcceleration:1
[hiddenAction_initA]
setBodyRotation:270
setHeight:2000
autoTriggerOnEvent:created
[hiddenAction_smoke]
spawnEffects:custom:smoke*15
autoTrigger:if not self.ground()
[hiddenAction_land]
setUnitMemory:landed =true
spawnEffects:custom:smoke3*60
autoTrigger:if self.ground() and memory.landed ==false
[effect_smoke]
createWhenOffscreen:true
physics:true
delayedStartTimerRandom:60
stripIndex: effects
frameIndex: 0
life:25
fadeOut: true
attachedToUnit: false
color: #ffc444
fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
hOffset:-120
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
hSpeedRandom:3
hSpeed:-12
dirSpeedRandom:5
dirSpeed:1.5
alsoEmitEffectsOnDeath:smoke2
[effect_smoke2]
createWhenOffscreen:true
physics:true
delayedStartTimerRandom:20
stripIndex: effects
frameIndex: 0
life:45
fadeOut: true
attachedToUnit: false
color: #ffffff
fadeInTime:5
scaleFrom: 3
scaleTo: 6
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.4
ySpeedAbsoluteRandom: 0.2
hSpeedRandom:1
hSpeed:-6
dirSpeedRandom:5
dirSpeed:1.5
[effect_smoke3]
delayedStartTimerRandom:60
physics:true
stripIndex: effects
frameIndex: 0
life:30
fadeOut: true
color: #ffffff
fadeInTime:5
scaleFrom: 2
scaleTo: 3
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom:8
ySpeedAbsoluteRandom:8
dirSpeedRandom:5
dirSpeed:1.5

[effect_left]
image:pack64L.png
imageShadow:pack64sdw.png
delayedStartTimerRandom:10
physics:true
life:120
fadeOut: true
fadeInTime:8
atmospheric:true
dirOffsetRandom:180
shadow:true
scaleFrom:0.6
alpha:1.5
xSpeedAbsolute:-6
xSpeedAbsoluteRandom:-2
hSpeed:1
physicsGravity:1
dirSpeedRandom:1
dirSpeed:-8
[effect_right]
image:pack64R.png
imageShadow:pack64sdw.png
delayedStartTimerRandom:10
physics:true
life:120
fadeOut: true
fadeInTime:8
atmospheric:true
dirOffsetRandom:180
shadow:true
scaleFrom:0.6
alpha:1.5
xSpeedAbsolute:6
xSpeedAbsoluteRandom:2
hSpeed:1
physicsGravity:1
dirSpeedRandom:1
dirSpeed:8
[action_recl-plc]
isVisible:false
text:占位符
description:plchd
price:红宝石=114
buildSpeed:10s

deleteSelf:true
[action_recl]
text:回收
description:回收发射仓(降落后)
price:crystal=-250,energy=45
buildSpeed:0s
spawnEffects:right,left
unitShownInUI: builder
deleteSelf:true
[decal_main]
basePosition:self.getOffsetAbsolute(0,-40)
layer:afterBody
image:eneLander64.png
imageScale:0.55
yOffsetAbsolute:40
imageScaleY:min(1,self.height/80)
alpha:select(memory.landed,0,1)