[core]
name:signSta
displayText:信号基站
displayDescription:-用来与外界通信\n-可用于购入资源和呼叫打击\n-建造多个信号基站以获得额外空间
class:CustomUnitMetadata
price:红宝石=4500
maxHp:800
mass:90
#buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
constructionFootprint:-1,0,1,1
footprint: -1,0,1,1
techLevel:1
buildSpeed:36.6s
availableInDemo:true
radius:30
tags:sta,signal
isBio:false
isBuilding:true
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Sboom
explodeOnDeathGroundCollision:false


[graphics]
icon_zoomed_out:ROOT:icon/site.png
total_frames:1
image:signalSta.png
image_wreak:stafcd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
scaleImagesTo:60
[attack]
canAttack:false
[movement]
movementType:HOVER
moveSpeed:0
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
maxTurnSpeed:0
turnAcceleration:0.1
[ai]
buildPriority:0.018
recommendedInEachBaseNum:6
[action_updt1]

buildSpeed:16.6s
text:占位符
price:红宝石=1000
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技
allowMultipleInQueue:false