[core]
name:signSta
displayText:信号基站
displayDescription:-用来与外界通信\n-可用于购入资源和呼叫打击\n-建造多个信号基站以获得额外空间\n-只能控制80范围内的装置
class:CustomUnitMetadata
price:红宝石=4500
maxHp:800
mass:90
#buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
constructionFootprint:-1,0,1,1
footprint: -1,0,1,1
techLevel:1
buildSpeed:36.6s
availableInDemo:true
radius:30
tags:sta,signal
isBio:false
isBuilding:true
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Sboom
explodeOnDeathGroundCollision:false


[graphics]
icon_zoomed_out:ROOT:icon/site.png
total_frames:1
image:signalSta.png
image_wreak:stafcd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
scaleImagesTo:60
[attack]
canAttack:false
[movement]
movementType:HOVER
moveSpeed:0
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
maxTurnSpeed:0
turnAcceleration:0.1
[ai]
buildPriority:0.018
recommendedInEachBaseNum:6
[action_updt1]
isVisible:false
buildSpeed:16.6s
text:占位符[WIP]
price:红宝石=1000
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技
allowMultipleInQueue:false
[action_upload]
#非常莫名其妙的偷懒
buildSpeed:0s
iconImage:up.png
isLocked:if nearestUnit(withTag="callableLauncher",withinRange=80) == null
isLockedMessage:无可用发射台
text:上载${resDisp}*${count}
description_zh:获得1000信用点
alsoTriggerAction:dialUpload
#sendMessageTo:self
#sendMessageWithTags:up
#sendMessageWithData:cdt=${cdt}
price:${res}=${count}
@define resDisp = 红宝石
@define res = 红宝石
@define count = 1500
#@define cdt = 1000

[action_buy]
#非常莫名其妙的偷懒
buildSpeed:0s
iconImage:down.png
isLocked:if nearestUnit(withTag="callableLander",withinRange=80) == null
isLockedMessage:无可用着陆台
text:请求${resDisp}*${count}补给
description_zh:消耗1000信用点
price:1000
sendMessageTo:nearestUnit(withTag="callableLander",withinRange=80)
sendMessageWithTags:${res}
@define resDisp = 红宝石
@define res = 红宝石
@define count = 1500
#@define cdt = 1000
[action_buy0]
pos:3
@copyFromSection:action_buy
@define resDisp = 硫化物
@define res = S
@define count = 2500
[action_buy1]
pos:5
@copyFromSection:action_buy
@define resDisp = 晶体
@define res = crystal
@define count = 250
[action_buy2]
pos:7
@copyFromSection:action_buy
@define resDisp = 铁
@define res = iron
@define count = 1250
[action_buy3]
pos:9
@copyFromSection:action_buy
@define resDisp = 合金
@define res = heac
@define count = 175
[action_buy4]
pos:11
@copyFromSection:action_buy
@define resDisp = 核素
@define res = rad
@define count = 50

[action_upload0]
pos:2
@copyFromSection:action_upload
@define resDisp = 硫化物
@define res = S
@define count = 2500
[action_upload1]
pos:4
@copyFromSection:action_upload
@define resDisp = 晶体
@define res = crystal
@define count = 250
[action_upload2]
pos:6
@copyFromSection:action_upload
@define resDisp = 铁
@define res = iron
@define count = 1250
[action_upload3]
pos:8
@copyFromSection:action_upload
@define resDisp = 合金
@define res = heac
@define count = 175
[action_upload4]
pos:10
@copyFromSection:action_upload
@define resDisp = 核素
@define res = rad
@define count = 50
[hiddenAction_dialUpload]
#I'm a function :P
autoTriggerOnEvent:newMessage(withTag="up")
sendMessageTo:nearestUnit(withTag="callableLauncher",withinRange=80)
#sendMessageWithData:eventData(name="cdt")
