[core]
transportUnitsAddUnloadOption: false
name:slauncher
displayText:发射台
displayDescription:-需要放置在基站的相邻格并垂直\n-消耗14kW
class:CustomUnitMetadata
price:红宝石=2000
maxHp:1500
mass:900
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
techLevel:1
#buildingToFootprintOffsetY:-20
#buildingSelectionOffset: -8
buildSpeed:18s
availableInDemo:true
radius:45
tags:sta
isBio:false
isBuilding:true
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Lboom
numBitsOnDeath: 20
borrowResourcesWhileAlive:电力=14
[graphics]
icon_zoomed_out:ROOT:icon/site.png
scaleImagesTo:60
image:slauncher.png
image_wreak:slauncherw.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

total_frames:1
[attack]
canAttack:false
maxAttackRange:20000
[movement]
movementType:HOVER
moveSpeed:0

maxTurnSpeed:0
targetHeight:1
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.05
maxEachBase:1
maxGlobal:5
[action_holder]
isVisible:false
text:占位符
buildSpeed:0
price:S=100
[action_doc]
isVisible:false
text:占位符2
pos:3
[action_launch1]
text:发射红宝石*1000,换取700$
iconImage:ROOT:/mine.png
description_zh:发射(红宝石*1000)
buildSpeed:4.5s
isLocked:if self.resource.isTran == 1
isLockedMessage:另一运输任务正在执行中!
price:红宝石=1000,ammo=1
fireTurretXAtGround: lc
fireTurretXAtGround_withOffset:128,128
highPriorityQueue: true
onlyOneUnitAtATime: true
whenBuilding_playAnimation: fireNuke
displayRemainingStockpile: true
addResources:isTran=1,700
alsoQueueAction:de
[action_launch2]
text:发射晶体*100,换取800$
iconImage:ROOT:/cyst.png
description_zh:发射(晶体*100)
buildSpeed:4.5s
isLocked:if self.resource.isTran == 1
isLockedMessage:另一运输任务正在执行中!
price:crystal=100,ammo=1
fireTurretXAtGround: lc
fireTurretXAtGround_withOffset:128,128
highPriorityQueue: true
onlyOneUnitAtATime: true
whenBuilding_playAnimation: fireNuke
displayRemainingStockpile: true
addResources:isTran=1,800
alsoQueueAction:de
[action_launch3]
text:发射硫化物*500,换取500$
iconImage:ROOT:/S.png
description_zh:发射(硫化物*500)
buildSpeed:4.5s
isLocked:if self.resource.isTran == 1
isLockedMessage:另一运输任务正在执行中!
price:S=100,ammo=1
fireTurretXAtGround: lc
fireTurretXAtGround_withOffset:128,128
highPriorityQueue: true
onlyOneUnitAtATime: true
whenBuilding_playAnimation: fireNuke
displayRemainingStockpile: true
addResources:isTran=1,500
alsoQueueAction:de



[hiddenAction_de]
buildSpeed:6s
addResources:isTran=-1
[resource_isTran]
displayName:isTran
[turret_lc]
canShoot: false
x: 0
y: 0
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: rc
size: 1
turnSpeed: 40
#shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
#limitingMinRange:1
[projectile_rc]
directDamage:0
deflectionPower:-1
image:droper-m.png
targetGround:true
drawSize:0.5
turnSpeed:0
life: 500
speed: 0.1
targetSpeed:8
targetSpeedAcceleration:0.05
ballistic: true
ballistic_height: 20000
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
[arm_1]
image_foot:black64.png
image_leg:hyw.png
x: 0
y: 0
targetHeight:0
lockMovement:true

[arm_2]
image_foot:cvL2.png
image_leg:hyw.png
x: 0
y: 0
targetHeight:0.1
lockMovement:true
[arm_3]
image_foot:cvL1.png
image_leg:hyw.png
x: 0
y: 0
targetHeight:0.1
lockMovement:true
[animation_lca]
onActionsQueuedUnitPlayAt :1

[action_bui]
addResources:ammo=1
price:红宝石=300,S=10
text:建造火箭
description:-制造运火箭\n-最多停放4架
displayType:building
buildSpeed:45s
isActive:if self.ammoIncludingQueued(lessThan=3)
aiUse: launchAmmo

[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life:120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

[animation_fireNuke]
blendIn: 2s
blendOut: 2.5s
arm2_0: {x:7, y:0}
arm3_0: {x:-7, y:0}

[placementRule_1]
searchTags:signal
searchTeam:own
searchDistance:80
minCount:1
blocksPlacement:true
cannotPlaceMessage:80像素(4格)内没有找到信号基站!