[core]
transportUnitsAddUnloadOption: false
name:slander
displayText:着陆台
displayDescription:-需要放置在基站的相邻格\n-消耗1kW\n-可应答基站呼叫的各种资源投放\n-本身不具备呼叫能力
class:CustomUnitMetadata
price:红宝石=1000,iron=500
maxHp:1000
mass:900
footprint:0,0,0,0
constructionFootprint:0,0,1,1
techLevel:1
buildingToFootprintOffsetY:20
buildingToFootprintOffsetX:20
#buildingSelectionOffset: -8
buildSpeed:18s
availableInDemo:true
radius:45
tags:sta,callableLander
isBio:false
isBuilding:true
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Lboom
numBitsOnDeath: 20
borrowResourcesWhileAlive:电力=1
#disableAllUnitCollisions: true
[graphics]
showQueueBar:false
icon_zoomed_out:ROOT:icon/site.png
scaleImagesTo:40
image:recivePad.png
image_wreak:slauncherw.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
drawLayer: bottom
total_frames:1
[attack]
canAttack:false
maxAttackRange:0
[movement]
movementType:HOVER
moveSpeed:0
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.05
maxEachBase:1
maxGlobal:5
[hiddenAction_lds]
autoTriggerOnEvent:newMessage
alsoQueueAction:ldsp
[hiddenAction_ldsp]
buildSpeed:3.7s
playSoundAtUnit:ROOT:/SFX/thrustFadeI.ogg:3
[hiddenAction_ld]
autoTriggerOnEvent:newMessage(withTag="红宝石")
temporarilyRemoveTags:callableLander
spawnUnits:mineDrop
alsoQueueAction:d
[hiddenAction_ld2]
autoTriggerOnEvent:newMessage(withTag="S")
temporarilyRemoveTags:callableLander
spawnUnits:SDrop
alsoQueueAction:d
[hiddenAction_ld3]
autoTriggerOnEvent:newMessage(withTag="iron")
temporarilyRemoveTags:callableLander
spawnUnits:ironDrop
alsoQueueAction:d
[hiddenAction_ld4]
autoTriggerOnEvent:newMessage(withTag="crystal")
temporarilyRemoveTags:callableLander
spawnUnits:cystDrop
alsoQueueAction:d
[hiddenAction_ld5]
autoTriggerOnEvent:newMessage(withTag="heac")
temporarilyRemoveTags:callableLander
spawnUnits:heacDrop
alsoQueueAction:d
[hiddenAction_ld6]
autoTriggerOnEvent:newMessage(withTag="rad")
temporarilyRemoveTags:callableLander
spawnUnits:radDrop
alsoQueueAction:d
[action_d]
isVisible:true
text:运输进度
isLockedMessage: 
isLocked:true
buildSpeed:16.6s
canPlayerCancel:false
temporarilyAddTags:callableLander

[placementRule_1]
searchTags:signal
searchTeam:own
searchDistance:80
minCount:1
blocksPlacement:true
cannotPlaceMessage:80像素(4格)内没有找到信号基站!