[core]
transportUnitsAddUnloadOption: false
name:slander
displayText:着陆台
displayDescription:-需要放置在基站的相邻格\n-消耗2kW\n-可呼叫各种资源投放
class:CustomUnitMetadata
price:红宝石=1000
maxHp:1000
mass:900
footprint:0,0,1,1
constructionFootprint:0,0,1,1
techLevel:1
buildingToFootprintOffsetY:20
buildingToFootprintOffsetX:20
#buildingSelectionOffset: -8
buildSpeed:18s
availableInDemo:true
radius:45
tags:sta
isBio:false
isBuilding:true
explodeTypeOnDeath:building
unitsSpawnedOnDeath:Lboom
numBitsOnDeath: 20
borrowResourcesWhileAlive:电力=2
[graphics]
icon_zoomed_out:ROOT:icon/site.png
scaleImagesTo:40
image:recivePad.png
image_wreak:slauncherw.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

total_frames:1
[attack]
canAttack:false
maxAttackRange:0
[movement]
movementType:HOVER
moveSpeed:0
[resource_isTran]
displayName:cooldown
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.05
maxEachBase:1
maxGlobal:5
[action_holder]
isVisible:false
text:占位符
buildSpeed:0
price:S=100
[action_doc]
isVisible:false
text:占位符2
pos:3
[action_launch1]
text:请求红宝石*1000
iconImage:ROOT:/mine.png
description_zh:需要$750
buildSpeed:10s
isLocked:if self.resource.isTran == 1
isLockedMessage:正在冷却!
price:750

spawnUnits:builder
highPriorityQueue: true
displayRemainingStockpile: true
addResources:isTran=1
alsoQueueAction:de
[hiddenAction_de]
buildSpeed:4s
addResources:isTran=-1
[placementRule_1]
searchTags:signal
searchTeam:own
searchDistance:80
minCount:1
blocksPlacement:true
cannotPlaceMessage:80像素(4格)内没有找到信号基站!