[core]
name:stacore1
displayText:1级空间站核心
displayDescription:-基地\n-无法自卫 \n-苍蝇老巢\+20ele
class:CustomUnitMetadata
price:红宝石=30000
borrowResourcesWhileAlive:电力=-20
maxHp:20000
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
techLevel:1
buildSpeed:120s
nanoFactorySpeed:2

availableInDemo:true
radius:30
displayRadius:30
isBio:false
isBuilding:true
explodeTypeOnDeath:building
canBuild_1_name:buildDrone
canBuild_3_name:engineer

generation_resources:红宝石=4
generation_delay:40
exit_x:0
exit_y:0
exit_moveAwayAmount:20

isPickableStartingUnit:true
startFallingWhenStartingUnit:true

maxTransportingUnits:2
transportUnitsRequireMovementType:HOVER,LAND
transportUnitsBlockOtherTransports:false
transportUnitsRequireTag:boat
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,bs
[attack]
canAttack:false
[graphics]
icon_zoomed_out:ROOT:icon/bs.png
total_frames:2
image:staBay1.png
image_wreak:staBayd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start:0
animation_idle_end:1
animation_idle_speed:20
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.01
maxEachBase:5

[movement]
movementType:HOVER
[hiddenAction_out]
autoTrigger:true
requireConditional:if self.transportingUnitwithTags(includes='boat')
forceUnloadTransportNow:true
[action_updt2]
buildSpeed:15s
text:升级-T2
price:红宝石=4000,data=256
displayType:upgrade
unitShownInUI:stacore2
allowMultipleInQueue:false
convertTo:stacore2
ai_isHighPriority:true
[action_trans]
iconImage:trans.png
text:转换
description_zh:消耗1k$转换为1.5k红宝石
buildSpeed:1s
price:1000
ai_isHighPriority:true
addResources:红宝石=1500
[action_aired]
autoTrigger:true
requireConditional:if (self.customTimer >= 10) and self.isControlledByAI()
isVisible:false
addResources:红宝石=200,data=50
ai_isHighPriority:true
buildSpeed:0.1s
resetCustomTimer:true
[action_doc]
text:帮助
iconImage:doc.png
#description_zh:开局请使用"转换"来获得初始资源,本模组使用"红宝石"作为资源\n-苍蝇是最基础的攻击单位,通过攻击陨石可以爆红宝石(实体)\n-靠近红宝石(实体)会自动吸收转换为Hp\n-所有飞船的hp一开始均为1,当hp满时即可升级\n-同级飞船的Hp上限一样(这意味着大多时候护盾在充当Hp)\n-炮台和一些建筑会消耗电力,电力<=0炮台会不攻击\n-基地和太阳能板生产电力\n-祝您游玩愉快!
buildSpeed:0.2s
price:0
addResources:红宝石=25
[hiddenAction_zm]
autoTriggerOnEvent:created
playSoundAtUnit:ROOT:/land.ogg


[action_transAI]
isVisible:false
text:转换(ai)
autoTrigger:if (self.isControlledByAI() and (self.resource.credits > 1000))
addResources:-1000,红宝石=1500
[action_transAI2]
isVisible:false
text:转换(ai)2
autoTrigger:if (self.isControlledByAI() and (self.resource.credits > 10000))
addResources:-10000,红宝石=15000