[core]
name:stacore1
displayText:核心仓
#注意是仓不是舱
displayDescription:-基地\n-能够生产简单的开荒单位\n-速度为普通工厂的1.5倍\n-带有20kJ的缓存容量\n-升级以解锁更高级的科技
class:CustomUnitMetadata
price:红宝石=30000
borrowResourcesWhileAlive:cap=-20
maxHp:20000
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
techLevel:1
buildSpeed:120s
nanoFactorySpeed:2

availableInDemo:true
radius:30
displayRadius:30
isBio:false
isBuilding:true
explodeTypeOnDeath:building
canBuild_1_name:buildDrone
canBuild_3_name:engineer

generation_resources:红宝石=30
generation_delay:40
exit_x:0
exit_y:40
exit_moveAwayAmount:20

isPickableStartingUnit:true
startFallingWhenStartingUnit:true

maxTransportingUnits:2
transportUnitsRequireMovementType:HOVER,LAND
transportUnitsBlockOtherTransports:false
transportUnitsRequireTag:boat
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,bs
[canBuild_sr]
name:setRally
pos:-1
[attack]
canAttack:false
[graphics]
icon_zoomed_out:ROOT:icon/bs.png
total_frames:2
image:staBay1.png
image_wreak:staBayd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start:0
animation_idle_end:1
animation_idle_speed:20
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.01
maxEachBase:2
recommendedInEachBaseNum:1
[movement]
movementType:HOVER

[action_updt2]
buildSpeed:32.3s
text:升级-T2
price:红宝石=4000,data=256
streamingCost:电力=1024
displayType:upgrade
unitShownInUI:stacore2
allowMultipleInQueue:false
convertTo:stacore2
ai_isHighPriority:true
[action_trans]
iconImage:trans.png
text:转换
description_zh:消耗1k$转换为1.5k红宝石\n-只能在开局2分钟内使用
isLocked:if self.customTimer>=120
buildSpeed:0s
price:1000
ai_isHighPriority:true
addResources:红宝石=1500

[action_doc]
text:帮助
iconImage:doc.png
#description_zh:开局请使用"转换"来获得初始资源,本模组使用"红宝石"作为资源\n-苍蝇是最基础的攻击单位,通过攻击陨石可以爆红宝石(实体)\n-靠近红宝石(实体)会自动吸收转换为Hp\n-所有飞船的hp一开始均为1,当hp满时即可升级\n-同级飞船的Hp上限一样(这意味着大多时候护盾在充当Hp)\n-炮台和一些建筑会消耗电力,电力<=0炮台会不攻击\n-基地和太阳能板生产电力\n-祝您游玩愉快!
#这里的内容被分离到了另一个mod
buildSpeed:0.2s
price:0
addResources:红宝石=25
[hiddenAction_zm]
autoTriggerOnEvent:created
playSoundAtUnit:ROOT:/land.ogg
#还是v7的着陆音效 懒得换了

[hiddenAction_transAI]
autoTrigger:if (self.isControlledByAI() and self.customTimer < 120)
addResourcesWithLogic:credits=self.resource.红宝石,红宝石=-1*self.resource.红宝石
#究极大粪 只是懒得写set:)