[core]
transportUnitsAddUnloadOption: false

name:tranLauncher
displayText:深空运输站
displayDescription:-emmm\n-消耗45kW
class:CustomUnitMetadata
price:红宝石=20000,data=12200,heac=100
maxHp:150000
mass:900
footprint:-6,-8,6,5
constructionFootprint:-6,-8,6,5
techLevel:1
buildingToFootprintOffsetY:-20
buildingSelectionOffset: -8
buildSpeed:0.000003
availableInDemo:true
radius:140
tags:sta
isBio:false
isBuilding:true
explodeTypeOnDeath:building
exit_x:0
exit_y:20
exit_moveAwayAmount:25
unitsSpawnedOnDeath:Lboom
numBitsOnDeath: 20
borrowResourcesWhileAlive:电力=45
maxTransportingUnits: 100
transportUnitsRequireMovementType: AIR, LAND,HOVER
transportUnitsUnloadDelayBetweenEachUnit: 5
transportUnitsKillOnDeath:false
transportUnitsBlockOtherTransports: false
[graphics]
icon_zoomed_out:ROOT:icon/site.png
scaleImagesTo:240
image:tranLauncher.png
image_wreak:stafcd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

total_frames:1
[attack]
canAttack:false
maxAttackRange:20000
[movement]
movementType:HOVER
moveSpeed:0

maxTurnSpeed:0
targetHeight:1
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.05
maxEachBase:1
maxGlobal:5
[action_holder]
isVisible:false
text:占位符
buildSpeed:0
price:S=100
[action_doc]
isVisible:false
text:占位符2
pos:3
[action_launch]
text:发射
iconImage:rocket.png
description_zh:将建筑内单位发射到指定地点
buildSpeed:8.3s
isLocked:if self.resource.isTran == 1
isLockedMessage:另一运输任务正在执行中!
price:S=1000,ammo=1
fireTurretXAtGround: lc
fireTurretXAtGround_showGuideDecals:targetGuide
#displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
whenBuilding_playAnimation: fireNuke
displayRemainingStockpile: true
#resetCustomTimer:true
addResources:isTran=1
alsoQueueAction:unload
[resource_isTran]
displayName:isTran

[hiddenAction_unload]
buildSpeed:17s
#autoTrigger:if (self.customTimer() > 12  and self.resource.isTran > 0)
fireTurretXAtGround:uld
addResources:isTran=-1
highPriorityQueue: true
[decal_targetGuide]
alwaysStartDirAtZero: true
layer: inactive
image:sel.png
imageScale: 1
alpha: 0.4
teamColors:true

[projectile_odp]
directDamage:0
life:16000
speed:250
image:hyw.png
deflectionPower:-1
targetGround:true
#spawnUnit:droper(alwayStartDirAtZero=true)
#instant:true
spawnProjectilesOnCreate:rc
spawnUnit:droper
[projectile_unitS]
turnSpeed:10
unloadUpToXUnitsFromSource:100
directDamage:0
life:60
instant:true
deflectionPower:-1
[turret_lc]
canShoot: false
x: -67
y: -45
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: odp
size: 1
turnSpeed: 40
#shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:1000
[turret_uld]
canShoot: false
x: -67
y: -45
idleDir:0
invisible: true
projectile: unitS
turnSpeed: 40
[projectile_rc]
directDamage:0
deflectionPower:-1
image:droper-m.png
targetGround:true
drawSize:0.7
turnSpeed:0
life: 500
speed: 0.1
targetSpeed:8
targetSpeedAcceleration:0.01
ballistic: true
ballistic_height: 20000
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
[arm_1]
image_foot:black32.png
image_leg:hyw.png
x: -67
y: -45
targetHeight:0
lockMovement:true

[arm_2]
image_foot:cv2.png
image_leg:hyw.png
x: -67
y: -45
targetHeight:0.1
lockMovement:true
[arm_3]
image_foot:cv1.png
image_leg:hyw.png
x: -67
y: -45
targetHeight:0.1
lockMovement:true
[animation_lca]
onActionsQueuedUnitPlayAt :1

[action_bui]
addResources:ammo=1
price:红宝石=12000,heac=100
text:建造火箭
description:-制造深空投放火箭\n-最多停放3架
displayType:building
buildSpeed:45s
isActive:if self.ammoIncludingQueued(lessThan=3)
aiUse: launchAmmo

[action_funload]
text:卸下单位
description:-卸下候车的单位
startUnloadingTransport:true
buildSpeed:0s
isLocked:if self.resource.isTran == 1
isLockedMessage:单位已在途!

[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life:120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

[animation_fireNuke]
blendIn: 2s
blendOut: 2.5s
arm2_0: {x:15, y:0}
arm3_0: {x:-15, y:0}