[core]

name:tranLauncher
displayText:深空运输站
displayDescription:-emmm\n-消耗45kW
class:CustomUnitMetadata
price:红宝石=20000,data=12200,heac=100
maxHp:150000
mass:900
footprint:-6,-8,6,5
constructionFootprint:-6,-8,6,5
techLevel:1
buildingToFootprintOffsetY:-20
buildingSelectionOffset: -8
buildSpeed:0.000003
availableInDemo:true
radius:140
tags:sta
isBio:false
isBuilding:true
explodeTypeOnDeath:building
exit_x:0
exit_y:20
exit_moveAwayAmount:25
unitsSpawnedOnDeath:Lboom
numBitsOnDeath: 20
borrowResourcesWhileAlive:电力=45
maxTransportingUnits: 10
transportUnitsRequireMovementType: AIR, LAND,HOVER
transportUnitsUnloadDelayBetweenEachUnit: 5
transportUnitsKillOnDeath:false
transportUnitsBlockOtherTransports: false
[graphics]
icon_zoomed_out:ROOT:icon/site.png
scaleImagesTo:240
image:tranLauncher.png
image_wreak:stafcd.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

total_frames:1
[attack]
canAttack:false
maxAttackRange:20000
[movement]
movementType:HOVER
moveSpeed:0
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
maxTurnSpeed:0
turnAcceleration:0.1
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.05
maxEachBase:1
maxGlobal:5
[action_holder]
isVisible:false
text:占位符
buildSpeed:0
price:S=100
[action_doc]
isVisible:false
text:占位符2
pos:3
[action_launch]
text:发射
iconImage:rocket.png
description_zh:将建筑内单位发射到指定地点
buildSpeed:8.3s
price:S=1000
fireTurretXAtGround: lc
fireTurretXAtGround_showGuideDecals:targetGuide
#displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true

[decal_targetGuide]
alwaysStartDirAtZero: true
layer: inactive
image:sel.png

imageScale: 1
alpha: 0.4
teamColors:true

[projectile_odp]
directDamage:0
life:60
deflectionPower:-1
#spawnUnit:droper(alwayStartDirAtZero=true)
instant:true

[turret_lc]

canShoot: false
x: -67
y: -45
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: rc
size: 1
turnSpeed: 40
#shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:260

[projectile_rc]
pushVelocity:12
#pushForce:15000
image:rocket.png
tags:nuke
directDamage:123
life: 99999
speed: 0.1
targetSpeed:8
targetSpeedAcceleration:0.01
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage:10000
#hullDamageMultiplier:0 for EMP version
#hullDamageMultiplier: 0
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
drawSize:0.55
areaRadius:1500
areaExpandTime:120
deflectionPower:-1
shouldRevealFog:true
nukeWeapon:true
lightColor: #EEEE00
lightSize: 1
friendlyFire: true
trailEffect: true
#CUSTOM:projectileTrail
trailEffectRate:4
spawnUnit:NUKE2
[decal_cv1]
image:cv1.png
imageScale:1.7
xOffsetAbsolute: -67
yOffsetAbsolute: 45
layer:beforeBody
[decal_cv2]
image:cv2.png
imageScale:1.7
xOffsetAbsolute: -67
yOffsetAbsolute: 45
layer:beforeBody
[decal_base]
image:black64.png
imageScale:1.3
xOffsetAbsolute: -67
yOffsetAbsolute: 45
layer:beforeBody
order:-2
[animation_lca]
onActionsQueuedUnitPlayAt :1
