[core]
copyFrom:"""ROOT:RW_Engine/View/View.md,ROOT:RW_Engine/View/CommonCallBack.md"""
name:LayoutInterpreter
tags:LayoutInterpreter
isUnselectable:true
showInEditor:false


#----------Cache----------#
#存储所有以InitializeData为标准的Id下标    下标为I
@memory indexInitializeDataIdCaches:number[]
#存储所有以InitializeData为标准的Attribute下标 下标为A
@memory indexInitializeDataAttributeCaches:number[]
#存储所有以InitializeData为标准的,下标 下标为,
@memory indexCommaCaches:number[]
#存储所有以InitializeData为标准的///下标 下标为///的第一个/
@memory indexInitializeDataCaches:number[]
#----------Cache----------#

#布局数据
@memory InitializeData:string
#在标记Id,Attribute等时使用的临时str,为一个///Data///中的内容



@memory oneInitializeDataTmp:string
#在ViewInit中所使用的oneInitializeDataTmp为独立字符串，
#而所有Cache却以布局数据为基准
#故indexInitializeDataTmp作为该oneInitializeDataTmp在布局数据
#中真实下标
@memory indexInitializeDataTmp:number


#----------StringToInt----------#
@memory LayoutStringToIntPOW:number
@memory LayoutStringToIntTmp:string
@memory LayoutStringToIntResult:number
@memory LayoutStringToIntArrayTmp:string
#----------StringToInt----------#


#存储由该LayoutInterpreter管理的所有控件
@memory ViewArray:unit[]

#布局文件单个控件的布局属性
@memory ViewInitType:string
#用于遍历布局文件每个控件的布局属性
@memory ViewInitStartingLoopNum:number
#遍历下标临时存储
@memory oneInitializeDataTmpIndex:number
#用于定位每个逗号
@memory indexCommaTmp:number
@memory ViewIdTmp:number

@memory ViewInitNextLocked:boolean



[hiddenAction_LayoutInterpreterCreated]
autoTriggerOnEvent:created
resetCustomTimer:true
sendMessageTo:self.customTarget1
sendMessageWithTags:LayoutInterpreterInitWaiting



[hiddenAction_receivedView]
autoTriggerOnEvent:newMessage(withTag="addToLayoutInterpreter")
setUnitMemory:ViewArray[eventData("ViewId",type="number")]=eventSource


[hiddenAction_LayoutInterpreterInit]
#接收布局信息
autoTriggerOnEvent:newMessage(withTag="LayoutInterpreterInit")
setUnitMemory:InitializeData=eventData("InitializeData",type="string"),indexInitializeDataIdCaches=null,indexInitializeDataAttributeCaches=null,indexCommaCaches=null,indexInitializeDataCaches=null,ViewInitStartingLoopNum=0,oneInitializeDataTmpIndex=0,indexCommaTmp=0,commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventData("commonCallBackTarget",type="unit")

#标记所有///  记录的下标需注意
alsoTriggerAction:updatingInitializeDataIndexCaches
#遍历所有字符
alsoTriggerActionRepeat:length(memory.InitializeData)
#准备标记各个id,Attribute及","
alsoQueueAction:analyzeInitializeDataLoop



[hiddenAction_updatingInitializeDataIndexCaches]
highPriorityQueue:true
#在获取一个///test///内容时 第一个index需要+3
requireConditional:if substring(memory.InitializeData,index,index+3) == "///"
setUnitMemory:indexInitializeDataCaches[memory.indexInitializeDataCaches.size]  = index


[hiddenAction_analyzeInitializeDataLoop]
buildSpeed:0.0s
alsoTriggerAction:analyzeInitializeData,ViewStart-Check
#遍及次数为///的大小
alsoTriggerActionRepeat:memory.indexInitializeDataCaches.size

[hiddenAction_ViewStart-Check]
requireConditional:if index+1 == memory.indexInitializeDataCaches.size
alsoTriggerAction:ViewStart


[hiddenAction_analyzeInitializeData]


#开始阴间
#oneInitializeDataTmp为一个///Data///中的内容
#在获取一个///test///内容时 第一个index需要+3
setUnitMemory:oneInitializeDataTmp=substring(memory.InitializeData,memory.indexInitializeDataCaches[index]+3,memory.indexInitializeDataCaches[(index+1)]),indexInitializeDataTmp=memory.indexInitializeDataCaches[index]+3
#因为所有的Cache都是以InitializeData为标准，而这里
#遍历的却是oneInitializeDataTmp  应加上当前内容在
#InitializeData标准的下标
alsoTriggerAction:analyingInitializeData



[hiddenAction_analyingInitializeData]
requireConditional:if memory.oneInitializeDataTmp != "|" and length(memory.oneInitializeDataTmp) != 0
alsoTriggerAction:analyzingInitializeDataId,analyzingInitializeDataAttribute,analyzingInitializeDataComma
alsoTriggerActionRepeat:length(memory.oneInitializeDataTmp)

#showMessageToAllPlayers:oneInitializeDataTmp为%{memory.oneInitializeDataTmp}

#存储所有以InitializeData为标准的Id下标    下标为I
[hiddenAction_analyzingInitializeDataId]
requireConditional:if substring(memory.oneInitializeDataTmp,index,index+3)=="Id:"
setUnitMemory:indexInitializeDataIdCaches[memory.indexInitializeDataIdCaches.size]=index+memory.indexInitializeDataTmp

#存储所有以InitializeData为标准的Attribute下标 下标为A
[hiddenAction_analyzingInitializeDataAttribute]
requireConditional:if substring(memory.oneInitializeDataTmp,index,index+10)=="Attribute:"
setUnitMemory:indexInitializeDataAttributeCaches[memory.indexInitializeDataAttributeCaches.size]=index+memory.indexInitializeDataTmp

#存储所有以InitializeData为标准的,下标 下标为,
[hiddenAction_analyzingInitializeDataComma]
requireConditional:if substring(memory.oneInitializeDataTmp,index,index+1)==("""','""")
setUnitMemory:indexCommaCaches[memory.indexCommaCaches.size]=index+memory.indexInitializeDataTmp




[hiddenAction_ViewStart]
requireConditional:if memory.ViewInitStartingLoopNum <= memory.indexInitializeDataCaches.size

alsoTriggerAction:ViewInitStarting

[hiddenAction_ViewInitStarting]
setUnitMemory:oneInitializeDataTmp=substring(memory.InitializeData,memory.indexInitializeDataCaches[memory.ViewInitStartingLoopNum]+3,memory.indexInitializeDataCaches[(memory.ViewInitStartingLoopNum+1)]),indexInitializeDataTmp=memory.indexInitializeDataCaches[memory.ViewInitStartingLoopNum]+3,oneInitializeDataTmpIndex=0


alsoTriggerAction:ViewInit-layout-Check

[hiddenAction_ViewInit-layout-Check]
buildSpeed:0.0s
requireConditional:if memory.oneInitializeDataTmpIndex < length(memory.oneInitializeDataTmp)
setUnitMemory:ViewInitType=select(substring(memory.oneInitializeDataTmp,memory.oneInitializeDataTmpIndex,memory.oneInitializeDataTmpIndex+3)=="Id:","Id",select(substring(memory.oneInitializeDataTmp,memory.oneInitializeDataTmpIndex,memory.oneInitializeDataTmpIndex+17)=="layout_marginTop=","marginTop",select(substring(memory.oneInitializeDataTmp,memory.oneInitializeDataTmpIndex,memory.oneInitializeDataTmpIndex+18)=="layout_marginLeft=","marginLeft","NULL")))
#showMessageToAllPlayers:ViewInitType为%{memory.ViewInitType}
alsoTriggerAction:ViewInit-layout-Set,ViewInit-layout-Check-Loop


[hiddenAction_ViewInit-layout-Check-Next]
requireConditional:if memory.ViewInitNextLocked==false and memory.oneInitializeDataTmpIndex == length(memory.oneInitializeDataTmp)
setUnitMemory:ViewInitNextLocked=true
#showMessageToAllPlayers:Next%{memory.oneInitializeDataTmpIndex}
alsoTriggerAction:ViewInit-layout-Check-Nexting

[hiddenAction_ViewInit-layout-Check-Nexting]
setUnitMemory:ViewInitNextLocked=false,ViewInitStartingLoopNum=memory.ViewInitStartingLoopNum+2
removeAllQueuedItemsWithoutRefund:true
alsoTriggerAction:ViewStart

#showMessageToAllPlayers:Nexting


[hiddenAction_ViewInit-layout-Check-Loop]
requireConditional:if memory.ViewInitType == "NULL" and memory.oneInitializeDataTmpIndex < length(memory.oneInitializeDataTmp)
buildSpeed:0.0s
setUnitMemory:oneInitializeDataTmpIndex=memory.oneInitializeDataTmpIndex+1
alsoTriggerAction:ViewInit-layout-Check-Next,LayoutInterpreterInitSucceed
alsoQueueAction:ViewInit-layout-Check
#[hiddenAction_ViewInit-layout-Set]
#requireConditional:
#alsoTriggerAction:ViewInit-layout-Set

[hiddenAction_ViewInit-layout-Set]
requireConditional:if memory.ViewInitType != "NULL" and (memory.ViewInitType == "Id" or memory.ViewInitType == "marginLeft" or memory.ViewInitType == "marginTop") and memory.oneInitializeDataTmpIndex < length(memory.oneInitializeDataTmp)
removeAllQueuedItemsWithoutRefund:true

setUnitMemory:LayoutStringToIntResult=0,LayoutStringToIntTmp=substring(memory.oneInitializeDataTmp,memory.oneInitializeDataTmpIndex+select(memory.ViewInitType == "Id",3,select(memory.ViewInitType == "marginTop",17,select(memory.ViewInitType == "marginLeft",18,-1))),memory.indexCommaCaches[memory.indexCommaTmp]-memory.indexInitializeDataTmp)



#showMessageToAllPlayers:oneInitializeDataTmpIndex为%{memory.oneInitializeDataTmpIndex}Set开始index=%{memory.oneInitializeDataTmpIndex+select(memory.ViewInitType == "Id",3,select(memory.ViewInitType == "marginTop",17,select(memory.ViewInitType == "marginLeft",18,-1)))}结束为%{memory.indexCommaCaches[memory.indexCommaTmp]-memory.indexInitializeDataTmp}LayoutStringToIntTmp为%{memory.LayoutStringToIntTmp}
alsoTriggerAction:LayoutStringToInt


[hiddenAction_LayoutStringToInt]
setUnitMemory:LayoutStringToIntPOW=1
alsoTriggerAction:LayoutStringToIntPush
alsoTriggerActionRepeat:length(memory.LayoutStringToIntTmp)


[hiddenAction_LayoutStringToIntPush]
setUnitMemory:LayoutStringToIntArrayTmp=substring(memory.LayoutStringToIntTmp,length(memory.LayoutStringToIntTmp)-1-index,length(memory.LayoutStringToIntTmp)-index),LayoutStringToIntResult=memory.LayoutStringToIntResult+select(memory.LayoutStringToIntArrayTmp=="1",1,select(memory.LayoutStringToIntArrayTmp=="2",2,select(memory.LayoutStringToIntArrayTmp=="3",3,select(memory.LayoutStringToIntArrayTmp=="4",4,select(memory.LayoutStringToIntArrayTmp=="5",5,select(memory.LayoutStringToIntArrayTmp=="6",6,select(memory.LayoutStringToIntArrayTmp=="7",7,select(memory.LayoutStringToIntArrayTmp=="8",8,select(memory.LayoutStringToIntArrayTmp=="9",9,select(memory.LayoutStringToIntArrayTmp=="-",1,0))))))))))*memory.LayoutStringToIntPOW*select(memory.LayoutStringToIntArrayTmp=="-",-1,1),LayoutStringToIntPOW=memory.LayoutStringToIntPOW*10

alsoQueueAction:LayoutStringToIntCheck

alsoTriggerOrQueueActionConditional:if index+1==length(memory.LayoutStringToIntTmp)


[hiddenAction_LayoutStringToIntCheck]
buildSpeed:0.0s
requireConditional:if memory.oneInitializeDataTmpIndex < length(memory.oneInitializeDataTmp)
setUnitMemory:oneInitializeDataTmpIndex=memory.oneInitializeDataTmpIndex+select(memory.ViewInitType == "Id",3,select(memory.ViewInitType == "marginTop",17,select(memory.ViewInitType == "marginLeft",18,-1))),indexCommaTmp=memory.indexCommaTmp+1,ViewIdTmp=select(memory.ViewInitType == "Id",memory.LayoutStringToIntResult,memory.ViewIdTmp)

sendMessageTo:memory.ViewArray[memory.ViewIdTmp]
sendMessageWithTags:setLayout
sendMessageWithData:ViewInitType=memory.ViewInitType,value=memory.LayoutStringToIntResult
#showMessageToAllPlayers:发送给Id为%{memory.ViewIdTmp}的%{memory.ViewArray[memory.ViewIdTmp]}ViewInitType为%{memory.ViewInitType}value为%{memory.LayoutStringToIntResult}
alsoQueueAction:ViewInit-layout-Check
#alsoTriggerAction:LayoutInterpreterInitSucceed
[hiddenAction_LayoutInterpreterInitSucceed]
requireConditional:if memory.oneInitializeDataTmpIndex+1 == length(memory.oneInitializeDataTmp)
alsoTriggerAction:StartCommonCallBack
#showMessageToAllPlayers:LayoutInterpreterInitSucceed
[action_updateContentIndexCachesTest]
text:测试布局文件解析
buildSpeed:0.0s
setUnitMemory:InitializeData="///Id:1,Attribute:layout_marginTop=50,layout_marginLeft=30,///|///Id:2,Attribute:layout_marginTop=10,layout_marginLeft=60,///|///Id:3,Attribute:layout_marginTop=5000,layout_marginLeft=-3000,///"
alsoTriggerAction:updatingInitializeDataIndexCaches
alsoTriggerActionRepeat:length(memory.InitializeData)

alsoQueueAction:analyzeInitializeDataLoop


[action_ViewStartTest]
text:测试ViewStart
buildSpeed:0.0s
alsoTriggerAction:ViewStart
