[core]
copyFrom:ROOT:tmp/turret.template
name:pstr
displayText:自适应框架
displayDescription:-最基础的建筑,承担着干细胞的作用\n-能够分化为各类2*2建筑
class:CustomUnitMetadata
price:iron=600
maxHp:2000
borrowResourcesWhileAlive:电力=1
#好处:可以逃课升T2炮台 坏消息:升级时间是两倍
techLevel:1
buildSpeed:0.002

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:150
shootDelay:18
setMainTurretAs:1

[graphics]
turretImageScale:0.5
total_frames:1
icon_zoomed_out:ROOT:icon/tur.png
image:str.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40

shadowOffsetY:1
[ai]
buildPriority:0.1
maxEachBase:20
recommendedInEachBaseNum:8


[movement]
movementType:HOVER

[action_updt1]
buildSpeed:33.3s
text:升级-T2机炮
price:红宝石=1200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staTur2
allowMultipleInQueue:false
convertTo:staTur2
[action_updt2]
buildSpeed:20s
text:升级-双管炮
price:红宝石=1000
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staTur2
allowMultipleInQueue:false
convertTo:staTTur2
[action_updt3]
buildSpeed:46.7s
text:升级-T2激光炮
price:红宝石=1200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staLTur2
allowMultipleInQueue:false
convertTo:staLTur2
[action_updt4]
buildSpeed:47.6s
text:升级-T2火炮
price:红宝石=2200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staRTur2
allowMultipleInQueue:false
convertTo:staRTur2