[core]
name:nukePad
displayText:<核弹发射井>
displayDescription:建造并发射威力巨大的导弹\n-需要1TB数据
class: CustomUnitMetadata
isLockedIfGameModeNoNuke:true
price:heac=1500,data=1048576
maxHp:15000
mass:9000
footprint: -1,-1,1,1
constructionFootprint: -2,-2,2,2
techLevel: 1
buildSpeed:480s
availableInDemo: true
radius: 50
isBio: false
isBuilding: true
exit_x:0
exit_y:-1
[action_buildNuke]
#price:rad=100,tian=480
price:红宝石=10000,data=1024,heac=128
text:建造导弹
description:需要1GB源代码,用于运输和投放弹头
displayType: NONE
buildSpeed:24.4s
pos:0.2
isActive:if self.ammoIncludingQueued(lessThan=4)
addResources: ammo=1
iconImage: SHARED:icon_build.png
aiUse: launchAmmo
[decal_targetGuide]
alwaysStartDirAtZero: true
layer: inactive
image:sel.png
@define area_guide_size: 100
@define area_guide_radius: 50
@define lowDamageBorder: 30
imageScale: ${ projectile_nuke.areaRadius - lowDamageBorder }/${area_guide_radius}*0.7
alpha: 0.4
teamColors:true
[action_launchNuke1]
fireTurretXAtGround: siloTop
fireTurretXAtGround_showGuideDecals:targetGuide
price:ammo=1,rad=128
text:发射<核弹>(逐个)
description:炸炸炸!!!!!\n-装药为标准核武
displayType: action
buildSpeed: 3.5s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
[action_launchNuke1-q]
fireTurretXAtGround: siloTop
fireTurretXAtGround_showGuideDecals:targetGuide
price:ammo=1,rad=128
text:发射<核弹>(齐射)
description:炸!!!!!
displayType: action
buildSpeed: 3.5s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime:false
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
[action_launchNuke2]
fireTurretXAtGround: siloTop-push
fireTurretXAtGround_showGuideDecals:targetGuide
price:ammo=1,crystal=1280
text:发射<冲击弹>(逐个)
description:炸炸炸!!!!!\n-eeee
displayType: action
buildSpeed: 3.5s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
[action_launchNuke3]
fireTurretXAtGround: siloTop-super
fireTurretXAtGround_showGuideDecals:targetGuide
price:ammo=1,data=12800
text:发射<super弹>(逐个)
description:炸炸炸!!!!!\n-eeee
displayType: action
buildSpeed: 3.5s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
[action_launchNuke4]
fireTurretXAtGround: siloTop-dt
fireTurretXAtGround_showGuideDecals:targetGuide
price:ammo=1,rad=50,S=2500
text:发射<脏弹>(逐个)
description:炸炸炸!!!!!\n-eeee
displayType: action
buildSpeed: 3.5s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
[graphics]
total_frames: 5
image:nukeLan.png
image_wreak:NONE
scaleImagesTo:70
#scaleTurretImagesTo: 9
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start:0
animation_idle_end:4
icon_zoomed_out:ROOT:icon/nuke.png
[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange:20000
[movement]
movementType: NONE
[turret_siloTop]
canShoot: false
x: 0
y: -5
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: nuke
size: 1
turnSpeed: 40
shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:260
[turret_siloTop-push]
canShoot: false
x: 0
y: -5
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: nuke-push
size: 1
turnSpeed: 40
shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:260
[turret_siloTop-super]
canShoot: false
x: 0
y: -5
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #EECCCC
projectile: nuke++
size: 1
turnSpeed: 40
shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:260
[turret_siloTop-dt]
canShoot: false
x: 0
y: -5
idleDir:0
invisible: true
shoot_sound:nuke_launch
shoot_sound_vol:0.27
shoot_light: #3bff69
projectile:dt
size: 1
turnSpeed: 40
shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light,custom:nukeLaunch_smoke*6
limitingMinRange:260
[projectile_nuke]
pushVelocity:12
#pushForce:15000
image:nuke1.png
tags:nuke
directDamage:123
life: 99999
speed: 0.1
targetSpeed:8
targetSpeedAcceleration:0.01
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage:10000
#hullDamageMultiplier:0 for EMP version
#hullDamageMultiplier: 0
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
drawSize:0.55
areaRadius:1500
areaExpandTime:120
deflectionPower:-1
shouldRevealFog:true
nukeWeapon:true
lightColor: #EEEE00
lightSize: 1
friendlyFire: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
spawnUnit:NUKE2
[projectile_nuke++]
pushVelocity:30
#pushForce:15000
image:nuke1.png
tags:nuke
directDamage:123
life: 99999
speed: 0.1
targetSpeed:12
targetSpeedAcceleration:0.02
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage:16000
#hullDamageMultiplier:0 for EMP version
#hullDamageMultiplier: 0
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
drawSize:1
areaRadius:1500
areaExpandTime:120
deflectionPower:-1
shouldRevealFog:true
nukeWeapon:true
lightColor: #EEEE00
lightSize: 1
friendlyFire: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
spawnUnit:NUKE2*10,NUKE
[projectile_dt]
pushVelocity:-30
#pushForce:15000
image:nuke1.png
tags:nuke
directDamage:123
life: 99999
speed: 0.1
targetSpeed:10
targetSpeedAcceleration:0.01
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage:100
#hullDamageMultiplier:0 for EMP version
#hullDamageMultiplier: 0
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
drawSize:0.55
areaRadius:1500
areaExpandTime:120
deflectionPower:-1
shouldRevealFog:true
nukeWeapon:true
lightColor: #00ee77
lightSize: 10
friendlyFire: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
spawnUnit:NUKE2*2
[projectile_nuke-push]
pushVelocity:75
#pushForce:15000
image:nuke2.png
tags:nuke
directDamage:123
life:99999
speed: 0.1
targetSpeed:8
targetSpeedAcceleration:0.01
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage:500
#hullDamageMultiplier:0 for EMP version
#hullDamageMultiplier: 0
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
drawSize:0.55
areaRadius:1500
areaExpandTime:60
deflectionPower:-1
shouldRevealFog:true
nukeWeapon:true
lightColor: #4bee00
lightSize: 1
friendlyFire: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4
spawnUnit:NUKE
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life:120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_nukeLaunch_wave]
priority:high
stripIndex:shockwave
life: 50
scaleFrom: 0.5
scaleTo: 2.5
[effect_nukeLaunch_smoke]
priority:high
xOffsetAbsoluteRandom: 10
yOffsetAbsoluteRandom: 10
frameIndex: 0
stripIndex: smoke_black
spawnChance: 0.3
life: 90
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #EEEE00
fadeInTime:5
scaleFrom: 0.3
scaleTo: 0.8
alpha: 0.9
drawUnderUnits:false
liveAfterAttachedDies: false
hSpeed:0.4
xSpeedAbsoluteRandom:0.9
ySpeedAbsoluteRandom:0.9
dirOffsetRandom:180
atmospheric: true
[effect_nukeLaunch_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false
[ai]
buildPriority: 0.01
noneInBaseExtraPriority: 0.04
noneGlobalExtraPriority: 0.1
maxEachBase: 0
ai_upgradePriority: 0.2
aiTags: nukeLauncher, launcher