[core]
name:NUKE2
availableInDemo:false
maxHp:0
mass:0
price:0
radius:5
explodeOnDeath:false
effectOnDeath:CUSTOM:lt,CUSTOM:wv,CUSTOM:dt*25,CUSTOM:ff*70,CUSTOM:swv,CUSTOM:hlt,CUSTOM:ydt*40,CUSTOM:cwv,CUSTOM:scw,CUSTOM:lte,CUSTOM:scw2
soundOnDeath:boom.ogg
unitsSpawnedOnDeath:AP1*5(spawnChance=0.8, maxSpawnLimit=5,offsetRandomXY=1000),AP2*12(spawnChance=0.8, maxSpawnLimit=12,offsetRandomXY=1500),AP3*25(spawnChance=0.8, maxSpawnLimit=25,offsetRandomXY=2000)
[graphics]
image:wlt.png
[attack]
canAttack:false
[movement]
movementType:NONE
[effect_lt]
image:ROOT:effect/wspt.png
color:#FFFFFF
life:300
scaleFrom:5
hSpeed:1.8
scaleTo:3.5
fadeOut:true
fadeInTime:0
priority:critical
alpha:1
[effect_wv]
image:ROOT:effect/4.png
color:#FFFFFF
life:45
scaleFrom:1
scaleTo:50
priority:critical
alsoPlaySound:ROOT:effect/boom.ogg
alpha:1
[effect_dt]
image:ROOT:effect/ydot.png
color: #FFBF00
priority:high
attachedToUnit:false
life:190
physics:true
xSpeedRelativeRandom:80
ySpeedRelativeRandom:80
hSpeed:5
hSpeedRandom:1
scaleFrom:2
scaleTo:1
alpha:1
[effect_ff]
color: #ffff00
image:ROOT:effect/rspt.png
priority:high
attachedToUnit:false
life:360
#physics:true
scaleFrom:3
scaleTo:9
alpha:0.1
[effect_swv]
image:ROOT:effect/4.png
color: #f1f372
life:220
scaleFrom:1
scaleTo:40
priority:critical
alsoPlaySound:ROOT:effect/boom.ogg
alpha:0.6
[effect_hlt]
image:ROOT:effect/hlt.png
color: #fff1aa
life:100
scaleFrom:26
scaleTo:4
priority:critical
alpha:0.2
[effect_ydt]
image:ROOT:effect/ydot.png
color:#FFBFFF
priority:high
attachedToUnit:false
life:190
physics:true
xSpeedRelativeRandom:80
ySpeedRelativeRandom:80
hSpeed:3
hSpeedRandom:1
scaleFrom:2
scaleTo:1
alpha:1
[effect_cwv]
image:ROOT:effect/4.png
color: #ffe66b
life:12
scaleFrom:1
scaleTo:16
priority:critical
alsoPlaySound:ROOT:effect/boom.ogg
alpha:1
[effect_scw]
priority:critical
image:SHARED:shockwave_normal_128.png
life:60
attachedToUnit:false
scaleFrom:1.5
scaleTo:18
drawUnderUnits:false
fadeOut:true
fadeInTime:0
alpha:1
drawType: displacement
alwayStartDirAtZero:true
[effect_scw2]
priority:critical
image:SHARED:shockwave_normal_128.png
life:15
attachedToUnit:false
scaleFrom:1.5
scaleTo:40
drawUnderUnits:false
fadeOut:true
fadeInTime:0
alpha:1
drawType: displacement
alwayStartDirAtZero:true
[effect_lte]
image:ROOT:effect/wspt.png
color: #FFFFFF
life:60
scaleFrom:50
scaleTo:1
priority:critical
alpha:0.4