[core]
copyFrom:"""ROOT:RW_Engine/View/View.md"""
name:allFontsBase.ini
dont_load:true
showInEditor:false
isUnselectable:false
tags:font

@memory char:string
@memory fontsScale:number
@memory frame:number
@memory locked:boolean


autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true
updateUnitMemory:char=self.customTarget1.readUnitMemory("char",type="string"),fontsScale=self.customTarget1.readUnitMemory("fontsScale",type="number")
updateUnitMemoryRate:0




[graphics]
teamColoringMode:hueShift
teamColorsOnTurret:true

[hiddenAction_created]
autoTriggerOnEvent:created
resetCustomTimer:true
setBodyRotation:-90
switchToTeam:self.customTarget1.teamId
#[hiddenAction_setSoltId]
#autoTriggerOnEvent:tookDamage(withTag="setSoltId")
#requireConditional:if eventSource == self.customTarget1
#teleportTo:createMarker(x=eventSource.readUnitMemory("setSoltIdX",type="float"),y=self.customTarget1.y)
#switchToTeam:self.customTarget1.teamId

[hiddenAction_fontReload]
autoTriggerOnEvent:newMessage(withTag="fontReload")
requireConditional:if eventSource == self.customTarget1
deleteSelf:true


[hiddenAction_setCharColor]
autoTriggerOnEvent:newMessage(withTag="setCharColor")
switchToTeam:self.customTarget1.teamId

#[hiddenAction_refreshLocation]
#autoTriggerOnEvent:newMessage(withTag="refreshLocation")
#teleportTo:createMarker(x=self.customTarget1.x,y=self.customTarget1.y)
