[core]
copyFrom:"""ROOT:RW_Engine/View/View.md"""
name:ColliderNegative
tags:ColliderNegative
showInEditor:false
isUnselectable:false
isBuilding:false
#碰撞检测范围
@global DEFAULT_COLLICER_MARK_RANGE:8

@memory ColliderMarkRange:number

@memory ColliderArgument:number[]
@memory ColliderArgumentRange:number[]
@memory ColliderConstant:number[]
#启动状态
@memory ColliderStatus:boolean







@memory ColliderArgumentComputing:boolean

@memory ColliderWayPoint:unit

@memory ColliderNegativeMark:unit
@memory ColliderRealArgument:number
@memory ColliderComputingArgument:number
@memory ColliderComputingDependentVariable:number
@memory ColliderComputingLoop:number
@memory ColliderComputingArgumentX:number
@memory ColliderStep:number


@memory ColliderRotation:float









@memory ColliderNegativeMarksList:unit[]


autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true



[hiddenAction_ColliderNegativeWaitingInit]
autoTriggerOnEvent:created
sendMessageTo:self.customTarget1
sendMessageWithTags:ColliderNegativeWaitingInit
spawnUnits:ColliderWayPoint(offsetX=40,offsetY=40)
setUnitMemory:ColliderMarkRange=${DEFAULT_COLLICER_MARK_RANGE}
[hiddenAction_SetColliderWayPoint]
autoTriggerOnEvent:newMessage(withTag="ColliderWayPoint")
setUnitMemory:ColliderWayPoint=eventSource


[hiddenAction_ColliderArgumentComputing]
autoTrigger:if memory.ColliderStatus == true and memory.ColliderArgumentComputing==false
setUnitMemory:ColliderArgumentComputing=true

alsoTriggerAction:ColliderComputingArgumentX

[hiddenAction_ColliderComputingArgumentX]
buildSpeed:0.0s
setUnitMemory:ColliderComputingArgument=memory.ColliderArgument[memory.ColliderComputingLoop]
alsoTriggerAction:ColliderComputingArgumentPow

alsoTriggerActionRepeat:memory.ColliderArgument[(memory.ColliderComputingLoop+1)]
#0 1 2 3 4 5 6 7
#2 2 3 3
#-3x**3
[hiddenAction_ColliderComputingArgumentPow]
setUnitMemory:ColliderComputingArgument=memory.ColliderComputingArgument*memory.ColliderRealArgument
alsoTriggerAction:ColliderComputingArgumentCheck
alsoTriggerOrQueueActionConditional:if index+1 == memory.ColliderArgument[(memory.ColliderComputingLoop+1)]


[hiddenAction_ColliderComputingArgumentCheck]
setUnitMemory:ColliderComputingArgumentX=memory.ColliderComputingArgumentX+memory.ColliderComputingArgument,ColliderComputingArgument=0,ColliderComputingLoop=memory.ColliderComputingLoop+2



#showMessageToAllPlayers:%{ColliderComputingArgumentX}

alsoTriggerAction:ColliderComputingArgumentCheck-Loop,ColliderComputingArgumentCheck-Loop-End

[hiddenAction_ColliderComputingArgumentCheck-Loop]
buildSpeed:0.0s
requireConditional:if memory.ColliderComputingLoop < memory.ColliderArgument.size
alsoQueueAction:ColliderComputingArgumentX
[hiddenAction_ColliderComputingArgumentCheck-Loop-End]
buildSpeed:0.0s
requireConditional:if memory.ColliderComputingLoop == memory.ColliderArgument.size
#showMessageToAllPlayers:ddd
alsoTriggerAction:ColliderComputingConstant
alsoTriggerActionRepeat:memory.ColliderConstant.size

[hiddenAction_ColliderComputingConstant]
setUnitMemory:ColliderComputingArgumentX=memory.ColliderComputingArgumentX+memory.ColliderConstant[index]
alsoTriggerAction:ColliderNegativeMark
alsoTriggerOrQueueActionConditional:if index+1 == memory.ColliderConstant.size


[hiddenAction_ColliderNegativeMark]
setUnitMemory:ColliderComputingDependentVariable=memory.ColliderComputingArgumentX,ColliderNegativeMark=self.getOffsetRelative(x=memory.ColliderRealArgument,y=memory.ColliderComputingDependentVariable)
spawnUnits:ColliderNegativeMark(spawnSource=memory.ColliderNegativeMark,copyWaypointsFrom=memory.ColliderWayPoint)

alsoTriggerAction:ColliderDetectionRestart
alsoTriggerOrQueueActionWithTarget:self.customTarget1
[hiddenAction_ColliderDetectionRestart]
requireConditional:if memory.ColliderRealArgument != memory.ColliderArgumentRange[3]

setUnitMemory:ColliderArgumentComputing=false,ColliderArgumentComputing=false,ColliderRealArgument=select(memory.ColliderArgumentRange[2]==1,select(memory.ColliderRealArgument==memory.ColliderArgumentRange[3],memory.ColliderArgumentRange[1],select(memory.ColliderRealArgument+memory.ColliderStep > memory.ColliderArgumentRange[3],memory.ColliderArgumentRange[3],memory.ColliderRealArgument+memory.ColliderStep)),select(memory.ColliderRealArgument+memory.ColliderStep > memory.ColliderArgumentRange[3],memory.ColliderArgumentRange[1],memory.ColliderRealArgument+memory.ColliderStep)),ColliderComputingArgument=0,ColliderComputingDependentVariable=0,ColliderComputingLoop=0,ColliderComputingArgumentX=0



[hiddenAction_SetColliderNegative]
autoTriggerOnEvent:newMessage(withTag="ColliderNegativeInit")
setUnitMemory:ColliderArgument[memory.ColliderArgument.size]=eventData("ColliderArgumentConstant",type="number"),ColliderArgument[memory.ColliderArgument.size]=eventData("ColliderArgumentPow",type="number"),ColliderArgumentRange[memory.ColliderArgumentRange.size]=select(eventData("ColliderArgumentRangeOriginClosing",type="boolean")==true,1,2),ColliderArgumentRange[memory.ColliderArgumentRange.size]=eventData("ColliderArgumentRangeOrigin",type="number"),ColliderArgumentRange[memory.ColliderArgumentRange.size]=select(eventData("ColliderArgumentRangeBoundClosing",type="boolean")==true,1,2),ColliderArgumentRange[memory.ColliderArgumentRange.size]=eventData("ColliderArgumentRangeBound",type="number"),ColliderConstant[memory.ColliderConstant.size]=eventData("ColliderConstant",type="number"),ColliderStep=eventData("ColliderStep",type="number")


[hiddenAction_SetColliderNegativeStatus]
autoTriggerOnEvent:newMessage(withTag="SetColliderNegativeStatus")
setUnitMemory:ColliderStatus=eventData("ColliderStatus",type="boolean")

[hiddenAction_SetColliderRotation]
autoTriggerOnEvent:newMessage(withTag="SetColliderRotation")

setUnitMemory:ColliderRotation=eventData("rotation",type="float")

setBodyRotation:memory.ColliderRotation
#ColliderRealArgument=memory.ColliderArgumentRange[1]


[hiddenAction_ColliderNegativeMarkAdd]
autoTriggerOnEvent:newMessage(withTag="ColliderNegativeMarkAdd")
setUnitMemory:ColliderNegativeMarksList[memory.ColliderNegativeMarksList.size] = eventSource






