[core]
copyFrom:ROOT:/tmp/RBMK.template
name:RBMKcore
displayText:石墨轻水型核反应堆核心
displayDescription:核电,轻而易举啊!\n坏了坏了
class:CustomUnitMetadata
price:heac=200,iron=4500
maxHp:1500
techLevel:1
buildSpeed:100s
footprint: 0,0,1,1
constructionFootprint:0,0,1,1
buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
radius:20
buildingSelectionOffset: -8
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
experimental: true
explodeOnDeath:true
tags:sta,RBMK,Rcore
mass:1000
shieldDisplayOnlyDeflection:true
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:1
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
total_frames:1
icon_zoomed_out:ROOT:rad2.png
image:core-r.png
image_shadow:AUTO
image_wreak:wreak.png
shadowOffsetX:1
scaleImagesTo:40
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02

#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0

[placementRule_1]
searchTags:Rcore
searchTeam:own
searchDistance:450
maxCount:0
blocksPlacement:true
cannotPlaceMessage:450像素(22.5格)内不能有2个控制器!

[hiddenAction_zm]
autoTriggerOnEvent:created
playSoundAtUnit:ROOT:/land.ogg
showQuickWarLogToAllPlayers:核电,轻而易举啊!
[hiddenAction_zm2]
autoTriggerOnEvent:destroyed
playSoundAtUnit:ROOT:/land.ogg
showQuickWarLogToAllPlayers:坏了坏了
spawnUnits:NUKE