[core]
copyFrom:ROOT:/tmp/RBMK.template
name:RBMKfuelRod
displayText:燃料棒
displayDescription:核电,轻而易举啊!\n坏了坏了
class:CustomUnitMetadata
price:heac=40,iron=120
maxHp:8000
techLevel:1
buildSpeed:10s
tags:sta,RBMK
mass:1000

[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:120
shootDelay:10
[graphics]
total_frames:4
animation_idle_start:0
animation_idle_end:3
icon_zoomed_out:ROOT:rad2.png
image:rod.png
image_shadow:AUTO
image_wreak:wreak.png
shadowOffsetX:1
scaleImagesTo:40
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02

#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0
[placementRule_1]
searchTags:Rcore
searchTeam:own
searchDistance:300
minCount:1
blocksPlacement:true
cannotPlaceMessage:300像素(15格)内没有找到控制器!

[attachment_rod]
x:0
y:0
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:rodEmp