[core]
name:batteryBase
displayText:电池基座
displayDescription:-可以放置电池\n-储存15kJ
class:CustomUnitMetadata
price:红宝石=1024,iron=10
maxHp:1000
shieldDisplayOnlyDeflection:true
mass:1000
buildingToFootprintOffsetX:40
buildingToFootprintOffsetY:10
constructionFootprint:0,-1,3,1
footprint: 0,0,3,1
#borrowResourcesWhileAlive:cap=-15
techLevel:1
buildSpeed:12s
availableInDemo:true
radius:20
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,ele,bbs,ebt
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bbs,ebt
[attack]
canAttack:false
[graphics]
drawLayer:bottom
scaleImagesTo:80
image:basicBatteryBase.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.02
[movement]
movementType:HOVER
[attachment_1]
x:0
y:24
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:batteryS
#showAllActionsFrom:true
#[action_battery]
#text:test
#weaponSlots:1
#weaponSlot_1_name:1
#weaponSlot_1_pos:1
#luke在模块化蜘蛛里禁用掉的几条键 似乎不能用
[action_rec]
buildSpeed:16.6s
text:拆除
iconImage:rec.png
description:拔出电芯,返还部分成本
sendMessageTo:self.attachment
sendMessageWithTags:r
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == false
[action_basic]
buildSpeed:8.3s
text:基础电池
iconImage:bbicon.png
description:需要6000红宝石,储存80kJ
sendMessageTo:self.attachment
sendMessageWithTags:basic
price:红宝石=6000
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
[action_pbs]
buildSpeed:16.6s
text:铅酸电池
iconImage:sbicon.png
description:储存175kJ
sendMessageTo:self.attachment
sendMessageWithTags:pbs
price:红宝石=3000,S=750,iron=800
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_lith]
buildSpeed:24.4s
text:锂离子电池
iconImage:lbicon.png
description:储存220kJ
sendMessageTo:self.attachment
sendMessageWithTags:lith
price:红宝石=6000,S=500,iron=1800
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_nai]
buildSpeed:33.3s
text:钠铁电池
iconImage:nbicon.png
description:储存400kJ
sendMessageTo:self.attachment
sendMessageWithTags:nai
price:红宝石=12000,S=600,iron=4000
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_mix]
buildSpeed:42.2s
text:混芯电池
iconImage:mbicon.png
description:储存780kJ
sendMessageTo:self.attachment
sendMessageWithTags:mix
price:红宝石=23333,S=1230,crystal=50,iron=2500
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_nuc]
buildSpeed:83.3s
text:核子活化电池
iconImage:nbicon.png
description:储存1MJ
sendMessageTo:self.attachment
sendMessageWithTags:nuc
price:12000,红宝石=65536,rad=70,heac=500
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_cyst]
buildSpeed:45.6s
text:晶体电池
iconImage:cybicon.png
description:储存660kJ
sendMessageTo:self.attachment
sendMessageWithTags:cyst
price:10000,crystal=600,iron=1000,S=500
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_alloy]
buildSpeed:63.3s
text:合金电池
iconImage:abicon.png
description:储存800kJ
sendMessageTo:self.attachment
sendMessageWithTags:alloy
price:5000,iron=6000,crystal=300,heac=800
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_rtg]
buildSpeed:49.8s
text:大型放射性同位素热电机
iconImage:rtgicon.png
description:输出恒定功率65kW
sendMessageTo:self.attachment
sendMessageWithTags:rtg
price:20000,rad=240,iron=600,crystal=100,heac=500
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_qa]
buildSpeed:111.1s
text:量子电池
iconImage:qbicon.png
description:储存8MJ
sendMessageTo:self.attachment
sendMessageWithTags:qa
price:36000,rad=64,红宝石=67000,crystal=2400,heac=1250,ee=1
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_dk]
buildSpeed:128s
text:暗能电池
iconImage:dbicon.png
description:储存48MJ
sendMessageTo:self.attachment
sendMessageWithTags:dk
price:1655400,rad=110,crystal=12000,heac=4550,ee=128
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_ee]
buildSpeed:156s
text:电素电池
iconImage:ebicon.png
description:储存1GJ
sendMessageTo:self.attachment
sendMessageWithTags:ee
price:3240000,rad=820,crystal=3000,heac=12000,ee=65536
isVisible:if self.attachment.readUnitMemory(name="empty",type="bool") == true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!