[core]
showInEditor:false
name:batteryMix
displayText:混芯电池
displayDescription:储存680kJ
class:CustomUnitMetadata
price:红宝石=23333,S=1230,crystal=50,iron=2500
maxHp:800
shieldDisplayOnlyDeflection:true
mass:128
#borrowResourcesWhileAlive:cap=-15
borrowResourcesWhileAlive:cap=-680
techLevel:1
buildSpeed:12s
availableInDemo:true
radius:40
isBuilding:false
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,ele,ebt,bbs
ignoreInUnitCapCalculation: true
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bbs,ebt
@memory empty:bool
[attack]
canAttack:false
[graphics]
drawLayer:ground2
scaleImagesTo:80
image:mixBattery.png
image_shadow:batterySdw.png
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.02
[movement]
moveSpeed:0
maxTurnSpeed:0
targetHeight:2
movementType:NONE
[hiddenAction_rec]
autoTriggerOnEvent:newMessage(withTag="r")
addResources:${core.price}
setUnitMemory:empty=true
iconImage:rec.png
convertTo:batteryS