[core]
showInEditor:false
name:batteryS
displayText:电池框架
displayDescription:-空的框架\n-可以插入电池\n-储存0kJ
class:CustomUnitMetadata
price:iron=5
maxHp:800
shieldDisplayOnlyDeflection:true
mass:128
#borrowResourcesWhileAlive:cap=-15
techLevel:1
buildSpeed:12s
availableInDemo:true
radius:40
isBuilding:false
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,ele,ebt,bbs
ignoreInUnitCapCalculation: true
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bbs,ebt
@memory empty:bool
[attack]
canAttack:false
[graphics]
icon_build:sbIcon.png
drawLayer:ground2
scaleImagesTo:80
image:batteryS.png
image_shadow:batterySdw.png
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.02
[movement]
moveSpeed:0
maxTurnSpeed:0
targetHeight:2
movementType:NONE
[hiddenAction_updti]
autoTriggerOnEvent:newMessage
setUnitMemory:empty=false
[hiddenAction_updt0]
autoTriggerOnEvent:newMessage(withTag="basic")
convertTo:batteryBasic
[hiddenAction_updt1]
autoTriggerOnEvent:newMessage(withTag="pbs")
convertTo:batteryLead
[hiddenAction_updt2]
autoTriggerOnEvent:newMessage(withTag="lith")
convertTo:batteryLith
[hiddenAction_updt3]
autoTriggerOnEvent:newMessage(withTag="nai")
convertTo:batteryNai
[hiddenAction_updt4]
autoTriggerOnEvent:newMessage(withTag="mix")
convertTo:batteryMix
[hiddenAction_updt5]
autoTriggerOnEvent:newMessage(withTag="nuc")
convertTo:batteryNuc
[hiddenAction_updt6]
autoTriggerOnEvent:newMessage(withTag="cyst")
convertTo:batteryCyst
[hiddenAction_updt65]
autoTriggerOnEvent:newMessage(withTag="alloy")
convertTo:batteryAolly
[hiddenAction_updt7]
autoTriggerOnEvent:newMessage(withTag="rtg")
convertTo:bRTG
[hiddenAction_updt8]
autoTriggerOnEvent:newMessage(withTag="qa")
convertTo:batteryQua
[hiddenAction_updt9]
autoTriggerOnEvent:newMessage(withTag="dk")
convertTo:batteryDark
[hiddenAction_updt10]
autoTriggerOnEvent:newMessage(withTag="ee")
convertTo:batteryEe
[hiddenAction_init]
setUnitMemory:empty=true
autoTriggerOnEvent:created
setBodyRotation:-90