[core]
showInEditor:false
name:bRTG
displayText:大型放射性同位素热电机
displayDescription:输出恒定功率65kW
class:CustomUnitMetadata
price:20000,rad=240,iron=600,crystal=100,heac=500
maxHp:800
shieldDisplayOnlyDeflection:true
mass:128
#borrowResourcesWhileAlive:cap=-15
generation_resources:电力=65
generation_active:if self.resource.电力 < self.resource.cap
techLevel:1
buildSpeed:12s
availableInDemo:true
radius:40
isBuilding:false
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,ele,ebt,bbs
ignoreInUnitCapCalculation: true
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bbs,ebt
@memory empty:bool
[attack]
canAttack:false
[graphics]
drawLayer:ground2
scaleImagesTo:80
image:qdRTG.png
image_shadow:batterySdw.png
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.02
[movement]
moveSpeed:0
maxTurnSpeed:0
targetHeight:2
movementType:NONE
[hiddenAction_rec]
autoTriggerOnEvent:newMessage(withTag="r")
addResources:${core.price}
setUnitMemory:empty=true
iconImage:rec.png
convertTo:batteryS