[core]
name:capac2
displayText:双联电容
displayDescription:-易于制造的小容量电池\n-储存30kJ
class:CustomUnitMetadata
price:红宝石=2200,iron=150,S=120
maxHp:1800
shieldDisplayOnlyDeflection:true
mass:1000
#buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
constructionFootprint:-1,0,1,1
footprint: -1,0,1,1
borrowResourcesWhileAlive:cap=-30
techLevel:1
buildSpeed:26s
availableInDemo:true
radius:20
isBuilding:true
explodeTypeOnDeath:large
tags:sta,ele
numBitsOnDeath:5
[attack]
canAttack:false
[graphics]
scaleImagesTo:60
image_wreak:capw.png
image:dbCap.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.02
[movement]
movementType:HOVER
[hiddenAction_dead]
autoTriggerOnEvent:destroyed
setResourcesWithLogic:电力=min(self.resource.电力,self.resource.cap)
alsoTriggerAction:boom
[hiddenAction_boom]
requireConditional:if self.resource.电力 >= self.resource.cap*0.5
spawnUnits:Mboom*1