[core]
name:DFCcore
displayText:暗核聚变堆核心[WIP]
displayDescription:-?
class:CustomUnitMetadata
price:红宝石=16000,heac=750,data=32222,rad=450,ee=12
maxHp:12800
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-2,-2,2,2
constructionFootprint:-2,-2,2,2
generation_resources:电力=4000
generation_active:if self.resource.电力 < self.resource.cap
#if 电力+步长<=容量      视觉效果更好 不会有溢出 
#I dont enable this because I idk whether this expression will affect performance(放洋屁:P )
techLevel:1
buildSpeed:120s
availableInDemo:true
radius:30
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
unitsSpawnedOnDeath:NUKE2,NUKE,AP1
autoTriggerCooldownTime:0.1s

@memory power:float
@memory temp:number
@memory cache1:float
[resource_speed]
displayName:speed
[resource_fuel]
displayName:燃料
[resource_waste]
displayName:废料
[resource_fui]
displayName:冷流体
[resource_hfui]
displayName:热流体
[attack]
canAttack:false
[graphics]
image:DFCcv.png
image_shadow:AUTO
scaleImagesTo:100
shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true
turretImageScale:0.4
[turret_pan]
#x:0
#y:0
#canShoot:false
#height:0
#idleSpin:10
#image:DFCfui.png
[ai]
buildPriority:0.002
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02
maxEachBase:1
[movement]
movementType:HOVER
[decal_fuild]
layer:afterBody
imageScale:0.39
image:DFCfui.png
alpha:(self.resource.fui+self.resource.hfui)/65536
basePosition:self.getOffsetRelative(dirOffset=self.customTimer*self.resource.speed)
[decal_top]
imageScale:0.39
teamColors:true
image:DFCcv2.png
layer:onTop
[decal_DFCgl]
isVisible:if self.resource.fuel >1
imageScale:0.8+memory.power/self.resource.fuel+sin(self.customTimer*memory.power)/(8+128/self.resource.fuel)
teamColors:true
image:DFCglowc.png
alpha:squareRoot(self.resource.fuel)/64+sin(self.customTimer*100)/5
layer:onTop
[decal_DFC]
imageScale:0.39+0.2*memory.power/self.resource.speed
teamColors:true
image:DFCfc.png
alpha:squareRoot(self.resource.fuel)/32
layer:onTop
[decal_glow]
imageScale:0.39
teamColors:true
total_frames:2
alpha:memory.power/(self.resource.fuel+64)*1.2
frame:int(rnd(0,2))
image:DFCglow.png
layer:onTop
[decal_glowH]
imageScale:0.39
teamColors:true
total_frames:2
color: #ff9100
alpha:self.resource.hfui/self.resource.fui
frame:int(rnd(0,2))
image:DFCglowo.png
layer:onTop
[action_start0]
text:提高磁铁功率
description:\n-缓慢提高电磁铁功率,加速磁流体\n-为工质提供基本动能并起到约束作用\n-单个周期全程消耗12MJ,45.6s
isVisible:true
#isLocked:if self.resource.speed > 1
canPlayerCancel:false
#displayType:infoOnlyNoBox
streamingCost:电力=12000,speed=-256
buildSpeed:45.6s
pos:1
highPriorityQueue:true
[action_stop0]
isVisible:true
text:降低磁铁功率
description:\n-缓慢降低电磁铁功率\n-单个周期全程消耗3MJ,11.1s
isLocked:if self.resource.speed < 255
canPlayerCancel:false
#displayType:infoOnlyNoBox
streamingCost:电力=2000,speed=256
buildSpeed:11.1s
pos:3
[action_dbg]
isVisible:true
text:调试
addResources:fuel=1280
setResourcesWithLogic:hfui=0
buildSpeed:0
[action_dbg2]
isVisible:true
text:调试2
addResources:fui=512
setResourcesWithLogic:hfui=0
buildSpeed:0
[hiddenAction_updt]
autoTrigger:true
setUnitMemory:cache1=min(self.resource.fui,0.01*memory.temp*self.resource.speed/256),temp=memory.power*16-1*memory.cache1,power=min(0.2*self.resource.fuel+2.2,self.resource.fuel)*self.resource.speed/512
addResourcesWithLogic:fui=--0.2*memory.cache1,hfui=0.2*memory.cache1,fuel=-0.1*memory.power