[core]
name:expRea
displayText:冲击反应堆[WIP]
displayDescription:-早期测试用的 现版本没有计划启用\n-凑合着用吧\n-供给250单位的电力
class:CustomUnitMetadata
price:红宝石=12000,heac=450,data=4096,rad=200
maxHp:6500
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
generation_resources:电力=250
generation_active:if self.resource.电力 < self.resource.cap
#if 电力+步长<=容量      视觉效果更好 不会有溢出 
#I dont enable this because I idk whether this expression will affect performance(放洋屁:P )
techLevel:1
buildSpeed:120s
availableInDemo:true
radius:30
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
unitsSpawnedOnDeath:NUKE2,NUKE,AP1
[attack]
canAttack:false
[graphics]
image:expRea_bs.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true
turretImageScale:0.85
[turret_pan]
x:0
y:0
canShoot:false
height:0
idleSpin:10
image:expRea_fui.png
[ai]
buildPriority:0.002
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02
maxEachBase:6
[movement]
movementType:HOVER
[decal_top]
image:expRea_top.png
layer:onTop