[core]
name:RTG
displayText:放射性同位素热电
displayDescription:-利用核素衰变中放出的热量发电\n-不受磁暴影响\n-建筑速度缓慢,被暴力摧毁后可能会有轻度放射性污染\n-供给12单位的电力
class:CustomUnitMetadata
price:rad=12,data=512,iron=500
maxHp:1500
shieldDisplayOnlyDeflection:true
mass:1000
#buildingToFootprintOffsetX:20
#buildingToFootprintOffsetY:20
constructionFootprint:-1,-1,1,1
footprint: -1,-1,1,1
generation_resources:电力=12
generation_active:if self.resource.电力 < self.resource.cap
#或许能通过min(cap,sto)来解决?
techLevel:1
buildSpeed:75s
availableInDemo:true
radius:22
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
unitsSpawnedOnDeath:Lboom,AP2
[attack]
canAttack:false
[graphics]
image:RTG2.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.05
noneInBaseExtraPriority:0.3
noneGlobalExtraPriority:0.3
maxEachBase:8
[movement]
movementType:HOVER