[core]
name:solPan1
displayText:太阳能板基座
displayDescription:-基础发电设施\n-无法自卫 \n-供给4单位的电力
class:CustomUnitMetadata
price:红宝石=250
maxHp:2650
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
borrowResourcesWhileAlive:电力=-4
techLevel:1
buildSpeed:0.001
availableInDemo:true
radius:30
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
[attack]
canAttack:false
[graphics]
image:solbs.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true
[turret_pan]
x:0
y:0
canShoot:false
height:1
idleSpin:0.15
image:solPan1.png
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.03
noneGlobalExtraPriority:0.03
maxEachBase:12
[movement]
movementType:HOVER
[action_updt]
convertTo:solPan2
text:升级T2
price:红宝石=500
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0) or numberOfUnitsInTeam(withTag='TECH3', greaterThan=0) or numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
#[hiddenAction_updt2]
#convertTo:aiele
#autoTrigger:true
#requireConditional:if self.isControlledByAI()