[core]
name:	bastion
displayText:机械堡垒
displayDescription:-威力巨大的爆发攻击\n-超级自行火炮\n-飞行时不能攻击\n-血厚\n-看着有点眼熟？
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:iron=2000,data=1000
tags:btsp
maxHp:10000
maxShield:30000
shieldRegen:2
mass:180
techLevel:1
buildSpeed:62s
radius:34
isBio:false

fogOfWarSightRange:12
builtFrom_1_name:mechfc1

shieldDisplayOnlyDeflection:true
unitsSpawnedOnDeath:Lboom
explodeOnDeathGroundCollision:false
explodeOnDeath:false
showActionsWithMixedSelectionIfOtherUnitsHaveTag:mech
energyMax:300
energyRegen:1
[graphics]
icon_zoomed_out:ROOT:icon/mech.png
total_frames:1
#image_top:hv-mech.png
image:bastion.png
image_wreak:NONE
scaleImagesTo:80
lock_body_rotation_with_main_turret:true
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
showHealthBar:false
showShieldBar:false
[attack]
setMainTurretAs:1
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:300
shootDelay:30
turretRotateWithBody:true
isFixedFiring:true
[turret_1]
barrelY:10
shoot_sound:ROOT:/SFX/cvsShoot.ogg
shoot_sound_vol:0.6
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:0.2
onShoot_freezeBodyMovementFor:1.2s
shoot_flame:shockwave,largeExplosion
shoot_light: #ffbf00
recoilOffset:-30
recoilOutTime:15
recoilReturnTime:30
warmup:100
chargeEffectImage:ltbl.png
energyUsage:300
canAttackCondition: if not self.flying
clearTurretTargetAfterFiring:true
limitingAngle:60
idleDir:0
limitingMinRange: 60
warmupStartEffect:charge

[projectile_1]
trailEffect:projectileTrail
trailEffectRate:2
pushForce:500

turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
directDamage:1500
buildingDamageMultiplier:4
areaDamage:1000
areaRadius:180
#teamColorRatio:1
image:ltbl.png
#ROOT:/unit/ball.png
life:100
speed:4
frame:1
drawSize:0.8
lightColor:#00fbff
lightSize:0.5
tags:laser
explodeEffect:CUSTOM:d*5
explodeOnEndOfLife:true
spawnProjectilesOnExplode:1(recursionLimit=5)
retargetingInFlightSearchDelay:2
spawnProjectilesOnCreate:3*7(offsetRandomDir=361)
[projectile_3]
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
retargetingInFlightSearchDelay:3
directDamage:250
life:120
speed:3
pushForce:100

drawSize:0.6

image:ROOT:/unit/steam.png
lightColor: #ffff22
lightSize:1
explodeOnEndOfLife:true
[effect_d]
image:ROOT:\effect\ydot.png
priority:high
attachedToUnit:false
life:60
physics:true
xSpeedRelativeRandom:7
ySpeedRelativeRandom:7
hSpeed:1
hSpeedRandom:1

[effect_charge]
image:ltbl.png
priority:high
attachedToUnit:true
life:100
alpha:0.6
fadeOut:true
fadeInTime:30
scaleFrom:3
scaleTo:0.5
alsoPlaySound:ROOT:/SFX/cvsCharge.ogg
[effect_y]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:8
color:#ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:0.4
scaleTo:0.05
[movement]
movementType:AIR
moveSpeed:1.5
moveAccelerationSpeed:0.05
moveDecelerationSpeed:0.05
joinsGroupFormations:true
maxTurnSpeed:0.7
turnAcceleration:1
moveSlidingMode:false
moveIgnoringBody:false
landOnGround:true
[ai]
buildPriority:0.03
noneInBaseExtraPriority:0.05
noneGlobalExtraPriority:0.05


[decal_sctC]
image:ROOT:sctm.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.04*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2


[animation_dust]
onActions:move
effect_0.2s:{x:0,y:0,name:lt*1}
[effect_lt]
delayedStartTimerRandom:10
image:ltbl.png
life:60
scaleFrom:1.3
scaleTo:0.5
priority:critical
alpha:0.8
attachedToUnit:true
dirSpeedRandom:1
dirSpeed:2
yOffsetRelative:-30
drawUnderUnits:true
#hOffset:10

[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*60
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*60)-60
yOffsetAbsolute:-45
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:60
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-45
onlyWhileActive:true

[decal_bar_sd]
color: #22ffda
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.shield / self.maxShield)*60
alwaysStartDirAtZero:true
isVisible:if not (self.shield == self.maxShield)
onlyOnNonPreview:true
xOffsetAbsolute:((self.shield / self.maxShield)*60)-60
yOffsetAbsolute:-40
alpha:0.8
onlyWhileActive:true
[decal_sd_back]
color: #004869
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.shield == self.maxShield)
imageScale:2
imageScaleX:60
alpha:0.5
yOffsetAbsolute:-40
alwaysStartDirAtZero:true
onlyOnNonPreview:true
onlyWhileActive:true

[effect_projectileTrail]
image:lttra.png
life:100
fadeOut: true
attachedToUnit: false

fadeInTime:10
scaleFrom: 1
scaleTo: 0.1
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
#dirOffsetRandom:180

#xSpeedAbsoluteRandom: 0.2
#ySpeedAbsoluteRandom: 0.2

total_frames:4
animateFrameStart:0
animateFrameEnd:3
animateFrameSpeed:0.1