[core]
name:hvt
displayText:小型空间浮游炮
displayText_en:def_bs
displayDescription:-遛狗用的
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:红宝石=800
tags:mech
maxHp:800
mass:100
techLevel:1
buildSpeed:24s
radius:7
isBio:false
fogOfWarSightRange:20
#builtFrom_1_name:stafc1
unitsSpawnedOnDeath:Sboom
explodeOnDeath:false
showActionsWithMixedSelectionIfOtherUnitsHaveTag:mech
builtFrom_1_name:mechfc1
[graphics]
icon_zoomed_out:ROOT:icon/mech.png
total_frames:1
image:hv-turt.png
teamColorsOnTurret:true
image_wreak:NONE
scaleImagesTo:18
lock_body_rotation_with_main_turret:false
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
showEnergyBar:false
showHealthBar:false
showShieldBar:false
turretImageScale:1.2
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
setMainTurretAs:1
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:140
shootDelay:20
turretRotateWithBody:false
[turret_1]
image:smmtur.png
x:0
y:0
projectile:1
barrelY:20
turnSpeed:2
turnSpeedAcceleration:1
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:1
shoot_flame:NONE
shoot_light: #00FFFF
recoilOffset:-1
recoilOutTime:1
recoilReturnTime:10
[projectile_1]
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
directDamage:50
teamColorRatio:1
image:ROOT:/unit/steam.png
life:100
speed:14
frame:1
drawSize:0.8
lightColor:#00fbff
lightSize:0.5
tags:steam
explodeEffect:CUSTOM:d*3,p*1,y*1

[effect_d]
image:ROOT:\effect\ydot.png
priority:high
attachedToUnit:false
life:20
physics:true
xSpeedRelativeRandom:2
ySpeedRelativeRandom:2
hSpeed:1
hSpeedRandom:1

[effect_p]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:5
alpha:0.1
fadeOut:true
fadeInTime:0.5
scaleFrom:3
scaleTo:0.1
[effect_y]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:8
color:#ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:0.4
scaleTo:0.05
[movement]
movementType:HOVER
moveSpeed:1
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
joinsGroupFormations:true
maxTurnSpeed:1
turnAcceleration:1
moveSlidingMode:false
moveIgnoringBody:true
targetHeight:3.5
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.05
noneGlobalExtraPriority:0.05

[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*15
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*15)-15
yOffsetAbsolute:-22
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:15
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-22
onlyWhileActive:true
[decal_sctC]
image:ROOT:sctm.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.02*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2