[core]
name:Kblaster
displayText:动能冲击舰
displayText_en:space truck
displayDescription:-大运
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:红宝石=2500,heac=10
tags:btsp
maxHp:6000
selfRegenRate:1.5
mass:18
techLevel:1
buildSpeed:21.1s
radius:25
isBio:false
fogOfWarSightRange:4
builtFrom_1_name:mechfc1
shieldDisplayOnlyDeflection:false
unitsSpawnedOnDeath:Sboom
explodeOnDeathGroundCollision:false
explodeOnDeath:false

showActionsWithMixedSelectionIfOtherUnitsHaveTag:mech

[graphics]
#image_shield:ROOT:shh.png
icon_zoomed_out:ROOT:icon/mech.png

#image_top:hv-mech.png
image:Kblaster.png
image_wreak:NONE
scaleImagesTo:25
lock_body_rotation_with_main_turret:true
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start:1
animation_moving_end:1
animation_moving_speed:1
animation_idle_start:0
animation_idle_end:0
showEnergyBar:false
showHealthBar:false
showShieldBar:false
total_frames:2
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
setMainTurretAs:1
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:30
shootDelay:1
isMelee:true
turretRotateWithBody:true
[turret_1]
#image:barrel1.png
x:0
y:0
projectile:1
barrelY:10
turnSpeed:8
turnSpeedAcceleration:0.5
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:1
shoot_flame:NONE
shoot_light: #00FFFF
recoilOffset:5
recoilOutTime:2
recoilReturnTime:18
resourceUsage:hp=10
[projectile_1]
directDamage:800
pushForce:300
teamColorRatio:1
image:ROOT:/unit/ball.png
life:15
speed:120
frame:1
drawSize:0.1
lightColor: #ffd000
lightSize:4
explodeEffect:CUSTOM:d*5,p*1,y*1

[effect_d]
image:ROOT:\effect\ydot.png
priority:high
attachedToUnit:false
life:20
physics:true
xSpeedRelativeRandom:2
ySpeedRelativeRandom:2
hSpeed:1
hSpeedRandom:1

[effect_p]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:5
alpha:0.1
fadeOut:true
fadeInTime:0.5
scaleFrom:3
scaleTo:0.1
[effect_y]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:8
color:#ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:0.4
scaleTo:0.05
[movement]
movementType:HOVER
moveSpeed:5
moveAccelerationSpeed:0.05
moveDecelerationSpeed:0.05
joinsGroupFormations:false
maxTurnSpeed:3
turnAcceleration:1
moveSlidingMode:false
moveIgnoringBody:false

[ai]
buildPriority:0.03
noneInBaseExtraPriority:0.05
noneGlobalExtraPriority:0.05


[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*15
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*15)-15
yOffsetAbsolute:-12
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:15
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-12
onlyWhileActive:true


[decal_sctC]
image:ROOT:sctm.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.04*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2