[core]
name:mhvt
displayText:<空间浮游炮>
displayText_en:hoverlzm
displayDescription:-遛死狗用的
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:iron=1200
tags:mech
maxHp:4500
mass:250
techLevel:1
buildSpeed:38s
radius:15
isBio:false
fogOfWarSightRange:20
#builtFrom_1_name:stafc1
unitsSpawnedOnDeath:Sboom
explodeOnDeath:false
showActionsWithMixedSelectionIfOtherUnitsHaveTag:mech
builtFrom_1_name:mechfc1
[graphics]
turretImageScale:0.5
icon_zoomed_out:ROOT:icon/mech.png
total_frames:1
image:hv-turt2.png
teamColorsOnTurret:true
image_wreak:NONE
scaleImagesTo:35
lock_body_rotation_with_main_turret:true
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
showEnergyBar:false
showHealthBar:false
showShieldBar:false

disableLowHpSmoke:true
disableLowHpFire:true
[attack]
setMainTurretAs:2
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:230
shootDelay:20
turretRotateWithBody:false
[turret_1]
image:turM.png
x:0
y:0
projectile:1
barrelY:20
turnSpeed:2
turnSpeedAcceleration:1

shoot_sound:ROOT:/SFX/blast.ogg
shoot_sound_vol:1
shoot_flame:NONE
shoot_light: #00FFFF
recoilOffset:-2
recoilOutTime:3
recoilReturnTime:10
delay:50
[turret_2]
x:0
y:0
projectile:2
barrelY:14
barrelX:8
barrelOffsetX_onOddShots:-16
turnSpeed:1.4
turnSpeedAcceleration:0.5
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:1.4
shoot_flame:NONE
shoot_light: #d0ff00
recoilOffset:-1
recoilOutTime:1
recoilReturnTime:5
delay:10
limitingRange:125
[turret_3]
x:0
y:0
projectile:ld
barrelY:14
attachedTo:2
slave:true
turnSpeed:1.4
turnSpeedAcceleration:0.5
shoot_sound:ROOT:/SFX/stBlast.ogg
shoot_sound_vol:1.2
shoot_flame:NONE
shoot_light: #ffa200
recoilOffset:-5
recoilOutTime:20
recoilReturnTime:40
delay:70
limitingRange:155
[projectile_1]
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
directDamage:120
#teamColorRatio:1
image:ROOT:/unit/pj2.png
life:100
speed:14
frame:1
drawSize:0.5
lightColor:#00fbff
lightSize:0.5
tags:steam
explodeEffect:CUSTOM:d*3,p*1,y*1

[projectile_2]

directDamage:50
#teamColorRatio:1
image:ROOT:/unit/steam.png
life:100
speed:5
frame:1
drawSize:0.6
lightColor:#00fbff
lightSize:0.5
tags:steam
explodeEffect:CUSTOM:d*3,p*1,y*1

[projectile_ld]
targetGround:true
teamColorRatio:1
directDamage:50
#teamColorRatio:1
image:ROOT:/unit/ball.png
life:160
speed:2
frame:1
drawSize:0.6
lightColor: #ffd900
lightSize:2
tags:steam
explodeEffect:CUSTOM:d*6
trailEffect:true
#trailEffectRate:4
buildingDamageMultiplier:4
areaDamage:100
areaRadius:100
explodeOnEndOfLife:true
spawnProjectilesOnExplode:dot*5(offsetRandomDir=361)
[projectile_dot]
speedSpread:3
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
retargetingInFlightSearchDelay:3
directDamage:250
life:20
speed:8
pushForce:10

drawSize:0.3

image:ROOT:/unit/steam.png
lightColor: #ffff22
lightSize:0.5
explodeEffect:NONE
explodeOnEndOfLife:true
spawnProjectilesOnExplode:dot*4(offsetRandomDir=361,recursionLimit=2)
[effect_d]
image:ROOT:\effect\ydot.png
priority:high
attachedToUnit:false
life:20
physics:true
xSpeedRelativeRandom:2
ySpeedRelativeRandom:2
hSpeed:1
hSpeedRandom:1

[effect_p]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:5
alpha:0.1
fadeOut:true
fadeInTime:0.5
scaleFrom:3
scaleTo:0.1
[effect_y]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:8
color:#ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:0.4
scaleTo:0.05
[movement]
movementType:HOVER
moveSpeed:0.8
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
joinsGroupFormations:true
maxTurnSpeed:0.8
turnAcceleration:1
moveSlidingMode:false
moveIgnoringBody:true
targetHeight:3.5
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.05
noneGlobalExtraPriority:0.05

[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*15
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*15)-15
yOffsetAbsolute:-22
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:15
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-22
onlyWhileActive:true
[decal_sctC]
image:ROOT:sctm.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.02*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2