[core]
name:floatNiDie
displayText:空间浮游打碟
displayText_en:def_bs
displayDescription:-坐炮的爷爷
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:红宝石=450000
tags:mech
maxHp:65000
mass:1800
techLevel:1
buildSpeed:125s
radius:60
isBio:false
selfRegenRate:1
fogOfWarSightRange:20
builtFrom_1_name:stafc_huge


unitsSpawnedOnDeath:Lboom*3

explodeOnDeath:false


[graphics]
icon_zoomed_out:ROOT:icon/mech.png
total_frames:4
image:hv-tur.png
image_wreak:NONE
scaleImagesTo:120
lock_body_rotation_with_main_turret:false
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start:2
animation_moving_end:3
animation_moving_speed:20
animation_idle_start:0
animation_idle_end:1

turretImageScale:2
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
setMainTurretAs:1
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:360
shootDelay:10
turretRotateWithBody:false
[turret_1]
image:turM.png
x:0
y:0
projectile:1
barrelY:70
turnSpeed:10
turnSpeedAcceleration:1
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:1
shoot_flame:NONE
shoot_light: #00FFFF
recoilOffset:-2.5
recoilOutTime:2
recoilReturnTime:18
[projectile_1]

areaDamage:500
areaRadius:120
directDamage:500
largeHitEffect:true
image:ROOT:/unit/pj1.png
life:100
speed:18
frame:1
drawSize:0.8
lightColor: #ff0000
lightSize:2
tags:steam
explodeEffect:CUSTOM:d*3,p*1,y*1

[effect_d]
image:ROOT:\effect\ydot.png
priority:high
attachedToUnit:false
life:20
physics:true
xSpeedRelativeRandom:2
ySpeedRelativeRandom:2
hSpeed:1
hSpeedRandom:1

[effect_p]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:5
alpha:0.1
fadeOut:true
fadeInTime:0.5
scaleFrom:3
scaleTo:0.1
[effect_y]
image:ROOT:\effect\ospt.png
priority:high
attachedToUnit:false
life:8
color:#ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:0.4
scaleTo:0.05
[movement]
movementType:HOVER
moveSpeed:1
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
joinsGroupFormations:true
maxTurnSpeed:1
turnAcceleration:1
moveSlidingMode:false
moveIgnoringBody:true
targetHeight:3.5
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.05
noneGlobalExtraPriority:0.05

maxGlobal:80

[leg_1]
drawUnderAllUnits:true
x:0
y:0
attach_x:0
attach_y:0
lockMovement:true
hardLimit:10
image_end:mbase1.png
targetHeightRelative:true
targetHeight:-1.5
spinRate:0.4
dust_effect:true

[hiddenAction_deploy]



convertTo: floatNiDieD
displayType: action
price:  0
buildSpeed: 3s
whenBuilding_cannotMove: true
whenBuilding_rotateTo: 0
whenBuilding_rotateTo_orBackwards: true



canPlayerCancel: false
allowMultipleInQueue: false

alwaysSinglePress: true
[animation_1]
#onActions : Unknown
#underConstruction
leg1_3s: {dir:2}
#onActionsQueuedUnitPlayAt :0.1
[action_hid]
text: 坐下!
isVisible: true
buildSpeed:0s
playAnimation:1
alsoQueueAction:deploy

[attachment_1]
x:60
y:0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:staTur5

[attachment_2]
x:60
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:staLTur5
[attachment_3]
x:0
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:staRTur4
[attachment_4]
x:-60
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:hyperTractionBeam
[attachment_5]
x:-60
y:0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:singCan
[attachment_6]
x:-60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:dronefc4
[attachment_7]
x:0
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:misTurH3
[attachment_8]
x:60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:misTra2
[attachment_9]
x:60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:Ltur42
[attachment_10]
x:0
y:-0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:3tur-repair