[core]
name:floatNiDieD
displayText:坐下的空间浮游打碟

displayDescription:-biubiu
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:红宝石=450000
tags:mech
maxHp:65000
mass:18000
techLevel:1
buildSpeed:0.0001
radius:60
isBio:false

constructionFootprint:1,-1,1,1

fogOfWarSightRange:20
#builtFrom_1_name:stafc1

isBuilding:true
unitsSpawnedOnDeath:Sboom

explodeOnDeath:false

showActionsWithMixedSelectionIfOtherUnitsHaveTag:mech
maxShield: 500000
shieldRegen: 2.5
startShieldAtZero: true
[graphics]
image_shield:ROOT:shh.png
icon_zoomed_out:ROOT:icon/mech.png
total_frames:4
image:hv-tur.png
image_wreak:NONE
scaleImagesTo:120
lock_body_rotation_with_main_turret:false
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start:2
animation_moving_end:3
animation_moving_speed:20
animation_idle_start:0
animation_idle_end:1

turretImageScale:2
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:460
[decal_sctC]
image:ROOT:sctm.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.02*${core.radius}
teamColors:true
order:-2
alpha:0.3


[leg_1]
drawUnderAllUnits:true
x:0
y:0
attach_x:0
attach_y:0
lockMovement:true
hardLimit:10
image_end:mbase1.png
targetHeightRelative:true
targetHeight:-1.5
spinRate:0.1
dust_effect:true

[hiddenAction_deploy]



#convertTo: 
displayType: action
price:  0
buildSpeed: 3s
whenBuilding_cannotMove: true
whenBuilding_rotateTo: 0
whenBuilding_rotateTo_orBackwards: true



canPlayerCancel: false
allowMultipleInQueue: false

alwaysSinglePress: true

[action_hid]
text: 部署
isVisible: true
isLocked:true
[action_disdeploy]
text: 飞起来
isVisible: true
convertTo: floatNiDie
displayType: action
price:  0
buildSpeed: 2s
canPlayerCancel: false
allowMultipleInQueue: false
alwaysSinglePress: true
[movement]
movementType:HOVER



[attachment_1]
x:60
y:0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:staTur5

[attachment_2]
x:60
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:staLTur5
[attachment_3]
x:0
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:staRTur4
[attachment_4]
x:-60
y:60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:hyperTractionBeam
[attachment_5]
x:-60
y:0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:singCan
[attachment_6]
x:-60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:dronefc4
[attachment_7]
x:0
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:misTurH3
[attachment_8]
x:60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:45
onCreateSpawnUnitOf:misTra2
[attachment_9]
x:60
y:-60
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:Ltur42
[attachment_10]
x:0
y:-0
isUnselectable:false
canBeAttackedAndDamaged:true
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:3tur-repair