
[core]
copyFrom:"""ROOT:RW_Engine/View/StaticViews/LineTextView/LineTextViewSystem.ini"""

name:TextView
tags:TextView
showInEditor:true
#isUnselectable:false

@memory imageScaleX:number
@memory imageScaleY:number
@memory xOffsetAbsolute:number
@memory yOffsetAbsolute:number
updateUnitMemoryRate:0
updateUnitMemory:imageScaleX=((memory.textMax*(${defaultfontSize}*memory.textScale + memory.textMarginLeft)-memory.textMarginLeft)+13)/64,imageScaleY=((select(length(memory.text)%memory.textMax==0,length(memory.text)/memory.textMax,(length(memory.text)-(length(memory.text)%memory.textMax))/memory.textMax+1)*(${defaultfontSize}*memory.textScale + memory.textMarginTop)-memory.textMarginTop)+10)/32


@memory insertNum:number
@memory waitingText:string

autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true

#本图像默认1倍大小x只能放4个字y2行
[decal_1]
layer:beforeUI
xOffsetAbsolute:memory.xOffsetAbsolute+32*(memory.imageScaleX-1)
yOffsetAbsolute:memory.yOffsetAbsolute+16*(memory.imageScaleY-1)
imageScaleX:memory.imageScaleX
imageScaleY:memory.imageScaleY
image:文本显示框.png


[hiddenAction_TextViewCreated]
autoTriggerOnEvent:created
resetCustomTimer:true
setUnitMemory:imageScaleY=1,imageScaleX=1,text="",xOffsetAbsolute=21,yOffsetAbsolute=5,textMarginTop=1,textMax=int(5*memory.imageScaleY),textScale=${defaultFontScale}
sendMessageTo:self.customTarget1
sendMessageWithTags:TextViewCreated
alsoTriggerAction:viewText



[hiddenAction_TextViewInsert]
autoTriggerOnEvent:newMessage(withTag="TextViewInsert")
setUnitMemory:insertNum=select((length(memory.text) % memory.textMax)==0,0,memory.textMax-(length(memory.text) % memory.textMax)),waitingText=eventData("text",type="string")
alsoTriggerAction:insertSpace
alsoQueueAction:viewTextImmediately
alsoTriggerActionRepeat:memory.insertNum

showMessageToAllPlayers:%{eventData("text",type="string")} %{memory.insertNum}
[hiddenAction_insertSpace]
setUnitMemory:text=memory.text+" "
alsoTriggerAction:viewText-2
alsoTriggerOrQueueActionConditional:if index+1 == memory.insertNum

[hiddenAction_viewTextImmediately]
buildSpeed:0.0s
requireConditional:if length(memory.text) % memory.textMax == 0
setUnitMemory:text=memory.text+memory.waitingText
alsoTriggerAction:viewText

[hiddenAction_viewText-2]
setUnitMemory:text=memory.text+memory.waitingText
alsoTriggerAction:viewText





[hiddenAction_TextViewInit]
autoTriggerOnEvent:newMessage(withTag="TextViewInit")
setUnitMemory:commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource,textMax=select(eventData("textMax",type="number")<=0,memory.textMax,eventData("textMax",type="number")),text=""
#showMessageToAllPlayers:mmnn
#alsoTriggerAction:循环



[hiddenAction_AutoViewText]
#autoTrigger:if length(memory.realText) == memory.textIndex and memory.viewLocked == false
#setUnitMemory:viewLocked=true
alsoTriggerAction:viewText



#updateUnitMemory:
[hiddenAction_parentDeleted]
@copyFrom_skipThisSection:true

