[core]
copyFrom:ROOT:tmp/turret.template
name:Ltur2
displayText:裂解T2
displayDescription:-\n-射程15格\n-消耗5kW电力
class:CustomUnitMetadata
price:红宝石=6000
maxHp:3000
borrowResourcesWhileAlive:电力=5
techLevel:1
buildSpeed:0.002
energyMax:50
energyRegen:0.03
energyNeedsToRechargeToFull:true

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:300
[turret_1]
x:0
y:0
laserDefenceEnergyUse:1
canAttackCondition:if self.resource.电力>0
#shoot_sound:
#shoot_sound_vol:0.5
[graphics]
turretImageScale:0.5
total_frames:2
icon_zoomed_out:ROOT:icon/def.png
image:Ltur2.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.03
noneInBaseExtraPriority:0.04
noneGlobalExtraPriority:0.04
maxEachBase:12
maxGlobal:50
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0