[core]
copyFrom:ROOT:tmp/turret.template
name:Ltur41
displayText:缓冲型裂解
displayDescription:-\n-射24格\n-消耗12kW电力
class:CustomUnitMetadata
price:红宝石=24000
maxHp:8000
borrowResourcesWhileAlive:电力=12
techLevel:1
buildSpeed:0.002
energyMax:80
energyRegen:0.5
energyNeedsToRechargeToFull:true
maxShield:1000
shieldRegen:4
[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:480
[turret_1]
x:0
y:0
laserDefenceEnergyUse:1
canAttackCondition:if self.resource.电力>0
#shoot_sound:
#shoot_sound_vol:0.5
[graphics]
image_shield:ROOT:shs.png
turretImageScale:0.5
total_frames:2
icon_zoomed_out:ROOT:icon/def.png
image:Ltur41.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.01
maxEachBase:12
maxGlobal:50
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0