[core]
copyFrom:ROOT:tmp/turret.template
name:Ltur3
displayText:裂解T3
displayDescription:-\n-射程18格\n-消耗7kW电力
class:CustomUnitMetadata
price:红宝石=12000
maxHp:5000
borrowResourcesWhileAlive:电力=7
techLevel:1
buildSpeed:0.002
energyMax:80
energyRegen:0.06
energyNeedsToRechargeToFull:true

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:360
[turret_1]
x:0
y:0
laserDefenceEnergyUse:1
canAttackCondition:if self.resource.电力>0
#shoot_sound:
#shoot_sound_vol:0.5
[graphics]
turretImageScale:0.5
total_frames:2
icon_zoomed_out:ROOT:icon/def.png
image:Ltur3.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.01
maxEachBase:12
maxGlobal:50
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0
[action_updt2]
buildSpeed:45s
text:升级-缓冲型T4
price:红宝石=12000
displayType:upgrade
unitShownInUI:Ltur41
allowMultipleInQueue:false
convertTo:Ltur41
ai_isHighPriority:true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
[action_updt3]
buildSpeed:45s
text:升级-储存型T4
price:红宝石=12000
displayType:upgrade
unitShownInUI:Ltur42
allowMultipleInQueue:false
convertTo:Ltur42
ai_isHighPriority:true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!