[core]
copyFrom:ROOT:tmp/turret.template
name:Ltur1
displayText:裂解
displayDescription:-\n-射程10格\n-消耗2kW电力
class:CustomUnitMetadata
price:红宝石=1600
maxHp:1000
borrowResourcesWhileAlive:电力=2
techLevel:1
buildSpeed:0.002
energyMax:25
energyRegen:0.01
energyNeedsToRechargeToFull:true

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:200
[turret_1]
x:0
y:0
laserDefenceEnergyUse:1
canAttackCondition:if self.resource.电力>0
#shoot_sound:
#shoot_sound_vol:0.5
[graphics]
turretImageScale:0.5
total_frames:2
icon_zoomed_out:ROOT:icon/def.png
image:Ltur1.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.03
noneInBaseExtraPriority:0.04
noneGlobalExtraPriority:0.04
maxEachBase:12
maxGlobal:50
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0

[action_updt2]
buildSpeed:13s
text:升级-T2
price:红宝石=2400
displayType:upgrade
unitShownInUI:Ltur2
allowMultipleInQueue:false
convertTo:Ltur2
ai_isHighPriority:true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!