[core]
name:walla3
displayText:巨构合金墙
displayDescription:-反弹
class:CustomUnitMetadata
price:heac=12
maxHp:24000
techLevel:1
buildSpeed:16s
footprint: -1,-1,1,1
constructionFootprint:-1,-1,1,1
radius:30
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
mass:100
shieldDisplayOnlyDeflection:true
energyMax:20
energyRegen:0.24
energyNeedsToRechargeToFull:false
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:100
[turret_1]
x:0
y:0
laserDefenceEnergyUse:0.5
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:0.5
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
total_frames:1
icon_zoomed_out:ROOT:icon/wall.png
image:walla3.png
image_shadow:AUTO
image_wreak:wall3W.png
shadowOffsetX:1
scaleImagesTo:60
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02
#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0