[core]
name:wall2
displayText:大墙
displayDescription:-a good defender but no laser def.\n- oh no
class:CustomUnitMetadata
price:红宝石=260
maxHp:3000
techLevel:1
buildSpeed:0.5s
footprint: 0,0,1,1
constructionFootprint:0,0,1,1
buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
radius:20
buildingSelectionOffset: -8
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
mass:100
shieldDisplayOnlyDeflection:true
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:1
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
total_frames:1
icon_zoomed_out:ROOT:icon/wall.png
image:wall.png
image_shadow:AUTO
image_wreak:walWl.png
shadowOffsetX:1
scaleImagesTo:40
shadowOffsetY:1
[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.04
noneGlobalExtraPriority:0.04
maxEachBase:12
maxGlobal:50
#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0