[core]
name:wall3
displayText:巨无霸墙
displayDescription:-a good defender but no laser def.\n- oh no
class:CustomUnitMetadata
price:红宝石=600
maxHp:9000
techLevel:1
buildSpeed:5s
footprint: -1,-1,1,1
constructionFootprint:-1,-1,1,1
radius:30
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
mass:100
shieldDisplayOnlyDeflection:true
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:1
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
total_frames:1
icon_zoomed_out:ROOT:icon/wall.png
image:wall.png
image_shadow:AUTO
image_wreak:walWl.png
shadowOffsetX:1
scaleImagesTo:60
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02
#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0