[core]
name:wall
displayText:墙
displayDescription:-a good defender but no laser def.\n- oh no
class:CustomUnitMetadata
price:红宝石=50
maxHp:800
techLevel:1
buildSpeed:0.5s
constructionFootprint:0,0,0,0
footprint: 0,0,0,0
availableInDemo:true
radius:10
displayRadius:10
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
mass:100
shieldDisplayOnlyDeflection:true
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:1
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
turretImageScale:0.5
total_frames:1
icon_zoomed_out:ROOT:icon/wall.png
image:wall.png
image_wreak:walWl.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:20
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02

#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0