[core]
name:walla
displayText:合金墙
displayDescription:使用合金作为镀层的墙\n-概率吸收附近的物理子弹
class:CustomUnitMetadata
price:heac=1
maxHp:1300
techLevel:1
buildSpeed:2.2s
constructionFootprint:0,0,0,0
footprint: 0,0,0,0
availableInDemo:true
radius:10
displayRadius:10
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta
mass:100
shieldDisplayOnlyDeflection:true
energyMax:2
energyRegen:0.03
energyNeedsToRechargeToFull:false
[attack]
#fake attack
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:20
[turret_1]
x:0
y:0
laserDefenceEnergyUse:0.5
shoot_sound:ROOT:/SFX/pluse.ogg
shoot_sound_vol:0.5
[turret_fake]
x:0
y:0
canShoot:false
[graphics]
turretImageScale:0.5
total_frames:1
icon_zoomed_out:ROOT:icon/wall.png
image:walla.png
image_wreak:walWl.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:20
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.02

#notPassivelyTargetedByOtherUnits:true
lowPriorityTargetForOtherUnits:false
[movement]
movementType:HOVER
targetHeight:0
targetHeightDrift:0