[core]
name:VirtualDisk
class:CustomUnitMetadata
price:0
maxHp:1
mass:0
buildSpeed:0
isBuilding: true
radius:0
stayNeutral:true
isBio:false
showOnMinimap:false
canNotBeDirectlyAttacked: true
canNotBeDamaged:true
autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true
showInEditor:false

tags:VirtualDisk
#showInEditor:false
#@memory lsTreeNames:string[]
#@memory lsTreeType:string[]
@memory indexFileTypeCaches:number[]
@memory indexFileNameCaches:number[]
@memory indexContentCaches:number[]
@memory indexCommaCaches:number[]
@memory indexFileTmp:number

#存储所有FileSystem
@memory unitEpoll:unit[]

@memory nowInFileSystem:number
@memory oneFileContentTmp:string
[attack]

canAttack:false


[graphics]
total_frames:1
image:VirtualDisk.png
image_wreak:NONE
image_turret:NONE
imageSmoothing:true

[movement]
movementType:NONE

[hiddenAction_created]
autoTriggerOnEvent:created
resetCustomTimer:true
setUnitMemory:nowInFileSystem=0
spawnUnits:FileSystem*1


[hiddenAction_addFileSystemToEpoll]
autoTriggerOnEvent:newMessage(withTag="addFileSystemToEpoll")
setUnitMemory:unitEpoll[memory.unitEpoll.size] = eventSource


[hiddenAction_updateLsTreeData]
autoTriggerOnEvent:newMessage(withTag="updateLsTreeData")
setUnitMemory:indexFileTypeCaches=null,indexFileNameCaches=null,indexContentCaches=null,indexCommaCaches=null
alsoTriggerAction:getOneFile
alsoTriggerOrQueueActionWithTarget:memory.unitEpoll[memory.nowInFileSystem]

[action_getOneFile]
alsoTriggerAction:gettingOneFile
setUnitMemory:indexFileTypeCaches=null,indexFileNameCaches=null,indexContentCaches=null,indexCommaCaches=null
alsoTriggerActionRepeat:memory.unitEpoll[memory.nowInFileSystem].readUnitMemory("indexContentCaches",type="number[]").size
alsoTriggerOrQueueActionWithTarget:memory.unitEpoll[memory.nowInFileSystem]


[hiddenAction_gettingOneFile]
setUnitMemory:oneFileContentTmp=substring(thisActionTarget.readUnitMemory("Content",type="string"),thisActionTarget.readUnitMemory("indexContentCaches",type="number[]")[index]+3,thisActionTarget.readUnitMemory("indexContentCaches",type="number[]")[(index+1)]),indexFileTmp=thisActionTarget.readUnitMemory("indexContentCaches",type="number[]")[index]+3
alsoTriggerAction:analyzeFileData

[hiddenAction_analyzeFileData]
requireConditional:if memory.oneFileContentTmp != "|"
alsoTriggerAction:analyzingFileTypeData,analyzingFileNameData,analyzingFileContentData,analyzingFileCommaData
alsoTriggerActionRepeat:length(memory.oneFileContentTmp)

[hiddenAction_analyzingFileTypeData]
requireConditional:if substring(memory.oneFileContentTmp,index,index+9)=="FileType:"
setUnitMemory:indexFileTypeCaches[memory.indexFileTypeCaches.size]=index+memory.indexFileTmp
[hiddenAction_analyzingFileNameData]
requireConditional:if substring(memory.oneFileContentTmp,index,index+9)=="FileName:"
setUnitMemory:indexFileNameCaches[memory.indexFileNameCaches.size]=index+memory.indexFileTmp
[hiddenAction_analyzingFileContentData]
requireConditional:if substring(memory.oneFileContentTmp,index,index+8)=="Content"
setUnitMemory:indexContentCaches[memory.indexContentCaches.size]=index+memory.indexFileTmp
[hiddenAction_analyzingFileCommaData]
requireConditional:if substring(memory.oneFileContentTmp,index,index+1)==("""','""")
setUnitMemory:indexCommaCaches[memory.indexCommaCaches.size]=index+memory.indexFileTmp



[hiddenAction_getAllFileName]
autoTriggerOnEvent:newMessage(withTag="getAllFileName")
setCustomTarget2:eventSource
alsoTriggerAction:sendFileName
alsoTriggerActionRepeat:memory.indexFileNameCaches.size
alsoTriggerOrQueueActionWithTarget:memory.unitEpoll[memory.nowInFileSystem]

[hiddenAction_sendFileName]
sendMessageTo:self.customTarget2
sendMessageWithTags:sendFileName
sendMessageWithData:fileName=substring(thisActionTarget.readUnitMemory("Content",type="string"),memory.indexFileNameCaches[index]+9,memory.indexCommaCaches[(((index+1)*2)-1)]),isEnd=select(index+1 == memory.indexFileNameCaches.size,true,false)

#showMessageToAllPlayers:%{substring(thisActionTarget.readUnitMemory("Content",type="string"),memory.indexFileNameCaches[index]+9,memory.indexCommaCaches[(((index+1)*2)-1)])}
[action_getAllFileNameTest]
isVisible:true
text:%{memory.indexFileNameCaches[0]}
alsoTriggerAction:getAllFileName
setUnitMemory:indexFileTypeCaches=null,indexFileNameCaches=null,indexContentCaches=null,indexCommaCaches=null
