[core]
copyFrom:"""ROOT:RW_Engine/View/View.md"""
name:FileSystem
tags:FileSystem
#showInEditor:false
@memory info:string
@memory indexContentCaches:number[]
@memory Content:string
showInEditor:false

[hiddenAction_created]
autoTriggerOnEvent:created
resetCustomTimer:true
sendMessageTo:self.customTarget1
sendMessageWithTags:addFileSystemToEpoll

[hiddenAction_setInfo]
autoTriggerOnEvent:newMessage(withTag="setInfo")
setUnitMemory:info="///infoType:" + eventData("infoType",type="string") + " " + "infoName:" +eventData("infoName",type="string")

[hiddenAction_updateContentIndexCaches]
autoTriggerOnEvent:newMessage(withTag="updateContentIndexCaches")
setUnitMemory:indexContentCaches=null
alsoTriggerAction:updatingContentIndexCaches
alsoTriggerActionRepeat:length(memory.Content)



[hiddenAction_updatingContentIndexCaches]
requireConditional:if substring(memory.Content,index,index+3) == "///"
setUnitMemory:indexContentCaches[memory.indexContentCaches.size]  = index


[action_updateContentIndexCachesTest]
text:测试缓存
setUnitMemory:Content="///FileType:Text,FileName:这是一个文件,Content:shishanyue真可爱///|///FileType:Text,FileName:text,Content:test///|///FileType:Text,FileName:gogo,Content:gogo///"
alsoTriggerAction:updateContentIndexCaches


[action_add]
text:添加一个ab文件
setUnitMemory:Content=memory.Content + "|///FileType:Text,FileName:ab,Content:shishanyue真可爱///"
alsoTriggerAction:updateContentIndexCaches
