[core]
name:empBomber
displayText:EMP-FUSE(驱逐舰)
displayText_en:EMP-FUSE
displayDescription:FUSE的改版\n-投掷磁暴炸弹对护盾和电子设施有额外伤害,对成群的激光拦截很有效果\n-相较普通轰炸机转速和减速度更高/n[磁暴II]对电子设施造成2.5倍伤害
displayDescription_en:-$null ha ha ha
class:CustomUnitMetadata
price:红宝石=3200
tags:btsp
maxHp:2600
mass:80
techLevel:1
buildSpeed:33.3s
radius:14
isBio:false
fogOfWarSightRange:18

builtFrom_3_name:motherShip
shieldDisplayOnlyDeflection:true
unitsSpawnedOnDeath:Sboom
explodeOnDeathGroundCollision:true
explodeOnDeath:true
energyMax:6
energyRegen:0.008
energyNeedsToRechargeToFull:true
showActionsWithMixedSelectionIfOtherUnitsHaveTag:btsp
[effect_projectileTrail]
createWhenZoomedOut:false
priority:low
image:SHARED:light_50.png
life:30
fadeOut:true
attachedToUnit:false
color:#63e6e8
fadeInTime:2
scaleFrom:0.2
scaleTo:1
alpha:0.8
drawUnderUnits:true
ySpeedRelative:0.1
atmospheric:true
[graphics]
icon_zoomed_out:ROOT:icon/btsp2.png
total_frames:2
image:empBomber.png
image_wreak:NONE
scaleImagesTo:33
lock_body_rotation_with_main_turret:false
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

showHealthBar:false
showShieldBar:false
animation_moving_start:1
animation_moving_end:1
animation_moving_speed:1
animation_idle_start:0
animation_idle_end:0
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
isMelee:true
meleeEngangementDistance:100
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:true
maxAttackRange:45
shootDelay:36

attackMovement:bomber
[turret_1]
x:0
y:0
projectile:1
barrelY:0
turnSpeed:8
turnSpeedAcceleration:1
shoot_sound:ROOT:/SFX/exp1.ogg
shoot_sound_vol:0.2
shoot_flame:NONE
shoot_light: #ddff00
energyUsage:1
[projectile_1]
mutator1_ifUnitWithTags:ele
mutator1_areaDamageMultiplier:2.5
hullDamageMultiplier:0.8
pushVelocity:-1
areaDamageNoFalloff:true
largeHitEffect:true
pushForce:25

deflectionPower:10
image:bomb.png
targetGround:true
targetGroundSpread:15

areaDamage:256
color: #aaddff
areaRadius:80
directDamage:200
life:100

speed:0.1
targetSpeed:8
targetSpeedAcceleration:0.1

initialUnguidedSpeedY:-3
gravity:0.5

frame:1
drawSize:0.4
trailEffect:true
trailEffectRate:8
spawnProjectilesOnExplode:2*5(offsetRandomDir=360)
explodeEffect:CUSTOM:e*5,p*1,y*1,boome*1,scw*1,boom112*1
[projectile_2]
gravity:2
speedSpread:5
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
pushForce:10
deflectionPower:5
image:ROOT:/unit/ball.png
directDamage:50
life:60
speed:15
targetSpeed:0.4
targetSpeedAcceleration:0.4
frame:1
drawSize:0.3
color: #ffeb3c
explodeEffect:CUSTOM:e
[effect_e]
image:ROOT:\effect\ee.png

priority:high
attachedToUnit:false
life:45
physics:true
scaleFrom:0.4
xSpeedRelativeRandom:5
ySpeedRelativeRandom:5
hSpeed:1
hSpeedRandom:1

[effect_p]
image:ROOT:\unit\bbbd.png
color: #0daaff
priority:high
attachedToUnit:false
life:20
alpha:0.5
fadeOut:true
fadeInTime:0.3
scaleFrom:3
scaleTo:0.1
[effect_y]
image:ROOT:\effect\wspt.png
priority:high
attachedToUnit:false
life:18
#color: #ffdd00
alpha:0.3
fadeOut:true
fadeInTime:0.4
scaleFrom:3
scaleTo:2
[effect_boome]
image:ROOT:/unit/bbb.png
life:13
fadeOut: true
attachedToUnit: false
fadeInTime:0.4
scaleFrom: 2
scaleTo: 0.6
alpha: 0.9
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
#dirOffsetRandom:180
[effect_scw]
priority:critical
image:ROOT:\displacement\wave.png
life:8
attachedToUnit:false
scaleFrom:0.2
scaleTo:0.8
drawUnderUnits:false
fadeOut:true
#fadeInTime:0.4
alpha:0.8
drawType: displacement
alwayStartDirAtZero:true
[movement]
slowDeathFall: true
movementType:AIR
moveSpeed:1.9
moveAccelerationSpeed:0.06
moveDecelerationSpeed:0.04
joinsGroupFormations:true
maxTurnSpeed:2.3
turnAcceleration:0.8
moveSlidingMode:true
moveIgnoringBody:false
landOnGround:true
[ai]
buildPriority:0.008
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.005

[decal_bar_mine]
color: #ff2222
image:SHARED:white_pixel.png
imageScale:2
imageScaleX:(self.hp / self.maxHp)*30
alwaysStartDirAtZero:true
isVisible:if not (self.hp == self.maxHp)
onlyOnNonPreview:true
xOffsetAbsolute:((self.hp/self.maxHp)*30)-30
yOffsetAbsolute:-25
alpha:0.8
onlyWhileActive:true
[decal_mine_back]
color: #360b0b
image:SHARED:white_pixel.png
order:-1
isVisible:if not (self.hp == self.maxHp)
imageScale:2
imageScaleX:30
alpha:0.5
alwaysStartDirAtZero:true
onlyOnNonPreview:true
yOffsetAbsolute:-25
onlyWhileActive:true





[decal_sctC]
image:ROOT:sct.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:0.04*${core.radius}
teamColors:true
order:-2
alpha:0.3
[decal_sctA]
image:ROOT:sctarr_bs1.png
onlyWhileActive:true
onlyWhenSelectedByOwnPlayer:true
yOffsetRelative:${core.radius}
teamColors:true
order:-1
alpha:0.2


[effect_boom112]
image:ROOT:/effect/blue_explosion.png
life:30
fadeOut: true
attachedToUnit: false
fadeInTime:0.4
scaleFrom: 0.7
scaleTo: 5
alpha: 0.9
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
total_frames:13
animateFrameStart:0
animateFrameEnd:12
animateFrameSpeed:0.1