[core]
name:hea-itcpt
displayText:重型拦截无人机
class: CustomUnitMetadata
price:红宝石=1500
maxHp:800
maxShield:1600
shieldRegen:0.8
mass:80
techLevel:1
buildSpeed:0.001
availableInDemo: false
radius:15

isBio:false
isBuilder:false

tags:drone
showActionsWithMixedSelectionIfOtherUnitsHaveTag:drone
[graphics]
total_frames:1
image:hea-itcpt.png
icon_zoomed_out:ROOT:icon/drone.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:40
shadowOffsetX:1
shadowOffsetY:1
lock_body_rotation_with_main_turret:true
image_shield:ROOT:shh.png
[attack]
canAttackFlyingUnits:true
canAttackLandUnits:false
canAttackUnderwaterUnits:false
canAttack:true


maxAttackRange:220
shootDelay:10
[turret_barrel]
x:0
y:0
barrelX:-14
projectile:1
invisible:true
turnSpeed:2
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.2
shoot_flame:small
shoot_light: #FFff00
canShoot:true
recoilOffset: -1
recoilOutTime: 6
recoilReturnTime: 7
#idleSweepAddRandomAngle:40
[turret_barrel2]
x:0
y:0
barrelX:14
projectile:1
invisible:true
turnSpeed:2
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.2
shoot_flame:small
shoot_light: #FFff00
canShoot:true

#idleSweepAddRandomAngle:40
slave:true
attachedTo:barrel
[projectile_1]
directDamage:45
teamColorRatio:1
image:ROOT:/unit/steam.png
life:30
speed:16
frame:1
drawSize:0.4
lightColor: #00fbff
lightSize:0.4
tags:steam
explodeEffect: CUSTOM:lightSlowFade
[effect_lightSlowFade]
image: SHARED:light_50.png
life:40
fadeOut:true
attachedToUnit: true
color: #00ccff
scaleFrom:0.7
scaleTo:0.2
alpha:0.5
[movement]
movementType:AIR
moveSpeed:3.2
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
maxTurnSpeed:2.3
turnAcceleration:0.5
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.1
maxGlobal:80