[core]
name:meg-itcpt
displayText:堡垒拦截机
class: CustomUnitMetadata
price:红宝石=7000
maxHp:1500
maxShield:7600
shieldRegen:5
mass:80
techLevel:1
buildSpeed:0.0002
availableInDemo: false
radius:20

isBio:false
isBuilder:false

tags:drone
showActionsWithMixedSelectionIfOtherUnitsHaveTag:drone

builtFrom_2_name:dronefc3
builtFrom_3_name:dronefc4
[graphics]
turretImageScale:1.5
total_frames:1
image:meg-itcpt.png
icon_zoomed_out:ROOT:icon/drone.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:40
shadowOffsetX:1
shadowOffsetY:1
lock_body_rotation_with_main_turret:true
image_shield:ROOT:shh.png
[attack]
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
canAttack:true


maxAttackRange:360
shootDelay:15
[turret_barrel]
x:0
y:0
barrelX:-14
projectile:1
invisible:true
turnSpeed:3
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.2
shoot_flame:small
shoot_light: #FFff00
canShoot:true
recoilOffset: -1
recoilOutTime: 6
recoilReturnTime: 7
#idleSweepAddRandomAngle:40
canAttackLandUnits:false
[turret_barrel2]
x:0
y:0
barrelX:14
projectile:1
invisible:true
turnSpeed:2
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.2
shoot_flame:small
shoot_light: #FFff00
canShoot:true

#idleSweepAddRandomAngle:40
slave:true
attachedTo:barrel
canAttackLandUnits:false
[turret_233]
x:0
y:0
projectile:2
invisible:true
turnSpeed:1
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.5
shoot_flame:small
shoot_light: #FFff00
canShoot:true

#idleSweepAddRandomAngle:40

canAttackLandUnits:true
canAttackFlyingUnits:false
delay:30
limitingRange:130
[turret_gating]
image:smmtur.png
x:0
y:0
projectile:3
turnSpeed:7
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:0.3
shoot_light: #FFff00
canShoot:true
idleSweepAddRandomAngle:40
canAttackLandUnits:true
canAttackFlyingUnits:true
delay:4
limitingRange:200
canAttackCondition: if not self.flying
onShoot_freezeBodyMovementFor:1s
[projectile_1]
directDamage:300
teamColorRatio:1
image:ROOT:/unit/steam.png
life:40
speed:30
frame:1
drawSize:0.8
lightColor: #00fbff
lightSize:1
tags:steam
explodeEffect: CUSTOM:lightSlowFade
[projectile_2]
directDamage:150
teamColorRatio:1
image:ROOT:/unit/mic.png
life:60
speed:10
frame:1
drawSize:0.7
lightColor: #ff7300
lightSize:1
tags:steam
explodeEffect: CUSTOM:lightSlowFade
[projectile_3]
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true
directDamage:80
image:ROOT:/unit/pj2.png
life:60
speed:18
frame:1
drawSize:0.3
lightColor: #bbff00
lightSize:1
tags:steam
[effect_lightSlowFade]
image: SHARED:light_50.png
life:40
fadeOut:true
attachedToUnit: true
color: #00ccff
scaleFrom:0.7
scaleTo:0.2
alpha:0.5
[movement]
movementType:AIR
moveSpeed:2.5
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
maxTurnSpeed:2
turnAcceleration:0.5
landOnGround:true
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.1
maxGlobal:80