[core]
name:wasp
displayText:歼击机
class: CustomUnitMetadata
price:红宝石=1000
maxHp:880
mass:30
techLevel:1
buildSpeed:0.001
availableInDemo: false
radius:10

isBio:false
isBuilder:false

tags:drone
showActionsWithMixedSelectionIfOtherUnitsHaveTag:drone
energyMax:20
energyRegen:0.1
energyNeedsToRechargeToFull:true
[graphics]
total_frames:2
image:wasp.png
icon_zoomed_out:ROOT:icon/drone.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:30
shadowOffsetX:1
shadowOffsetY:1
#lock_body_rotation_with_main_turret:true
animation_moving_start:1
animation_moving_end:1
animation_moving_speed:1
animation_idle_start:0
animation_idle_end:0
movementEffect:dust
movementEffectRate:5
[attack]
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
canAttack:true
maxAttackRange:100
shootDelay:1

attackMovement:bomber
isMelee:true
[turret_barrel]
x:0
y:0
barrelX:12
barrelOffsetX_onOddShots:-24
barrelY:10
projectile:1
invisible:true
turnSpeed:5
turnSpeedAcceleration:1
shoot_sound:plasma_fire
shoot_sound_vol:1
#shoot_flame:small
shoot_light: #aeff00
canShoot:true
recoilOffset: -1
recoilOutTime: 3
recoilReturnTime: 4
energyUsage:1
[projectile_1]
#turnSpeed:0.5
#turnSpeedWhenNear:0
retargetingInFlight:true
directDamage:50

image:ROOT:/unit/pj2.png
life:60
speed:10
frame:1
drawSize:0.3
lightColor: #ff8142
lightSize:0.5
tags:steam
explodeEffect: CUSTOM:lightSlowFade
[effect_lightSlowFade]
image: SHARED:light_50.png
life:20
fadeOut:true
attachedToUnit: true
color: #ffe100
scaleFrom:0.5
scaleTo:0.1
alpha:0.5
[movement]
movementType:AIR
moveSpeed:4.3
moveAccelerationSpeed:0.05
moveDecelerationSpeed:0.005
maxTurnSpeed:3.5
turnAcceleration:1
moveSlidingMode:true
landOnGround:true
slowDeathFall: true
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02
noneGlobalExtraPriority:0.1
maxGlobal:80

[effect_dust]
#color: #d9ff00
delayedStartTimerRandom:10
image:jet.png
life:20
scaleFrom:0.8
scaleTo:1
priority:critical
alpha:1
ySpeedRelative:-1
xSpeedRelativeRandom:0.4
ySpeedRelativeRandom:0.2
yOffsetRelative:-20
#dirSpeedRandom:5
#dirSpeed:1.5
#attachedToUnit:true