[core]
copyFrom:ROOT:RW_Engine/View/View.md

name:TextViewUnit
showInEditor:false
isUnselectable:true
@memory slotId:number
@memory fontsScale:number
@memory fontUnit:unit
@memory char:string


@memory FontMode:number
updateUnitMemory:fontsScale=self.customTarget1.readUnitMemory("textScale",type="number"),fontUnit=self.attachment(slot="Font")
updateUnitMemoryRate:0



[attachment_Font]
x:0
y:0
#isUnselectable:false


[hiddenAction_created]
autoTriggerOnEvent:created
resetCustomTimer:true
sendMessageTo:self.customTarget1
sendMessageWithTags:addTextViewUnitToEpoll
setUnitMemory:fontMode=2,fontsScale=${defaultFontScale}
switchToTeam:self.customTarget1.teamId

[hiddenAction_setSoltId]
autoTriggerOnEvent:newMessage(withTag="setSoltId")
setUnitMemory:slotId=eventData("slotId",type="number")
#,setSoltIdX=self.customTarget1.x+memory.soltSize*memory.slotId,setSoltIdY=self.customTarget1.y+memory.soltSize*eventData("column",type="number")
teleportTo:eventData("position",type="unit")
#createMarker(x=memory.setSoltIdX,y=memory.setSoltIdY)

#sendMessageTo:memory.fontUnit
#sendMessageWithTags:refreshLocation

[hiddenAction_setChar]
autoTriggerOnEvent:newMessage(withTag="setChar")
requireConditional:if memory.char!=eventData("char",type="string")

setUnitMemory:char=eventData("char",type="string")

switchToTeam:select(self.teamId != self.customTarget1.readUnitMemory("defaultTextColor",type="number"),self.teamId,eventData("color",type="number"))


attachments_deleteNumUnits:1
alsoTriggerAction:spawnFontsUnit-better

[hiddenAction_spawnFontsUnit-better]
requireConditional:if memory.FontMode==2
attachments_addNewUnits:spawnFontsUnit-1-better
attachments_onlyOnSlots:Font




#--------已弃用------#
[hiddenAction_setFontUnit]
autoTriggerOnEvent:newMessage(withTag="setFontUnit")
setUnitMemory:fontUnit=eventSource
#通知父物体已经显示完成
sendMessageTo:self.customTarget1
sendMessageWithTags:settingCharSucceed

#设置该char颜色
[hiddenAction_setCharColor]
autoTriggerOnEvent:newMessage(withTag="setCharColor")
switchToTeam:eventData("color",type="number")
sendMessageTo:memory.fontUnit
sendMessageWithTags:setCharColor

[hiddenAction_setFontMode]
autoTriggerOnEvent:newMessage(withTag="setFontMode")

setUnitMemory:fontMode=eventData("fontMode",type="number")

[turret_base]
#
x: 0
y: 0
canShoot:false


