[core]
name:3turM1
displayText:大型空间导弹炮台
displayDescription:emm\n-射程7格\n-消耗2位电力
class:CustomUnitMetadata
price:红宝石=2200
maxHp:15700
borrowResourcesWhileAlive:电力=2

techLevel:1
buildSpeed:0.001
constructionFootprint:-1,-1,1,1
footprint: -1,-1,1,1
availableInDemo:true
radius:45
isBio:false
isBuilding:true
explodeTypeOnDeath:building
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,tur
mass:1000
energyMax:3
energyRegen:0.01
energyNeedsToRechargeToFull: true 
energyRegenWhenRecharging:0.05
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:350
shootDelay:10
setMainTurretAs:1
[effect_projectileTrail]
image:TRAL4.png
life:60
fadeOut: true
attachedToUnit: false

fadeInTime:10
scaleFrom: 1
scaleTo: 0.1
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

total_frames:4
animateFrameStart:0
animateFrameEnd:3
animateFrameSpeed:0.1



[turret_1]
energyUsage:1
barrelOffsetX_onOddShots:-10
barrelX:5
barrelY:22
image:3mistur.png
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:0.6
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:1
recoilOffset: -7
recoilOutTime:2
recoilReturnTime:10
shoot_flame:large
[turret_2]
energyUsage:1
barrelY:22
shoot_flame:large
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:0.6
x:0
y:0
projectile:1
warmup:5
attachedTo:1
slave:true
recoilOffset: -7
recoilOutTime:2
recoilReturnTime:10
[projectile_1]
autoTargetingOnDeadTarget:true

#turnSpeedWhenNear:8
initialUnguidedSpeedY:0

directDamage:400
areaDamage:300
areaRadius:50
life:640
speed:1.5
targetSpeed:10
targetSpeedAcceleration:0.1
frame:1
drawSize:0.8
trailEffect:projectileTrail
trailEffectRate:2.5
lightSize:1.5
lightColor: #f2ff00
image:mis_pj2.png
largeHitEffect:true
#explodeEffect:
deflectionPower:5


[graphics]
turretImageScale:0.8
total_frames:2
icon_zoomed_out:ROOT:icon/tur.png
image:simbs3.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:60
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.005
noneInBaseExtraPriority:0.02

[movement]
movementType:HOVER

[decal_sctC]
image:ROOT:/tur_sct.png
onlyWhileActive:true
alwaysStartDirAtZero:true
onlyWhenSelectedByOwnPlayer:true
imageScale:1.2
teamColors:true
order:2
alpha:0.3
