
[core]
copyFrom:ROOT:tmp/turret.template
name:misTurH2
displayText:重型导弹发射台
displayDescription:-更远的射程和更大的威力\n-射程15格\n-消耗4位电力
class:CustomUnitMetadata
price:红宝石=2400
maxHp:3500
borrowResourcesWhileAlive:电力=4

techLevel:1
buildSpeed:0.0015

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:300
shootDelay:40
setMainTurretAs:1
[turret_1]
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:0.8
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:1
canAttackMaxAngle:181
warmup:10
chargeEffectImage:mis_pj.png

[projectile_1]
autoTargetingOnDeadTarget:true
ballistic:true
ballistic_delaymove_height:22
ballistic_height:50

#turnSpeedWhenNear:8
initialUnguidedSpeedY:0

directDamage:450
life:480
speed:1.8
frame:1
drawSize:0.8
trailEffect:projectileTrail
trailEffectRate:2.5
lightSize:1.5
lightColor: #f2ff00
image:mis_pj.png
#explodeEffect:
deflectionPower:5
[graphics]
icon_zoomed_out:ROOT:icon/tur.png
image:misbs-H.png
total_frames:2
image_shadow:AUTO
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
shadowOffsetX:1
[ai]
buildPriority:0.015
noneInBaseExtraPriority:0.02
upgradedFrom:staTur1
ai_upgradePriority:0.01
[movement]
movementType:HOVER

[effect_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false
[effect_projectileTrail]
image:TRAL4.png
life:60
fadeOut: true
attachedToUnit: false

fadeInTime:10
scaleFrom: 1
scaleTo: 0.1
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

total_frames:4
animateFrameStart:0
animateFrameEnd:3
animateFrameSpeed:0.1

[action_updt2]
buildSpeed:23s
text:升级-重型T2
price:红宝石=3600
displayType:upgrade
unitShownInUI:misTurH3
allowMultipleInQueue:false
convertTo:misTurH3
ai_isHighPriority:true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH3', greaterThan=0))
isLockedMessage:升级基地解锁新科技!