
[core]
copyFrom:ROOT:tmp/turret.template
name:misTra
displayText:追迹导弹发射台
displayDescription:-发射射程极远的重型导弹\n-可以瞬间瘫痪一个激光拦截器(消耗1000能量拦截)\n-6秒1发\n-射程40格\n-消耗10位电力
class:CustomUnitMetadata
price:红宝石=10000
maxHp:10000
borrowResourcesWhileAlive:电力=10

techLevel:1
buildSpeed:0.0015
energyMax:360
energyRegen:1
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:800
shootDelay:300
setMainTurretAs:1
[turret_1]
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:2
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:1
canAttackMaxAngle:181
energyUsage:360
warmup:20
chargeEffectImage:mis_pjt.png

[projectile_1]
turnSpeed:2
autoTargetingOnDeadTarget:true
ballistic:true
ballistic_delaymove_height:40
ballistic_height:80

#turnSpeedWhenNear:8
initialUnguidedSpeedY:0

directDamage:600
areaDamage:1200
areaRadius:80
life:3000

speed:2
targetSpeed:8
targetSpeedAcceleration:0.05

frame:1
drawSize:1
trailEffect:projectileTrail
trailEffectRate:3
lightSize:1.5
lightColor: #006eff
image:mis_pjt.png
largeHitEffect:true
#explodeEffect:
deflectionPower:100
[graphics]
icon_zoomed_out:ROOT:icon/tur.png
image:misbs-trail.png
total_frames:2
image_shadow:AUTO
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
shadowOffsetX:1
[ai]
buildPriority:0.015
noneInBaseExtraPriority:0.02
upgradedFrom:staTur1
ai_upgradePriority:0.01
[movement]
movementType:HOVER

[effect_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false
[effect_projectileTrail]
image:TRAL8.png
life:60
fadeOut: true
attachedToUnit: false

fadeInTime:10
scaleFrom: 2
scaleTo: 0.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.3
[action_updt2]
buildSpeed:60s
text:升级-T2
price:红宝石=15000
displayType:upgrade
unitShownInUI:misTra2
allowMultipleInQueue:false
convertTo:misTra2
ai_isHighPriority:true
isLocked:if not (numberOfUnitsInTeam(withTag='TECH4', greaterThan=0))
isLockedMessage:升级基地解锁新科技!