
[core]
copyFrom:ROOT:tmp/turret.template
name:misTra2
displayText:追迹导弹发射台T2
displayDescription:-发射射程极远的重型导弹\n-可以瞬间瘫痪一个激光拦截器(消耗150能量拦截)\n-8秒1发\n-射程60格\n-消耗18位电力
class:CustomUnitMetadata
price:红宝石=30000
maxHp:12000
borrowResourcesWhileAlive:电力=18

techLevel:1
buildSpeed:0.0015
energyMax:960
energyRegen:1
maxShield:10000
shieldRegen:2
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:1200
shootDelay:60
setMainTurretAs:1
[turret_1]
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:2
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:1
canAttackMaxAngle:181
energyUsage:480
[projectile_1]
turnSpeed:10
autoTargetingOnDeadTarget:true
ballistic:true
ballistic_delaymove_height:40
ballistic_height:80

#turnSpeedWhenNear:8
initialUnguidedSpeedY:0

directDamage:2000
areaDamage:1800
areaRadius:100
life:3000

speed:3
targetSpeed:16
targetSpeedAcceleration:0.05

frame:1
drawSize:1
trailEffect:projectileTrail
trailEffectRate:3
lightSize:1.5
lightColor: #006eff
image:mis_pjt.png
largeHitEffect:true
#explodeEffect:
deflectionPower:150
[graphics]
icon_zoomed_out:ROOT:icon/tur.png
image:misbs-trail2.png
total_frames:2
image_shadow:AUTO
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
shadowOffsetX:1
image_shield:ROOT:shs.png
[ai]
buildPriority:0.015
noneInBaseExtraPriority:0.02
upgradedFrom:staTur1
ai_upgradePriority:0.01
[movement]
movementType:HOVER

[effect_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false
[effect_projectileTrail]
image:TRAL8.png
life:60
fadeOut: true
attachedToUnit: false

fadeInTime:10
scaleFrom: 2
scaleTo: 0.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

total_frames:8
animateFrameStart:0
animateFrameEnd:7
animateFrameSpeed:0.3