[core]
copyFrom:ROOT:tmp/turret.template
name:misTur1
displayText:导弹发射台
displayDescription:-好吧原版其实没有这个东西/n-射程11格/n-消耗2位电力
class:CustomUnitMetadata
price:红宝石=1000
maxHp:2300
borrowResourcesWhileAlive:电力=2

techLevel:1
buildSpeed:0.0015

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:220
shootDelay:30
setMainTurretAs:1
[turret_1]
canAttackCondition:if self.resource.电力>0
shoot_sound:missile_fire
shoot_sound_vol:0.6
x:0
y:0
projectile:1
turnSpeed:1
turnSpeedAcceleration:1
canAttackMaxAngle:181

[projectile_1]
autoTargetingOnDeadTarget:true
ballistic:true
ballistic_delaymove_height:5
ballistic_height:20
turnSpeed:12
turnSpeedWhenNear:8
initialUnguidedSpeedY:3
directDamage:140
life:120
speed:6
frame:1
drawSize:0.5
trailEffect:projectileTrail
trailEffectRate:8
lightSize:1
image:mis_pj.png
#explodeEffect:
deflectionPower:3
[graphics]

total_frames:2
icon_zoomed_out:ROOT:icon/tur.png
image:misbs.png
shadow:true
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
imageShadow:AUTO_ANIMATED
shadowOffsetX:1
shadowOffsetY:1
[ai]
buildPriority:0.1
maxEachBase:20
recommendedInEachBaseNum:8


[movement]
movementType:HOVER


[effect_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false
[effect_projectileTrail]
image:TRAL4.png
life:120
fadeOut: true
attachedToUnit: false

fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
#ySpeedRelative:-1
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

total_frames:3
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:0.2