[core]
copyFrom:ROOT:tmp/turret.template
name:staTur1
displayText:空间站炮台
displayDescription:-好吧原版其实没有这个东西/n-射程6.5格/n-消耗1位电力
class:CustomUnitMetadata
price:红宝石=600
maxHp:2000
borrowResourcesWhileAlive:电力=1

techLevel:1
buildSpeed:0.002

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:150
shootDelay:18
setMainTurretAs:1
[turret_1]
canAttackCondition:if self.resource.电力>0
shoot_sound:gun_fire
shoot_sound_vol:0.6
x:0
image:tura.png
y:0
projectile:1
turnSpeed:10
turnSpeedAcceleration:1
idleSweepAngle:30
idleSweepDelay:45
idleSweepSpeed:1
idleSweepAddRandomAngle:30
idleSweepAddRandomDelay:40

[projectile_1]
#弹道效果
turnSpeed:0
turnSpeedWhenNear:0
retargetingInFlight:true

directDamage:140
life:70
speed:10
frame:1
drawSize:0.7
teamColorRatio:1
image:ROOT:/unit/steam.png
[graphics]
turretImageScale:0.5
total_frames:2
icon_zoomed_out:ROOT:icon/tur.png
image:simbs.png
image_shadow:AUTO
shadowOffsetX:1
scaleImagesTo:40
animation_idle_start:0
animation_idle_end:1
shadowOffsetY:1
[ai]
buildPriority:0.04
noneInBaseExtraPriority:0.03
noneGlobalExtraPriority:0.03
[movement]
movementType:HOVER

[action_updt1]
buildSpeed:16.6s
text:升级-T2机炮
price:红宝石=1200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staTur2
allowMultipleInQueue:false
convertTo:staTur2
[action_updt2]
buildSpeed:10s
text:升级-双管炮
price:红宝石=1000
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staTur2
allowMultipleInQueue:false
convertTo:staTTur2
[action_updt3]
buildSpeed:23.3s
text:升级-T2激光炮
price:红宝石=1200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staLTur2
allowMultipleInQueue:false
convertTo:staLTur2
[action_updt4]
buildSpeed:23.3s
text:升级-T2火炮
price:红宝石=2200
displayType:upgrade
isLocked:if not (numberOfUnitsInTeam(withTag='TECH2', greaterThan=0))
isLockedMessage:升级基地解锁新科技!
unitShownInUI:staRTur2
allowMultipleInQueue:false
convertTo:staRTur2