[core]
name:Touch
class:CustomUnitMetadata
tags:Touch
price:0
maxHp:1
mass:0
buildSpeed:0
radius:0
isBio:false
canNotBeDirectlyAttacked: true
canNotBeDamaged:true
autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true

[graphics]
total_frames:1
image:ROOT:RW_Engine/View/空.png
image_wreak:NONE
image_turret:NONE
imageSmoothing:true
drawLayer:top
[hiddenAction_commonRequest]
autoTriggerOnEvent:created
resetCustomTimer:true
sendMessageTo:self.customTarget1
sendMessageWithTags:commonRequest
sendMessageWithData:name="${core.name}",tags="${core.tags}"



[arm_13]
x:0
y:0
draw_foot_on_top: false
drawUnderAllUnits:true
lockMovement:true
image_end:Touch.png
drawDirOffset:-90


[hiddenAction_Move]
autoTriggerOnEvent:newWaypointGivenByPlayer
teleportTo:createMarker(x=activeWaypointTarget.x,y=activeWaypointTarget.y)
fireTurretXAtGround:base
fireTurretXAtGround_withProjectile:Touch
fireTurretXAtGround_withTarget:createMarker(x=activeWaypointTarget.x,y=activeWaypointTarget.y)

#setUnitMemory:

[attack]

canAttack:false



[turret_base]
#
x: 0
y: 0
canShoot:false

[projectile_Touch]
directDamage: 0
life: 100
speed: 7
tags:Touch
frame:11
drawSize: 0
explodeEffect:NONE
friendlyFire:true
areaDamage:1
areaRadius:10
areaDamageNoFalloff:true
areaHitAirAndLandAtSameTime:true
areaRadiusFromEdge:true
instant:true


[movement]
movementType:NONE

moveSpeed:0.0
maxTurnSpeed:0.0

