[core]
copyFrom:ROOT:RW_Engine/View/StaticViews/Button/Button-static.md
name:Button-staticExample
tags:Button-staticExample

[hiddenAction_addLTVSystemToEpollSucceed]
#tags相当于函数名，Data中的text为参数
setUnitMemory:text="点击qwq"
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setText
sendMessageWithData:text=memory.text
alsoTriggerAction:initLayoutView

[hiddenAction_Touch]
autoTriggerOnEvent:tookDamage(withTag="Touch")

sendMessageTo:memory.LTVSystem
sendMessageWithTags:setText
sendMessageWithData:text="别碰我www"
setUnitMemory:text="别碰我www"
alsoTriggerAction:initLayoutView
