[core]
name:LineTextViewExample
class:CustomUnitMetadata
price:0
maxHp:1
mass:0
buildSpeed:0
isBuilding: true
radius:0
stayNeutral:true
isBio:false
showOnMinimap:false
canNotBeDirectlyAttacked: true
canNotBeDamaged:true
autoTriggerCooldownTime:0.0s
autoTriggerCooldownTime_allowDangerousHighCPU:true

@memory LTVSystem:unit

[hiddenAction_created]
autoTriggerOnEvent:created
resetCustomTimer:true

#创建文本框
spawnUnits:LineTextViewSystem

#文本框会自动发送tag为addLTVSystemToEpoll给该单位
[hiddenAction_addLTVSystemToEpoll]
autoTriggerOnEvent:newMessage(withTag="addLTVSystemToEpoll")
setUnitMemory:LTVSystem = eventSource

#tags相当于函数名，Data中的text为参数
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setText
sendMessageWithData:text="十山月是摸鱼小能手"

[action_setTextColorTest]
text:setTextColorTest
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setTextColor
sendMessageWithData:color=3,indexStart=0,indexEnd=3,commonHeadLength=1



[action_setTextSize1]
text:setTextSize-小
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setTextScale

sendMessageWithData:textScale=memory.LTVSystem.readUnitMemory("textScale",type="number")-0.5


[action_setTextSize2]
text:setTextSize-大
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setTextScale

sendMessageWithData:textScale=memory.LTVSystem.readUnitMemory("textScale",type="number")+0.5
[action_setTextSize3]
text:setTextSize-间隔-大
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setTextMarginLeft
sendMessageWithData:marginLeft=memory.LTVSystem.readUnitMemory("textMarginLeft",type="number")+10
[action_setTextSize4]
text:setTextSize-间隔-小
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setTextMarginLeft
sendMessageWithData:marginLeft=memory.LTVSystem.readUnitMemory("textMarginLeft",type="number")-10

[action_setTextTest]
text:setText
isVisible:true
sendMessageTo:memory.LTVSystem
sendMessageWithTags:setText
sendMessageWithData:text="warma"
[graphics]
total_frames:1
image:ROOT:RW_Engine/View/空.png
image_wreak:NONE
image_turret:NONE
imageSmoothing:true

[attack]

canAttack:false

[movement]
movementType:NONE
