[core]
name:allaserEmit
displayText:复合激光发生器
displayDescription:-耗电20kW\n OUTPUT 24eps
maxHp:2600
price:红宝石=500,crystal=10
shieldDisplayOnlyDeflection:true
borrowResourcesWhileAlive:电力=20
mass:1000
radius:10
constructionFootprint:0,1,0,1
footprint:0,1,0,1
buildingToFootprintOffsetY:20
isBuilding:true
tags:emit
energyMax:24
#energyRegen:0.05
generation_resources:energy=2
generation_active:if self.resource.电力>0 
generation_delay:5
startEnergyAtZero: true
[graphics]
scaleImagesTo:20
image:allaserEmit.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0
[ai]
ai_upgradePriority:0.8
[decal_line]
lineWidth:5
yOffsetRelative:15
alpha:self.energy/24
color: #ffff10
drawLineTo:nearestUnit(withTag="LP",withinRange=250)
#.getOffsetAbsolute(-19,-7)
[decal_line2]

lineWidth:2
yOffsetRelative:15
alpha:self.energy/4
color: #ffff50
drawLineTo:nearestUnit(withTag="LP",withinRange=250)
#.getOffsetAbsolute(-19,-7)
layer: BEFOREUI
[decal_glow]
imageScale:4
image:laserEmitGlow.png
alpha:self.energy/48
yOffsetRelative:15
color:#00ff00
layer: BEFOREUI
[hiddenAction_input2]
autoTrigger:if self.isEnergyFull() and nearestUnit(withTag="lsi",withinRange=200) != null and not nearestUnit(withTag="lsi",withinRange=200).isEnergyFull()
takeResources_excludeUnitsWithoutTags:lsi
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-24
addResources:energy=-24
takeResources_includeReference:nearestUnit(withTag="lsi",withinRange=250)
#takeResources_includeUnitsWithinRange:200