[core]
name:calCon
displayText:元件机箱
displayDescription:-维护4格内的元件台
class:CustomUnitMetadata
price:红宝石=1200
maxHp:1500
#borrowResourcesWhileAlive:电力=6
mass:100
footprint: 0,0,1,1
constructionFootprint:0,0,1,1
buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
radius:20
buildingSelectionOffset: -8
techLevel:1
buildSpeed:0.001
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
#generation_resources:dust=-3,iron=1
#generation_delay:40
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,eunit,tabCon
unitsSpawnedOnDeath:Eboom
[attack]
canAttack:false
[graphics]
total_frames:1
scaleImagesTo:40
icon_zoomed_out:ROOT:icon/pdc.png
image:calController.png
image_wreak:NONE
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

[ai]
buildPriority:0.003
noneInBaseExtraPriority:0.003
noneGlobalExtraPriority:0.002
recommendedInEachBaseNum:3
[movement]
movementType:HOVER