[core]
name:laserEle
displayText:激光同位素分离室
displayDescription:-需要外部波束源
class:CustomUnitMetadata
price:iron=1200,红宝石=6000,S=500,crystal=80,heac=100
maxHp:3500
#borrowResourcesWhileAlive:电力=6
mass:100
footprint:-1,0,1,1
constructionFootprint:-1,0,1,1
buildingToFootprintOffsetY:20
radius:30
buildingSelectionOffset: -8
techLevel:1
buildSpeed:32s
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
generation_resources:iron=-10,rad=5,energy=-50
generation_active:if self.resource.iron>10 and self.energy>50
generation_delay:40
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,highValue,lsi
unitsSpawnedOnDeath:Eboom
energyMax:500
energyRegen:0
startEnergyAtZero: true
[attack]
canAttack:false
[graphics]
total_frames:1
scaleImagesTo:60
icon_zoomed_out:ROOT:icon/pdc.png
image:laserEle.png
image_wreak:NONE
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1

[ai]
buildPriority:0.001
noneGlobalExtraPriority:0.002
[movement]
movementType:HOVER

[decal_glow]
image:laserEleGlow.png
imageScale:0.625
alpha: self.energy /500
[effect_dust]
delayedStartTimerRandom:45
image:datadot.png
life:40
scaleFrom:0.2
scaleTo:0.6
priority:critical
alpha:1
xSpeedAbsoluteRandom:3
ySpeedAbsoluteRandom:3
hSpeedRandom:0.5
hSpeed:1
dirSpeedRandom:0.5
dirSpeed:1
[animation_dust]
onActions:idle
effect_2s:{x:0,y:2,name:dust*1}

[attachment_lp]
x:-19
y:7
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:false
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:lsinput