[core]
name:laserSTO
#relay or sto?
displayText:激光中继器
displayDescription:-仅支持点对点 可以串联(不要尝试弄出一个环 这样非常消耗性能)\n带宽 25e/0.1s(250eps)\n最大连接距离 275px\n缓存容量 50e
maxHp:1600
price:红宝石=500,crystal=10
shieldDisplayOnlyDeflection:true
#borrowResourcesWhileAlive:电力=5
mass:1000
radius:20
constructionFootprint:0,1,0,1
footprint:0,1,0,1
buildingToFootprintOffsetY:20
isBuilding:true
tags:sto,lsi
energyMax:50
#energyRegen:0.05
startEnergyAtZero: true
transportUnitsRequireTag:marker
maxTransportingUnits:1
transportUnitsAddUnloadOption: false
@memory alt:number
autoTriggerCooldownTime:0.1s
[graphics]
scaleImagesTo:20
image:lsrelay.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
showTransportBar:false
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:275
[turret_select]
turnSpeed:16
x:0
y:0
projectile:sel
canShoot:false
[projectile_sel]
life:60
directDamage:114514
speed:25
targetGround:true
unloadUpToXUnitsFromSource:1
#instant:true
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0
[ai]
ai_upgradePriority:0.8
[hiddenAction_0]

[decal_glow]
layer: BEFOREUI
imageScale:2
image:laserEmitGlow.png
alpha:self.energy/75
color:#aaffaa
yOffsetRelative:15
[attachment_lp]
x:0
y:15
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:false
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:lsinput
[decal_line]
layer: BEFOREUI
lineWidth:5
yOffsetRelative:15
alpha:self.energy/50
color: #ff810b
drawLineTo:customTarget1.attachment
#.getOffsetAbsolute(-19,-7)
[decal_line2]
layer: BEFOREUI
lineWidth:2
yOffsetRelative:15
alpha:self.energy/50
 #to float
color: #ffdd8e
drawLineTo:customTarget1.attachment
#.getOffsetAbsolute(-19,-7)
[decal_lineSign]
lineWidth:1
yOffsetRelative:15
alpha:0.5
color: #ffffff
drawLineTo:customTarget1.attachment
[hiddenAction_input2]
autoTrigger:if self.energy>=25 and customTarget1 != null and not customTarget1.isEnergyFull()
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-25
addResources:energy=-25
takeResources_includeReference:customTarget1
#takeResources_includeUnitsWithinRange:200
[action_select]
addUnitsIntoTransport:Marker*1
text:选择输出目标
fireTurretXAtGround: select
fireTurretXAtGround_showGuideDecals:target
description:select
displayType: action
buildSpeed: 0s
pos: 0
highPriorityQueue: true
onlyOneUnitAtATime:false
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
setCustomTarget2:transporting(slot=0)
[decal_target]

alpha:0.8
isVisible:false
image:SHARED:icon_attack_point.png
[hiddenAction_inp]
autoTriggerOnEvent:newMessage
setCustomTarget1:customTarget2.readUnitMemory('tar',type='unit')
#卧槽我当时怎么想到的 我真TM是个甜菜😋
[decal_tar]
layer: BEFOREUI
onlyWhenSelectedByAnyPlayer:true
image:55sel.png
imageScale:10
xOffsetAbsolute:customTarget1.x-self.x
yOffsetAbsolute:customTarget1.y-self.y
[hiddenAction_init]
autoTriggerOnEvent:created
setUnitMemory:alt=0