[core]
name:laserOVF
#relay or sto?
displayText:激光溢流门
displayDescription:500eps
maxHp:1600
price:红宝石=500,crystal=10
shieldDisplayOnlyDeflection:true
mass:1000
radius:20
constructionFootprint:0,0,1,1
footprint:0,0,1,1
buildingToFootprintOffsetY:20
buildingToFootprintOffsetX:20
isBuilding:true
tags:sto,lsi
energyMax:100
#energyRegen:0.05
startEnergyAtZero: true
transportUnitsRequireTag:marker
maxTransportingUnits:1
transportUnitsAddUnloadOption: false
@memory probe:unit
@memory buffer:bool
@memory alt:number
@memory return:unit
#石山代码
autoTriggerCooldownTime:0.1s
[graphics]
scaleImagesTo:40
image:lsOVF.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
showTransportBar:false
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:200
[turret_select]
turnSpeed:16
x:0
y:0
projectile:sel
canShoot:false
[projectile_sel]
life:60
directDamage:114514
speed:25
targetGround:true
unloadUpToXUnitsFromSource:1
#instant:true
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0
[ai]
ai_upgradePriority:0.8
[hiddenAction_0]

[decal_glow]
imageScale:1.5
image:laserSTOGlow.png
alpha:self.energy/100

[attachment_lp]
x:0
y:7.5
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:false
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:lsinput
[decal_line]
layer: BEFOREUI
lineWidth:1
yOffsetRelative:-7.5
xOffsetRelative:-7
alpha:self.energy/100
color: #ff810b
drawLineTo:customTarget1.attachment
#.getOffsetAbsolute(-19,-7)
[decal_linea]
xOffsetRelative:7
@copyFromSection: decal_line
drawLineTo:customTarget2.attachment
color: #ffdd8e
[decal_lineSign1]
lineWidth:1
yOffsetRelative:-7.5
xOffsetRelative:-7
alpha:0.5
color: #ffffff
drawLineTo:customTarget1.attachment
[decal_lineSign2]
lineWidth:1
yOffsetRelative:-7.5
xOffsetRelative:7
alpha:0.3
color: #ffff00
drawLineTo:customTarget2.attachment
[hiddenAction_input2]
autoTrigger:if self.energy>50 and customTarget1 != null and not customTarget1.isEnergyFull()
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-50
addResources:energy=-50
takeResources_includeReference:customTarget1
#takeResources_includeUnitsWithinRange:200
[hiddenAction_input3]
autoTrigger:if self.energy>25 and customTarget2 != null and not customTarget2.isEnergyFull() and customTarget1.isEnergyFull()
#keepFull when trans happen 
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-50
addResources:energy=-50
takeResources_includeReference:customTarget2
#takeResources_includeUnitsWithinRange:200
[action_select0]
addUnitsIntoTransport:Marker*1
text:选择优先输出目标
isLocked:if memory.buffer==true
fireTurretXAtGround: select
fireTurretXAtGround_showGuideDecals:target
description:select
displayType: action
buildSpeed: 0s
pos: 0
highPriorityQueue: true
onlyOneUnitAtATime:false
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
setUnitMemory:probe=transporting(slot=0),alt=-1,buffer=true
[action_select1]
addUnitsIntoTransport:Marker*1
text:选择次级输出目标
isLocked:if memory.buffer==true
fireTurretXAtGround: select
fireTurretXAtGround_showGuideDecals:target
description:select
displayType: action
buildSpeed: 0s
pos: 0
highPriorityQueue: true
onlyOneUnitAtATime:false
#isAlsoViewableByEnemies: true
iconImage: SHARED:icon_attack_point.png
aiUse: launch
setUnitMemory:probe=transporting(slot=0),alt=1,buffer=true
[decal_target]
alpha:0.8
isVisible:false
image:SHARED:icon_attack_point.png
[hiddenAction_inp]
autoTriggerOnEvent:newMessage
setUnitMemory:return=memory.probe.readUnitMemory('tar',type='unit')
alsoTriggerAction:selBe
[hiddenAction_selBe]

setCustomTarget1:select(memory.alt==-1,memory.return,customTarget1)
setCustomTarget2:select(memory.alt==1,memory.return,customTarget2)
setUnitMemory:buffer=false
#,return=null,alt=0
[decal_tar]
layer: BEFOREUI
onlyWhenSelectedByAnyPlayer:true
image:55sel.png
imageScale:10
xOffsetAbsolute:customTarget1.x-self.x
yOffsetAbsolute:customTarget1.y-self.y
[decal_tar1]
layer: BEFOREUI
color:#ff0000
onlyWhenSelectedByAnyPlayer:true
image:55sel.png
imageScale:10
xOffsetAbsolute:customTarget2.x-self.x
yOffsetAbsolute:customTarget2.y-self.y