[core]
name:laserEmit
displayText:光电激光发生器
displayDescription:-耗电5kW
maxHp:1600
price:红宝石=500,crystal=10
shieldDisplayOnlyDeflection:true
borrowResourcesWhileAlive:电力=5
mass:1000
radius:10
constructionFootprint:0,0,0,1
footprint:0,1,0,1
buildingToFootprintOffsetY:20
isBuilding:true
tags:emit
energyMax:4
#energyRegen:0.05
generation_resources:energy=0.08
generation_active:if self.resource.电力>0 
generation_delay:5
startEnergyAtZero: true
[graphics]
scaleImagesTo:20
image:laserEmit.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0
[ai]
ai_upgradePriority:0.8
[hiddenAction_0]

[decal_line]
lineWidth:10
yOffsetRelative:15
alpha:self.energy/4
color: #ff1010
drawLineTo:nearestUnit(withTag="LP",withinRange=200)
#.getOffsetAbsolute(-19,-7)
[decal_line2]
lineWidth:2
yOffsetRelative:15
alpha:self.energy/4
color: #ffd2d2
drawLineTo:nearestUnit(withTag="LP",withinRange=200)
#.getOffsetAbsolute(-19,-7)
[decal_glow]
imageScale:1.5
image:laserEmitGlow.png
alpha:self.energy/4
yOffsetRelative:15

[hiddenAction_input2]
autoTrigger:if self.isEnergyFull() and nearestUnit(withTag="lsi",withinRange=200) != null and not nearestUnit(withTag="lsi",withinRange=200).isEnergyFull()
takeResources_excludeUnitsWithoutTags:lsi
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-4
addResources:energy=-4
takeResources_includeReference:nearestUnit(withTag="lsi",withinRange=200)
#takeResources_includeUnitsWithinRange:200