[core]
name:Marker
displayText:标记
displayDescription:-你他妈怎么看到这段介绍的
# 
showInEditor:false
mass:1
radius:1
tags:marker
@memory tar:unit
@memory alt:number
maxHp:24
selfRegenRate:-0.1
price:1
isUnselectableAsTarget:true
explodeOnDeath:false

[graphics]
isVisible:false
scaleImagesTo:1
image:55sel.png
image_wreak:NONE
image_turret:NONE
image_shadow:NONE
showHealthBar:false
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
canAttack:false
[movement]
movementType:LAND
[hiddenAction_pr]
autoTriggerOnEvent:created
setCustomTarget1:parent
[hiddenAction_connect]
autoTrigger:if (not self.hasParent())
setUnitMemory:tar=nearestUnit(withTag="lsi",withinRange=50)
sendMessageTo:customTarget1

# 这段真的太史了 为了偷懒直接跨单位搞了一坨判断 好孩子别学 (史山代码谁爱学谁学去)
