[core]
name:rlaserEmit
displayText:辐射激光发生器
displayDescription:-不耗电\n OUTPUT 4.8eps
maxHp:1600
price:红宝石=1000,crystal=20,rad=10
shieldDisplayOnlyDeflection:true

mass:1000
radius:10
constructionFootprint:0,1,0,1
footprint:0,1,0,1
buildingToFootprintOffsetY:20
isBuilding:true
tags:emit
energyMax:5
#energyRegen:0.05
generation_resources:energy=0.4
#generation_active:if self.resource.电力 > 0
generation_delay:5
startEnergyAtZero: true
[graphics]
scaleImagesTo:20
image:rlaserEmit.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0
[ai]
ai_upgradePriority:0.8
[hiddenAction_0]

[decal_line]
layer: BEFOREUI
lineWidth:3
yOffsetRelative:15
alpha:self.energy/5
color: #0bf3ff
drawLineTo:nearestUnit(withTag="LP",withinRange=200)
#.getOffsetAbsolute(-19,-7)
[decal_line2]
layer: BEFOREUI
lineWidth:1
yOffsetRelative:15
alpha:self.energy/5
 #to float
color: #88e7ff
drawLineTo:nearestUnit(withTag="LP",withinRange=200)
#.getOffsetAbsolute(-19,-7)
[decal_glow]
imageScale:1.5
image:rlaserEmitGlow.png
alpha:self.energy/5
yOffsetRelative:15

[hiddenAction_input2]
autoTrigger:if self.isEnergyFull() and nearestUnit(withTag="lsi",withinRange=200) != null and not nearestUnit(withTag="lsi",withinRange=200).isEnergyFull()
takeResources_excludeUnitsWithoutTags:lsi
takeResources_includeUnitsWithinRange_team:ally
takeResources_maxUnits:1
takeResources:energy=-5
addResources:energy=-5
takeResources_includeReference:nearestUnit(withTag="lsi",withinRange=200)
#takeResources_includeUnitsWithinRange:200