[core]
name:table
displayText:晶体元件台
displayDescription:-人话就是主板\n-什么?你问运行内存哪来的\n-.....
class:CustomUnitMetadata
price:红宝石=800,crystal=10
maxHp:1000
#borrowResourcesWhileAlive:电力=6
mass:100
footprint: 0,0,1,1
constructionFootprint:0,0,1,1
buildingToFootprintOffsetX:20
buildingToFootprintOffsetY:20
radius:16
buildingSelectionOffset: -8
techLevel:1
buildSpeed:0.001
availableInDemo:true
isBio:false
isBuilding:true
explodeTypeOnDeath:building
#generation_resources:dust=-3,iron=1
#generation_delay:40
explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:sta,eunit
unitsSpawnedOnDeath:Eboom
[attack]
canAttack:false
[graphics]
total_frames:4
scaleImagesTo:30
icon_zoomed_out:ROOT:icon/pdc.png
image:table.png
image_wreak:NONE
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start:0
animation_idle_end:3
[ai]
buildPriority:0.01
noneInBaseExtraPriority:0.01
noneGlobalExtraPriority:0.01
[movement]
movementType:HOVER

[attachment_1]
x:0
y:0
isUnselectable:false
canBeAttackedAndDamaged:false
addTransportedUnits:false
setDrawLayerOnBottom:false
canAttack:true
lockRotation:false
idleDir:0
onCreateSpawnUnitOf:PCB