[core]
createOnAggressiveTeam:true
name:alncore
displayText:aln波次核心
displayDescription:-\n-无法自卫 \n-老巢\+20ele
canOnlyBeAttackedByUnitsWithTags:NONE
class:CustomUnitMetadata
price:红宝石=1145141919810

maxHp:1000000
shieldDisplayOnlyDeflection:true
mass:1000
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
techLevel:1
buildSpeed:120s
nanoFactorySpeed:2

availableInDemo:true
radius:30
displayRadius:30
isBio:false
isBuilding:true
explodeTypeOnDeath:building

#generation_resources:time=1
#generation_delay:40

isPickableStartingUnit:true
startFallingWhenStartingUnit:true

explodeOnDeathGroundCollision:false
explodeOnDeath:false
tags:bs

autoTriggerCheckRate:every8Frames
[canBuild_1]
name:fly
[resource_time]
displayName:waveTime
[resource_time2]
displayName:waveTime2
[attack]
canAttack:false
[graphics]
icon_zoomed_out:ROOT:icon/bs.png
total_frames:1
image:Aicon.png
image_wreak:NONE
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
[movement]
movementType:HOVER

[action_a]
autoTrigger:true
requireConditional:if (self.customTimer >= 1)
isVisible:false
resetCustomTimer:true
showQuickWarLogToAllPlayers:%{self.resource.time}s
addResources:time=1
[action_z]
autoTrigger:if not numberOfUnitsInTeam(withTag='w0',greaterThan=0)
temporarilyAddTags:w0
showMessageToAllPlayers:第1波:绿鸡*50(200秒)
isVisible:false
[action_1]
autoTrigger:if self.hasResources(time=200) and not numberOfUnitsInTeam(withTag='w1',greaterThan=0)
spawnUnits:gc*50
temporarilyAddTags:w1
showMessageToAllPlayers:第2波:黄鸡*25,黄蟹*25(130秒)
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-200
[action_2]
autoTrigger:if self.hasResources(time=130) and not numberOfUnitsInTeam(withTag='w2',greaterThan=0)
spawnUnits:yc*25,yr*25
temporarilyAddTags:w2
showMessageToAllPlayers:第3波:红蟹*15,红鸡*15(150秒)
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-130
[action_3]
autoTrigger:if self.hasResources(time=150) and not numberOfUnitsInTeam(withTag='w3',greaterThan=0)
spawnUnits:rr*15,rc*15
temporarilyAddTags:w3
showMessageToAllPlayers:第4波:黄蟹*80,黄鸡*80(260秒)
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-150
[action_4]
autoTrigger:if self.hasResources(time=260) and not numberOfUnitsInTeam(withTag='w4',greaterThan=0)
spawnUnits:yc*80,yr*80
temporarilyAddTags:w4
showMessageToAllPlayers:第5波:紫蟹*1,紫鸡*1,红蟹*35,红鸡*35(180秒)
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-260
[action_5]
autoTrigger:if self.hasResources(time=180) and not numberOfUnitsInTeam(withTag='w5',greaterThan=0)
spawnUnits:pr*1,pc*1,rr*35,rc*35
temporarilyAddTags:w5
showMessageToAllPlayers:第6波:紫鸡*12,紫蟹*12(300秒)
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-60
[action_6]
autoTrigger:if self.hasResources(time=300) and not numberOfUnitsInTeam(withTag='w6',greaterThan=0)
spawnUnits:pc*12,pr*12
temporarilyAddTags:w6
showMessageToAllPlayers:生存600s!
isVisible:false
playSoundGlobally:ROOT:/land.ogg
addResources:time=-300
[action_7]
autoTrigger:if self.hasResources(time=600) and not numberOfUnitsInTeam(withTag='w7',greaterThan=0)
#spawnUnits:NUKE*1,NUKE2*1
showMessageToAllPlayers:----胜利----
isVisible:false
temporarilyAddTags:w7
playSoundGlobally:ROOT:/land.ogg
addResources:hp=-100000000