[core]
copyFrom:ROOT:RW_Engine/View/View.md,ROOT:RW_Engine/Module/LayoutInterpreter/ImportLayoutInterpreter.md,ROOT:RW_Engine/View/CommonCallBack.md

name:PageTextViewSystem
showInEditor:false
@memory unitEpoll:unit[]
@memory text:string
@memory needInitLTVSystemSoltId:boolean
@memory needNewLTVSystemNum:number
@memory lineFontsNum:number


[hiddenAction_created]
@define initCounts:10
autoTriggerOnEvent:created
resetCustomTimer:true
setUnitMemory:lineFontsNum=20
spawnUnits:LineTextViewSystem*${initCounts}




#设置一行显示文本的最大量
[hiddenAction_setLineTextMax]
alsoTriggerAction:settingLineTextMax
alsoTriggerActionRepeat:memory.unitEpoll.size

[hiddenAction_settingLineTextMax]
sendMessageTo:memory.unitEpoll[index]
sendMessageWithTags:setTextMax
sendMessageWithData:textMax=memory.lineFontsNum




#在创建新TextViewUnit时，LineTextViewSystem会通过该action添加到epoll
[hiddenAction_addLTVSystemToEpoll]
autoTriggerOnEvent:newMessage(withTag="addLTVSystemToEpoll")
setUnitMemory:unitEpoll[memory.unitEpoll.size] = eventSource




#重新刷新每一个LineTextViewSystem的下标
[hiddenAction_initLTVSystemSoltId]
highPriorityQueue:true
alsoTriggerAction:initingLTVSystemSoltId
alsoTriggerActionRepeat:memory.unitEpoll.size

[hiddenAction_initingLTVSystemSoltId]
highPriorityQueue:true
sendMessageTo:memory.unitEpoll[index]
sendMessageWithTags:setSoltId
sendMessageWithData:slotId=index



#设置显示文本，过长不会截断
[hiddenAction_setText]
autoTriggerOnEvent:newMessage(withTag="setText")
setUnitMemory:text=eventData("text",type="string"),needInitLTVSystemSoltId=true,commonCallBackFlag=eventData("commonCallBackFlag",type="string"),commonCallBackTarget=eventSource
alsoQueueAction:StartCommonCallBack,needNewLTVSystem,initSettingText




#判断是否需要添加新的LineTextViewSystem
[hiddenAction_needNewLTVSystem]
buildSpeed:0.00s
requireConditional:if length(memory.text)/memory.lineFontsNum > memory.unitEpoll.size
alsoTriggerAction:spawnNewLTVSystem
setUnitMemory:needNewLTVSystemNum=length(memory.text)/memory.lineFontsNum - memory.unitEpoll.size
alsoTriggerActionRepeat:memory.needNewLTVSystemNum

#调用spawnNewLTVSystem生成
[hiddenAction_spawnNewLTVSystem]
spawnUnits:LineTextViewSystem
alsoQueueAction:initSettingText
alsoTriggerOrQueueActionConditional:if index+1 == memory.needNewLTVSystemNum




#显示text
[hiddenAction_initSettingText]
buildSpeed:0.00s
requireConditional:if memory.needInitLTVSystemSoltId == true and length(memory.text)/memory.lineFontsNum <= memory.unitEpoll.size
alsoTriggerAction:initLTVSystemSoltId,setLineTextMax
setUnitMemory:needInitLTVSystemSoltId=false
alsoQueueAction:doSettingText




[hiddenAction_doSettingText]
buildSpeed:0.0s
alsoTriggerAction:setingText
alsoTriggerActionRepeat:memory.unitEpoll.size




[hiddenAction_setingText]
sendMessageTo:memory.unitEpoll[index]
sendMessageWithTags:setText
sendMessageWithData:text=substring(memory.text,index*memory.lineFontsNum,(index+1)*memory.lineFontsNum)
