[core]
showOnMinimap:false
#onNewMapSpawn:emptyResourcePools_asNeutral
name:randore
createOnNeutralTeam:true
stayNeutral:true
availableInDemo:false
displayText:随机矿石
displayDescription:-石の大碟
class:CustomUnitMetadata
price:0
maxHp:6000
mass:100000
techLevel:1
buildSpeed:0.001
radius:10
tags:gen
explodeOnDeath:false
showInEditor:true
[attack]
canAttack:false
[graphics]
drawLayer:ground2
icon_zoomed_out:ROOT:icon/ore.png
total_frames:1
image:orel.png
image_wreak:NONE
image_shadow:NONE
shadowOffsetX:0
shadowOffsetY:2
scaleImagesTo:45
disableLowHpFire:true
disableLowHpSmoke:true
[movement]
movementType:LAND
moveSpeed:0.02
moveAccelerationSpeed:0.001
moveDecelerationSpeed:0
maxTurnSpeed:0.001
turnAcceleration:0.001
moveIgnoringBody:true
[hiddenAction_diedie]
autoTrigger:if not self.isInMap()
deleteSelf:true
[hiddenAction_rand1]
buildSpeed:0.1s
requireConditional:if (rnd(0,2) > 1.5 )
convertTo:ore_iron
[hiddenAction_rand2]
buildSpeed:0.1s
requireConditional:if (rnd(0,2) > 1.5)
convertTo:ore_dust
[hiddenAction_rand3]
buildSpeed:0.1s
requireConditional:if (rnd(0,2) > 1 )
convertTo:ore_tian
[hiddenAction_rand4]
buildSpeed:0.1s
requireConditional:if (rnd(0,2) > 1 )
convertTo:ore_cyst
[hiddenAction_rand5]
buildSpeed:0.1s
convertTo:ore_uran
requireConditional:if (rnd(0,2) > 1 )
[hiddenAction_rand6]
buildSpeed:0.1s
convertTo:rdata
[hiddenAction_created1]
buildSpeed:1
autoTriggerOnEvent:created
alsoQueueAction:rand1,rand2,rand3,rand4,rand5,rand6