[core]
copyFrom:ROOT:tmp/ore.template
name:rdata
displayText:废弃服务器
displayDescription:-也许可以修复?\n+16data,消耗16kW
class: CustomUnitMetadata
price:iron=1000,红宝石=1000,data=1024
maxHp:12000
mass:1000
techLevel:1
buildSpeed:0.1
availableInDemo: false
radius:25
isBio:false
isBuilder:false
#stayNeutral:true
createNeutral: true
resourceRate:0.5
tags:ore,rad-ore
borrowResourcesWhileAlive:电力=16
generation_active:if (not (self.resource.data > self.resource.datamax)and self.resource.电力>0)
generation_resources:data=16
generation_delay:40
[graphics]
drawLayer:ground2
icon_zoomed_out:ROOT:icon/ore.png
total_frames:1
image:ruinData.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:45
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
canAttack:false
[movement]
moveSpeed:0
maxTurnSpeed:0
movementType:HOVER