[core]
copyFrom:ROOT:tmp/ore.template
name:rdata
displayText:封存计算机容器
displayDescription:-被密封起来罐头状的计算机\n-内部数据密度很大\n-储存阵列已经损坏,也许可以修复?\n+16MB/s,消耗10kW\n-[高价值]可能会被优先攻击\n-[未知科技]不可被常规手段修复,注意保护
class: CustomUnitMetadata
price:iron=1000,红宝石=1000,data=1024
maxHp:12000
mass:1000
techLevel:1
buildSpeed:0.1
availableInDemo: false
radius:25
isBio:false
isBuilder:false
#stayNeutral:true
createNeutral: true
resourceRate:0.5
tags:ore,highValue
borrowResourcesWhileAlive:电力=10
generation_active:if (not (self.resource.data > self.resource.datamax)and self.resource.电力>0)
generation_resources:data=16
generation_delay:40
[graphics]
drawLayer:ground2
icon_zoomed_out:ROOT:icon/ore.png
total_frames:1
image:ruinData.png
image_wreak:NONE
image_turret: NONE
image_shadow: AUTO
scaleImagesTo:45
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
canAttack:false
[movement]
moveSpeed:0
maxTurnSpeed:0
movementType:HOVER
[resource_p]
displayName:fix
[action_fix]
#赌
text:尝试修复
description:尝试修复损坏部分\n-成功后可储存大量数据,运算速度提升至4倍\n-仅有33.3%的概率成功,请谨慎考虑
price:红宝石=4096,iron=550,data=512
buildSpeed:0.016s
alsoQueueAction:good,reset
addResources:p=1
isLocked:if self.resource.p == 1
isLockedMessage:已经在修复了QAQ
[hiddenAction_good]
requireConditional:if (rnd(0,3) < 1 )
buildSpeed:36.7s
convertTo:rser
[hiddenAction_reset]
addResources:p=-1