[core]
showInEditor:false
showOnMinimap:false
name:star_yellow
createOnAggressiveTeam:true
availableInDemo:false
displayText:黄星
displayDescription:-你应该叫它黄矮星
class:CustomUnitMetadata
price:0
maxHp:25000
selfRegenRate:1
mass:100000
techLevel:1
buildSpeed:0.001
radius:1
tags:star
explodeOnDeath:false
[attack]
canAttack:false
[graphics]
total_frames:1
image:star_yellow.png
image_wreak:NONE
image_shadow:NONE
shadowOffsetX:0
shadowOffsetY:2
scaleImagesTo:60
disableLowHpFire:true
disableLowHpSmoke:true
[movement]
movementType:AIR
moveSpeed:0.02
moveAccelerationSpeed:0.001
moveDecelerationSpeed:0
maxTurnSpeed:0.001
turnAcceleration:0.001
moveIgnoringBody:true
[hiddenAction_diedie]
autoTrigger:if not self.isInMap()
deleteSelf:true
#[hiddenAction_created1]
#buildSpeed:120s
#autoTriggerOnEvent:created
#spawnUnits:pc*1(offsetRandomXY=10)
[action_aigen]
autoTrigger:true
requireConditional:if (self.customTimer >= 10)
isVisible:false
addResources:红宝石=50
ai_isHighPriority:true
buildSpeed:0.1s
resetCustomTimer:true
spawnUnits:fighterDrone*1(offsetRandomXY=4500)
[decal_blare]
image:blare_yellow.png
imageScale:1.5
order:-1
alpha:0.2
[decal_blare2]
image:blare_yellow.png
imageScale:1
order:-1
alpha:0.4