[core]
showInEditor:false
name:meu
displayText:中浓缩铀棒[自燃]
displayDescription:中子放射函数[LINAR]:x*0.4+1\n每接受一个中子产生的热量:0.8K\n氙元素产生:x*0.5\n氙元素燃烧:x^2/50
maxHp:1000
autoTriggerCheckRate:every4Frames
price:红宝石=1000
shieldDisplayOnlyDeflection:true
mass:100
radius:4
experimental: true
generation_resources:rad=-0.2
generation_delay:40
generation_active:if self.resource.rad>0
[graphics]
icon_zoomed_out:ROOT:rad2.png
scaleImagesTo:5
image:uran.png
image_wreak:NONE
image_turret:NONE
image_shadow:NONE
#lock_body_rotation_with_main_turret:true
[attack]
canAttack:false
[resource_fluxf]
displayName:通量(快)
[resource_fluxss]
displayName:slowsum
[resource_dt]
displayName:deltaTemp
[resource_xenon]
displayName:氙中毒
[movement]
movementType:NONE
targetHeight:5
maxTurnSpeed:20
targetHeightDrift:1
[ai]
ai_upgradePriority:0.8

[action_re]
convertTo:rodEmp
displayType:upgrade
price:红宝石=-500
text:取消装填
buildSpeed:2s
whenBuilding_cannotMove:true
highPriorityQueue:true
isLocked:if self.resource.fluxf>20
isLockedMessage:您来晚辣
#int(self.x() + rnd(-3,3)),int(self.y() +f rnd(-3,3))
[hiddenAction_fluxe]
autoTrigger:true
addResourcesWithLogic:fluxf=(parent.resource.fluxss*(1 - self.resource.xenon/100))*0.4+1,dt=parent.resource.fluxss*0.4
[hiddenAction_xenonPosion]
autoTrigger:true
requireConditional:if ((self.resource.xenon+(parent.resource.fluxss*0.5-0.02*parent.resource.fluxss*parent.resource.fluxss))<=100 or ((self.resource.xenon+(parent.resource.fluxss*0.5-0.02*parent.resource.fluxss*parent.resource.fluxss)>0)))
# 屎山代码
addResourcesWithLogic:xenon=parent.resource.fluxss*0.5-0.02*parent.resource.fluxss*parent.resource.fluxss

[hiddenAction_fluxout]
autoTrigger:if self.resource.fluxf>100
addResources:fluxf=-10
spawnUnits:Mboom
[action_fluxfdisp]
iconImage:neutf.png
isVisible:true
text:(%{self.resource.fluxf})
textPostFix: 快中子通量
displayType:infoOnly
buildSpeed:0