[core]
showInEditor:false
name:rodUran
displayText:铀棒
displayDescription:-每秒消耗0.2rad\n-发射快中子\n-每秒最多向外发射4通量\n-内部通量堆积超过100会造成损坏\n-通量每秒增加=外部快中子通量*0.2+1
maxHp:1000
autoTriggerCheckRate:every4Frames
price:红宝石=1000
shieldDisplayOnlyDeflection:true
mass:100
radius:4
experimental: true
generation_resources:rad=-0.2
generation_delay:40
generation_active:if self.resource.rad>0
[graphics]
icon_zoomed_out:ROOT:rad2.png
scaleImagesTo:5
image:uran.png
image_wreak:NONE
image_turret:NONE
image_shadow:NONE
#lock_body_rotation_with_main_turret:true
[attack]
canAttack:false
[resource_fluxf]
displayName:通量(快)
[movement]
movementType:NONE
targetHeight:5
maxTurnSpeed:20
targetHeightDrift:1
[ai]
ai_upgradePriority:0.8

[action_re]
convertTo:rodEmp
displayType:upgrade
price:红宝石=-500
text:取消装填
buildSpeed:2s
whenBuilding_cannotMove:true
highPriorityQueue:true
isLocked:if self.resource.fluxf>20
isLockedMessage:您来晚辣
#int(self.x() + rnd(-3,3)),int(self.y() +f rnd(-3,3))
[hiddenAction_fluxe]
autoTrigger:true
addResourcesWithLogic:fluxf=(parent.resource.fluxf)*0.2+1
[hiddenAction_fluxemt]
#addResources:fluxf=-4
takeResources_includeParent:true
takeResources:fluxf=-4
autoTrigger:if self.resource.fluxf>4
[hiddenAction_fluxout]
autoTrigger:if self.resource.fluxf>100
addResources:fluxf=-10
spawnUnits:Mboom
[action_fluxfdisp]
iconImage:neutf.png
isVisible:true
text:(%{self.resource.fluxf})
textPostFix: 快中子通量
displayType:infoOnly
buildSpeed:0